// Dedicated wire-conformance fixture for the protobuf-es TS server.
//
// This is the ENCODE-side mirror of the client fixture
// (internal/tsclientgen/testdata/es/conformance.proto). The client proof asks
// "does fromJson decode what the Go server sent?"; this one asks the opposite
// and equally load-bearing question: "does toJson(create(...)) emit what a Go
// server would have emitted?" — because an es-mode server is what produces the
// body every sebuf client, Go or TS, has to read.
//
// The fields below are chosen so a single encode exercises every place where
// protobuf-es's canonical JSON output could drift from Go's protojson:
//   - zero-valued scalars/bools/lists must be OMITTED, not emitted as "" / 0 /
//     false / [];
//   - 64-bit ints must leave as JSON STRINGS, preserving values past 2^53;
//   - a partially-populated nested message must emit only its set fields;
//   - maps must emit as JSON objects;
//   - enums must emit as their NAME string, and the zero value must be omitted.
//
// It is intentionally standalone: no service, no sebuf/http imports, so
// protoc-gen-es emits a clean _pb module that only depends on
// @bufbuild/protobuf. Generate the JS the conformance test imports with:
//
//   protoc \
//     --plugin=protoc-gen-es=.scratch/es-spike/node_modules/.bin/protoc-gen-es \
//     --es_out=internal/tsservergen/testdata/es \
//     --es_opt=target=js,import_extension=js \
//     --proto_path=internal/tsservergen/testdata/es \
//     conformance.proto

// @generated by protoc-gen-es v2.12.1 with parameter "target=js,import_extension=js"
// @generated from file conformance.proto (package test.serverconformance, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv2";

/**
 * Describes the file conformance.proto.
 */
export const file_conformance = /*@__PURE__*/
  fileDesc("ChFjb25mb3JtYW5jZS5wcm90bxIWdGVzdC5zZXJ2ZXJjb25mb3JtYW5jZSIgCgRJdGVtEgsKA3NrdRgBIAEoCRILCgNxdHkYAiABKAUiqgQKDlNlcnZlclJlc3BvbnNlEgoKAmlkGAEgASgJEhEKCWJpZ190b3RhbBgCIAEoAxIqCgRpdGVtGAMgASgLMhwudGVzdC5zZXJ2ZXJjb25mb3JtYW5jZS5JdGVtEkoKCmF0dHJpYnV0ZXMYBCADKAsyNi50ZXN0LnNlcnZlcmNvbmZvcm1hbmNlLlNlcnZlclJlc3BvbnNlLkF0dHJpYnV0ZXNFbnRyeRIuCgZzdGF0dXMYBSABKA4yHi50ZXN0LnNlcnZlcmNvbmZvcm1hbmNlLlN0YXR1cxIMCgRuYW1lGAYgASgJEg0KBWNvdW50GAcgASgFEg4KBmFjdGl2ZRgIIAEoCBINCgVyYXRpbxgJIAEoARIOCgZsYWJlbHMYCiADKAkSPgoEdGFncxgLIAMoCzIwLnRlc3Quc2VydmVyY29uZm9ybWFuY2UuU2VydmVyUmVzcG9uc2UuVGFnc0VudHJ5EiwKBmRldGFpbBgMIAEoCzIcLnRlc3Quc2VydmVyY29uZm9ybWFuY2UuSXRlbRI3Cg9mYWxsYmFja19zdGF0dXMYDSABKA4yHi50ZXN0LnNlcnZlcmNvbmZvcm1hbmNlLlN0YXR1cxoxCg9BdHRyaWJ1dGVzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ARorCglUYWdzRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgJOgI4ASozCgZTdGF0dXMSFgoSU1RBVFVTX1VOU1BFQ0lGSUVEEAASEQoNU1RBVFVTX0FDVElWRRABYgZwcm90bzM");

/**
 * Describes the message test.serverconformance.Item.
 * Use `create(ItemSchema)` to create a new message.
 */
export const ItemSchema = /*@__PURE__*/
  messageDesc(file_conformance, 0);

/**
 * Describes the message test.serverconformance.ServerResponse.
 * Use `create(ServerResponseSchema)` to create a new message.
 */
export const ServerResponseSchema = /*@__PURE__*/
  messageDesc(file_conformance, 1);

/**
 * Describes the enum test.serverconformance.Status.
 */
export const StatusSchema = /*@__PURE__*/
  enumDesc(file_conformance, 0);

/**
 * @generated from enum test.serverconformance.Status
 */
export const Status = /*@__PURE__*/
  tsEnum(StatusSchema);

