// @generated by protoc-gen-es v2.12.1 with parameter "target=ts,import_extension=js"
// @generated from file multi_word_oneof.proto (package testdata.multi_word_oneof, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_sebuf_http_annotations } from "./sebuf/http/annotations_pb.js";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file multi_word_oneof.proto.
 */
export const file_multi_word_oneof: GenFile = /*@__PURE__*/
  fileDesc("ChZtdWx0aV93b3JkX29uZW9mLnByb3RvEhl0ZXN0ZGF0YS5tdWx0aV93b3JkX29uZW9mIhsKC1RleHRDb250ZW50EgwKBGJvZHkYASABKAkiOgoMSW1hZ2VDb250ZW50EgsKA3VybBgBIAEoCRINCgV3aWR0aBgCIAEoBRIOCgZoZWlnaHQYAyABKAUiqwEKDk11bHRpV29yZEV2ZW50EgoKAmlkGAEgASgJEjoKCGJpZ190ZXh0GAIgASgLMiYudGVzdGRhdGEubXVsdGlfd29yZF9vbmVvZi5UZXh0Q29udGVudEgAEjwKCWJpZ19pbWFnZRgDIAEoCzInLnRlc3RkYXRhLm11bHRpX3dvcmRfb25lb2YuSW1hZ2VDb250ZW50SABCEwoRc3VwZXJfdGl0bGVfaW1hZ2UyrwEKFU11bHRpV29yZE9uZW9mU2VydmljZRKGAQoSVGVzdE11bHRpV29yZEV2ZW50EikudGVzdGRhdGEubXVsdGlfd29yZF9vbmVvZi5NdWx0aVdvcmRFdmVudBopLnRlc3RkYXRhLm11bHRpX3dvcmRfb25lb2YuTXVsdGlXb3JkRXZlbnQiGpq1GBYKEi9ldmVudHMvbXVsdGktd29yZBACGg2itRgJCgcvYXBpL3YxQl1aW2dpdGh1Yi5jb20vU2ViYXN0aWVuTWVsa2kvc2VidWYvaW50ZXJuYWwvdHNjbGllbnRnZW4vdGVzdGRhdGEvbXVsdGl3b3Jkb25lb2Y7bXVsdGl3b3Jkb25lb2ZiBnByb3RvMw", [file_sebuf_http_annotations]);

/**
 * Variant message types
 *
 * @generated from message testdata.multi_word_oneof.TextContent
 */
export type TextContent = Message<"testdata.multi_word_oneof.TextContent"> & {
  /**
   * @generated from field: string body = 1;
   */
  body: string;
};

/**
 * Describes the message testdata.multi_word_oneof.TextContent.
 * Use `create(TextContentSchema)` to create a new message.
 */
export const TextContentSchema: GenMessage<TextContent> = /*@__PURE__*/
  messageDesc(file_multi_word_oneof, 0);

/**
 * @generated from message testdata.multi_word_oneof.ImageContent
 */
export type ImageContent = Message<"testdata.multi_word_oneof.ImageContent"> & {
  /**
   * @generated from field: string url = 1;
   */
  url: string;

  /**
   * @generated from field: int32 width = 2;
   */
  width: number;

  /**
   * @generated from field: int32 height = 3;
   */
  height: number;
};

/**
 * Describes the message testdata.multi_word_oneof.ImageContent.
 * Use `create(ImageContentSchema)` to create a new message.
 */
export const ImageContentSchema: GenMessage<ImageContent> = /*@__PURE__*/
  messageDesc(file_multi_word_oneof, 1);

/**
 * Message with a multi-word oneof name and no oneof_config annotation.
 *
 * The oneof name (super_title_image) is deliberately multi-word: it must
 * surface in the generated TypeScript only as the PascalCase union type name
 * (MultiWordEventSuperTitleImage) and must NEVER leak as a raw snake_case
 * wrapper property. Because the oneof is un-annotated it takes the
 * presence-discriminated flat-union path, matching plain protojson.
 *
 * @generated from message testdata.multi_word_oneof.MultiWordEvent
 */
export type MultiWordEvent = Message<"testdata.multi_word_oneof.MultiWordEvent"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from oneof testdata.multi_word_oneof.MultiWordEvent.super_title_image
   */
  superTitleImage: {
    /**
     * @generated from field: testdata.multi_word_oneof.TextContent big_text = 2;
     */
    value: TextContent;
    case: "bigText";
  } | {
    /**
     * @generated from field: testdata.multi_word_oneof.ImageContent big_image = 3;
     */
    value: ImageContent;
    case: "bigImage";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message testdata.multi_word_oneof.MultiWordEvent.
 * Use `create(MultiWordEventSchema)` to create a new message.
 */
export const MultiWordEventSchema: GenMessage<MultiWordEvent> = /*@__PURE__*/
  messageDesc(file_multi_word_oneof, 2);

/**
 * @generated from service testdata.multi_word_oneof.MultiWordOneofService
 */
export const MultiWordOneofService: GenService<{
  /**
   * @generated from rpc testdata.multi_word_oneof.MultiWordOneofService.TestMultiWordEvent
   */
  testMultiWordEvent: {
    methodKind: "unary";
    input: typeof MultiWordEventSchema;
    output: typeof MultiWordEventSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_multi_word_oneof, 0);

