// Package swiftoneofhelper provides helper functions for Swift protobuf messages with oneof fields.
package swiftoneofhelper

import (
	"fmt"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/reflect/protoreflect"
)

const (
	// Swift type mappings
	swiftString  = "String"
	swiftInt32   = "Int32"
	swiftInt64   = "Int64"
	swiftUInt32  = "UInt32"
	swiftUInt64  = "UInt64"
	swiftBool    = "Bool"
	swiftFloat   = "Float"
	swiftDouble  = "Double"
	swiftData    = "Data"
)

// GenerateHelpers generates Swift helper extensions for all messages with oneofs in the given file.
func GenerateHelpers(plugin *protogen.Plugin, file *protogen.File) {
	filename := file.GeneratedFilenamePrefix + "_helpers.swift"
	g := plugin.NewGeneratedFile(filename, file.GoImportPath)

	// Write Swift file header
	g.P("// Code generated by protoc-gen-swift-oneof-helper. DO NOT EDIT.")
	g.P()
	g.P("import Foundation")
	g.P("import SwiftProtobuf")
	g.P()

	// Generate helpers for each message with oneofs
	for _, message := range file.Messages {
		generateMessageHelpers(g, message)
	}
}

// generateMessageHelpers generates Swift helper extensions for a single message and its nested messages.
func generateMessageHelpers(g *protogen.GeneratedFile, message *protogen.Message) {
	// Generate helpers for oneofs in this message
	if len(message.Oneofs) > 0 {
		generateSwiftExtension(g, message)
	}

	// Recurse into nested messages
	for _, nested := range message.Messages {
		generateMessageHelpers(g, nested)
	}
}

// generateSwiftExtension generates a Swift extension with convenience initializers for oneof fields.
func generateSwiftExtension(g *protogen.GeneratedFile, message *protogen.Message) {
	messageName := message.GoIdent.GoName
	
	g.P("// MARK: - ", messageName, " Oneof Helpers")
	g.P("extension ", messageName, " {")
	g.P()

	// Generate convenience initializers for each oneof field
	for _, oneof := range message.Oneofs {
		for _, field := range oneof.Fields {
			generateOneofConvenienceInit(g, message, oneof, field)
		}
	}

	// Generate static factory methods for each oneof field
	for _, oneof := range message.Oneofs {
		for _, field := range oneof.Fields {
			generateOneofStaticFactory(g, message, oneof, field)
		}
	}

	g.P("}")
	g.P()
}

// generateOneofConvenienceInit generates a convenience initializer for a specific oneof field.
func generateOneofConvenienceInit(g *protogen.GeneratedFile, message *protogen.Message,
	oneof *protogen.Oneof, field *protogen.Field,
) {
	if field.Message == nil {
		return // Only generate helpers for message-type oneof fields
	}

	messageName := message.GoIdent.GoName
	fieldName := field.GoName
	oneofName := swiftFieldName(oneof.GoName)
	
	// Build parameter list from the nested message fields
	var params []string
	var assignments []string

	for _, nestedField := range field.Message.Fields {
		paramName := swiftParameterName(nestedField.GoName)
		paramType := getSwiftFieldType(nestedField)
		params = append(params, fmt.Sprintf("%s: %s", paramName, paramType))
		
		swiftFieldName := swiftFieldName(nestedField.GoName)
		assignments = append(assignments, fmt.Sprintf("        messageField.%s = %s", swiftFieldName, paramName))
	}

	// Generate convenience initializer
	g.P("    /// Convenience initializer for ", messageName, " with ", fieldName, " oneof field")
	g.P("    init(", strings.Join(params, ", "), ") {")
	g.P("        self.init()")
	g.P("        var messageField = ", field.Message.GoIdent.GoName, "()")

	for _, assignment := range assignments {
		g.P(assignment)
	}

	g.P("        self.", oneofName, " = .", swiftFieldName(fieldName), "(messageField)")
	g.P("    }")
	g.P()
}

// generateOneofStaticFactory generates a static factory method for a specific oneof field.
func generateOneofStaticFactory(g *protogen.GeneratedFile, message *protogen.Message,
	oneof *protogen.Oneof, field *protogen.Field,
) {
	if field.Message == nil {
		return // Only generate helpers for message-type oneof fields
	}

	messageName := message.GoIdent.GoName
	fieldName := field.GoName
	oneofName := swiftFieldName(oneof.GoName)

	// Build parameter list from the nested message fields
	var params []string
	var assignments []string

	for _, nestedField := range field.Message.Fields {
		paramName := swiftParameterName(nestedField.GoName)
		paramType := getSwiftFieldType(nestedField)
		params = append(params, fmt.Sprintf("%s: %s", paramName, paramType))
		
		swiftFieldName := swiftFieldName(nestedField.GoName)
		assignments = append(assignments, fmt.Sprintf("        messageField.%s = %s", swiftFieldName, paramName))
	}

	// Generate static factory method
	g.P("    /// Static factory method for ", messageName, " with ", fieldName, " oneof field")
	g.P("    static func with", fieldName, "(", strings.Join(params, ", "), ") -> ", messageName, " {")
	g.P("        var message = ", messageName, "()")
	g.P("        var messageField = ", field.Message.GoIdent.GoName, "()")

	for _, assignment := range assignments {
		g.P(assignment)
	}

	g.P("        message.", oneofName, " = .", swiftFieldName(fieldName), "(messageField)")
	g.P("        return message")
	g.P("    }")
	g.P()
}

// getSwiftFieldType determines the Swift type for a protobuf field.
func getSwiftFieldType(field *protogen.Field) string {
	// Handle repeated fields
	if field.Desc.IsList() {
		return "[" + getSingleSwiftFieldType(field) + "]"
	}

	// Handle map fields
	if field.Desc.IsMap() {
		return getSwiftMapType(field)
	}

	// Handle optional fields (proto3 optional)
	if field.Desc.HasOptionalKeyword() {
		return getSingleSwiftFieldType(field) + "?"
	}

	return getSingleSwiftFieldType(field)
}

// getSingleSwiftFieldType returns the Swift type for a single (non-repeated, non-map) protobuf field.
func getSingleSwiftFieldType(field *protogen.Field) string {
	switch field.Desc.Kind() {
	case protoreflect.StringKind:
		return swiftString
	case protoreflect.BoolKind:
		return swiftBool
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return swiftInt32
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return swiftInt64
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return swiftUInt32
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return swiftUInt64
	case protoreflect.FloatKind:
		return swiftFloat
	case protoreflect.DoubleKind:
		return swiftDouble
	case protoreflect.BytesKind:
		return swiftData
	case protoreflect.EnumKind:
		if field.Enum != nil {
			return field.Enum.GoIdent.GoName
		}
		return swiftInt32 // fallback for enums
	case protoreflect.MessageKind:
		if field.Message != nil {
			return field.Message.GoIdent.GoName
		}
		return "Any" // fallback
	default:
		return "Any"
	}
}

// getSwiftMapType returns the Swift type for a map field.
func getSwiftMapType(field *protogen.Field) string {
	keyType := getSwiftMapKeyType(field.Desc.MapKey())
	valueType := getSwiftMapValueType(field)
	return fmt.Sprintf("[%s: %s]", keyType, valueType)
}

// getSwiftMapKeyType returns the Swift type for a map key.
func getSwiftMapKeyType(desc protoreflect.FieldDescriptor) string {
	switch desc.Kind() {
	case protoreflect.StringKind:
		return swiftString
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return swiftInt32
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return swiftInt64
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return swiftUInt32
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return swiftUInt64
	case protoreflect.BoolKind:
		return swiftBool
	default:
		return swiftString // Default to String for map keys
	}
}

// getSwiftMapValueType returns the Swift type for a map value.
func getSwiftMapValueType(field *protogen.Field) string {
	mapValue := field.Desc.MapValue()
	
	switch mapValue.Kind() {
	case protoreflect.StringKind:
		return swiftString
	case protoreflect.BoolKind:
		return swiftBool
	case protoreflect.Int32Kind, protoreflect.Sint32Kind, protoreflect.Sfixed32Kind:
		return swiftInt32
	case protoreflect.Int64Kind, protoreflect.Sint64Kind, protoreflect.Sfixed64Kind:
		return swiftInt64
	case protoreflect.Uint32Kind, protoreflect.Fixed32Kind:
		return swiftUInt32
	case protoreflect.Uint64Kind, protoreflect.Fixed64Kind:
		return swiftUInt64
	case protoreflect.FloatKind:
		return swiftFloat
	case protoreflect.DoubleKind:
		return swiftDouble
	case protoreflect.BytesKind:
		return swiftData
	case protoreflect.MessageKind:
		// For map values that are messages, we need to find the actual message type
		if field.Message != nil && field.Message.Fields != nil && len(field.Message.Fields) > 1 {
			// Map entry messages have exactly 2 fields: key and value
			for _, f := range field.Message.Fields {
				if f.Desc.Number() == 2 { // value field is always number 2
					return getSingleSwiftFieldType(f)
				}
			}
		}
		return "Any"
	default:
		return "Any"
	}
}

// swiftFieldName converts a Go protobuf field name to Swift field name convention.
func swiftFieldName(goName string) string {
	if goName == "" {
		return ""
	}
	
	// Convert from GoName (e.g., "AuthMethod") to Swift field name (e.g., "authMethod")
	return strings.ToLower(goName[:1]) + goName[1:]
}

// swiftParameterName converts a Go protobuf field name to Swift parameter name convention.
func swiftParameterName(goName string) string {
	// Swift parameter names are typically lowerCamelCase
	return swiftFieldName(goName)
}