// Code generated by sebuf. DO NOT EDIT.
// source: nestedcollision/v1/nested_collision.proto

import type { Wrapper } from "./wrapper.js";

export interface GetStatusRequest {
  id: string;
}

export interface GetStatusResponse {
  status?: Status;
  kind: Kind;
  wrapper?: Wrapper;
}

export interface Status {
  code: string;
  message: string;
}

export type Kind = "KIND_UNSPECIFIED" | "KIND_ALPHA";

