// Code generated by protoc-gen-go-oneof-helper. DO NOT EDIT.

package testdata

// NewLoginRequestEmail creates a new LoginRequest with Email set
func NewLoginRequestEmail(retryCount int32, clientId string, timestamp int64, rememberMe bool, email string, password string) *LoginRequest {
	return &LoginRequest{
		RetryCount: retryCount,
		ClientId:   clientId,
		Timestamp:  timestamp,
		RememberMe: rememberMe,
		AuthMethod: &LoginRequest_Email{
			Email: &EmailAuth{
				Email:    email,
				Password: password,
			},
		},
	}
}

// NewLoginRequestToken creates a new LoginRequest with Token set
func NewLoginRequestToken(retryCount int32, clientId string, timestamp int64, rememberMe bool, token string, tokenType string) *LoginRequest {
	return &LoginRequest{
		RetryCount: retryCount,
		ClientId:   clientId,
		Timestamp:  timestamp,
		RememberMe: rememberMe,
		AuthMethod: &LoginRequest_Token{
			Token: &TokenAuth{
				Token:     token,
				TokenType: tokenType,
			},
		},
	}
}

// NewConfigMessageDatabase creates a new ConfigMessage with Database set
func NewConfigMessageDatabase(name string, version int32, enabled bool, tags []string, host string, port int32) *ConfigMessage {
	return &ConfigMessage{
		Name:    name,
		Version: version,
		Enabled: enabled,
		Tags:    tags,
		StorageConfig: &ConfigMessage_Database{
			Database: &DatabaseConfig{
				Host: host,
				Port: port,
			},
		},
	}
}

// NewConfigMessageFile creates a new ConfigMessage with File set
func NewConfigMessageFile(name string, version int32, enabled bool, tags []string, path string) *ConfigMessage {
	return &ConfigMessage{
		Name:    name,
		Version: version,
		Enabled: enabled,
		Tags:    tags,
		StorageConfig: &ConfigMessage_File{
			File: &FileConfig{
				Path: path,
			},
		},
	}
}
