// Code generated by protoc-gen-csharp-http. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Runtime.Serialization;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace Test.Contracts
{
    public enum ItemState
    {
        [EnumMember(Value = "STATE_UNSPECIFIED")]
        StateUnspecified = 0,
        [EnumMember(Value = "STATE_READY")]
        StateReady = 1,
    }

    public class ApiException : Exception
    {
        public int StatusCode { get; }
        public string ResponseBody { get; }
        public IReadOnlyDictionary<string, IEnumerable<string>> Headers { get; }

        public ApiException(
            int statusCode,
            string responseBody,
            IReadOnlyDictionary<string, IEnumerable<string>>? headers = null)
            : base($"Request failed with status {statusCode}: {responseBody}")
        {
            StatusCode = statusCode;
            ResponseBody = responseBody;
            Headers = headers ?? new Dictionary<string, IEnumerable<string>>();
        }
    }

    public sealed class FieldViolation
    {
        [JsonProperty("field")]
        public string Field { get; set; } = string.Empty;
        [JsonProperty("description")]
        public string Description { get; set; } = string.Empty;
    }

    public sealed class ValidationException : ApiException
    {
        public IReadOnlyList<FieldViolation> Violations { get; }

        public ValidationException(
            int statusCode,
            string responseBody,
            IReadOnlyDictionary<string, IEnumerable<string>> headers,
            IReadOnlyList<FieldViolation> violations)
            : base(statusCode, responseBody, headers)
        {
            Violations = violations;
        }
    }

    public sealed class Item
    {
        [JsonProperty("id")]
        public string Id { get; set; }
        [JsonProperty("tags")]
        public List<string> Tags { get; set; }
        [JsonProperty("meta")]
        public Dictionary<string, object>? Meta { get; set; }
        [JsonProperty("state")]
        public ItemState State { get; set; }
        [JsonProperty("details")]
        public ItemDetails? Details { get; set; }
    }

    public sealed class ItemDetails
    {
        [JsonProperty("note")]
        public string Note { get; set; }
        [JsonProperty("scores")]
        public List<int> Scores { get; set; }
    }

    public sealed class FetchItemRequest
    {
        [JsonProperty("id")]
        public string Id { get; set; }
    }

    public sealed class ContractServiceClientOptions
    {
        public HttpClient? HttpClient { get; set; }
        public Dictionary<string, string>? DefaultHeaders { get; set; }
        public TimeSpan? Timeout { get; set; }
        public string ContentType { get; set; } = "application/json";
    }

    public sealed class ContractServiceCallOptions
    {
        public Dictionary<string, string>? Headers { get; set; }
        public TimeSpan? Timeout { get; set; }
        public string? ContentType { get; set; }
    }

    public interface IContractServiceClient
    {
        Task<Item> FetchItemAsync(FetchItemRequest req, ContractServiceCallOptions? options = null, CancellationToken cancellationToken = default);
    }

    public sealed class ContractServiceClient : IContractServiceClient
    {
        private readonly string _baseUrl;
        private readonly HttpClient _httpClient;
        private readonly Dictionary<string, string> _defaultHeaders;
        private readonly TimeSpan? _timeout;
        private readonly string _contentType;

        public ContractServiceClient(string baseUrl, ContractServiceClientOptions? options = null)
        {
            _baseUrl = baseUrl.TrimEnd('/');
            _httpClient = options?.HttpClient ?? new HttpClient();
            _defaultHeaders = options?.DefaultHeaders is null
                ? new Dictionary<string, string>()
                : new Dictionary<string, string>(options.DefaultHeaders);
            _timeout = options?.Timeout;
            _contentType = options?.ContentType ?? "application/json";
        }

        public async Task<Item> FetchItemAsync(FetchItemRequest req, ContractServiceCallOptions? options = null, CancellationToken cancellationToken = default)
        {
            var contentType = options?.ContentType ?? _contentType;
            if (!string.Equals(contentType, "application/json", StringComparison.OrdinalIgnoreCase))
            {
                throw new NotSupportedException("Only application/json is implemented by the C# client generator.");
            }
            var path = "/";
            var query = new List<string>();
            var requestUri = query.Count == 0 ? path : path + "?" + string.Join("&", query);
            var headers = BuildHeaders(options);
            return await SendAsync<Item>(HttpMethod.Post, requestUri, req, headers, contentType, options?.Timeout ?? _timeout, cancellationToken);
        }

        private Dictionary<string, string> BuildHeaders(ContractServiceCallOptions? options)
        {
            var headers = new Dictionary<string, string>(_defaultHeaders);
            headers["Accept"] = "application/json";
            if (options?.Headers is not null)
            {
                foreach (var pair in options.Headers)
                {
                    headers[pair.Key] = pair.Value;
                }
            }
            return headers;
        }

        private async Task<TResponse> SendAsync<TResponse>(HttpMethod method, string requestUri, object? body, Dictionary<string, string> headers, string contentType, TimeSpan? timeout, CancellationToken cancellationToken) where TResponse : new()
        {
            using var request = new HttpRequestMessage(method, _baseUrl + requestUri);
            foreach (var header in headers)
            {
                request.Headers.TryAddWithoutValidation(header.Key, header.Value);
            }
            if (body is not null)
            {
                request.Content = new StringContent(SerializeRequest(body), Encoding.UTF8, contentType);
            }
            using var timeoutCancellation = timeout is null ? null : new CancellationTokenSource(timeout.Value);
            using var linkedCancellation = timeoutCancellation is null ? null : CancellationTokenSource.CreateLinkedTokenSource(cancellationToken, timeoutCancellation.Token);
            var effectiveCancellationToken = linkedCancellation?.Token ?? cancellationToken;
            using var response = await _httpClient.SendAsync(request, effectiveCancellationToken);
            var responseBody = response.Content is null ? string.Empty : await response.Content.ReadAsStringAsync(effectiveCancellationToken);
            var responseHeaders = CollectResponseHeaders(response);
            if (!response.IsSuccessStatusCode)
            {
                throw CreateApiException((int)response.StatusCode, responseBody, responseHeaders);
            }
            if (typeof(TResponse) == typeof(Empty) && string.IsNullOrWhiteSpace(responseBody))
            {
                return new TResponse();
            }
            if (string.IsNullOrWhiteSpace(responseBody))
            {
                return new TResponse();
            }
            var result = DeserializeResponse<TResponse>(responseBody);
            return result is null ? new TResponse() : result;
        }

        private static IReadOnlyDictionary<string, IEnumerable<string>> CollectResponseHeaders(
            HttpResponseMessage response)
        {
            var headers = new Dictionary<string, IEnumerable<string>>(StringComparer.OrdinalIgnoreCase);
            foreach (var header in response.Headers)
            {
                headers[header.Key] = header.Value.ToArray();
            }
            if (response.Content is not null)
            {
                foreach (var header in response.Content.Headers)
                {
                    headers[header.Key] = header.Value.ToArray();
                }
            }
            return headers;
        }

        private static ApiException CreateApiException(
            int statusCode,
            string responseBody,
            IReadOnlyDictionary<string, IEnumerable<string>> headers)
        {
            if (!string.IsNullOrWhiteSpace(responseBody))
            {
                try
                {
                    var parsed = JObject.Parse(responseBody);
                    if (statusCode == 400 && parsed["violations"] is JArray violationArray)
                    {
                        var violations = violationArray.ToObject<List<FieldViolation>>()
                            ?? new List<FieldViolation>();
                        return new ValidationException(statusCode, responseBody, headers, violations);
                    }
                }
                catch (JsonException)
                {
                    // Malformed or non-JSON error bodies fall back to ApiException.
                }
            }
            return new ApiException(statusCode, responseBody, headers);
        }

        private string SerializeRequest(object value)
        {
            var json = JsonConvert.SerializeObject(value);
            return NormalizeSerializedJson(value, json);
        }

        private static TResponse? DeserializeResponse<TResponse>(string json)
        {
            json = NormalizeResponseJson(typeof(TResponse), json);
            return JsonConvert.DeserializeObject<TResponse>(json);
        }

        private static string NormalizeSerializedJson(object value, string json)
        {
            var token = JToken.Parse(json);
            var normalized = NormalizeSerializedToken(value.GetType(), token);
            return normalized.ToString(Formatting.None);
        }

        private static string NormalizeResponseJson(Type responseType, string json)
        {
            var token = JToken.Parse(json);
            var normalized = NormalizeResponseToken(responseType, token);
            return normalized.ToString(Formatting.None);
        }

        private static JToken NormalizeSerializedToken(Type messageType, JToken token)
        {
            return messageType.Name switch
            {
                "Item" => NormalizeSerializedItem(token),
                _ => token
            };
        }
        private static JToken NormalizeResponseToken(Type messageType, JToken token)
        {
            return messageType.Name switch
            {
                "Item" => NormalizeResponseItem(token),
                _ => token
            };
        }
        private static JToken NormalizeMapValueForSerialization(JToken token, Type messageType)
        {
            return messageType.Name switch
            {
                _ => NormalizeSerializedToken(messageType, token)
            };
        }
        private static JToken NormalizeMapValueForResponse(JToken token, Type messageType)
        {
            return messageType.Name switch
            {
                _ => NormalizeResponseToken(messageType, token)
            };
        }
        private static bool IsEmptyObject(JToken token)
        {
            return token is JObject obj && !obj.Properties().Any();
        }
        private static bool ShouldOmitEmptyField(JToken token)
        {
            return token.Type == JTokenType.Null || IsEmptyObject(token);
        }

        private static JToken NormalizeSerializedItem(JToken token)
        {
            if (token is not JObject obj)
            {
                return token;
            }
            if (obj.TryGetValue("state", out var StateEnumToken))
            {
                if (obj["state"].Type == JTokenType.Integer)
                {
                    obj["state"] = EncodeEnumValue(typeof(ItemState), obj["state"].Value<long>());
                }
            }
            return obj;
        }

        private static JToken NormalizeResponseItem(JToken token)
        {
            if (token is not JObject obj)
            {
                return token;
            }
            if (obj.TryGetValue("state", out var StateEnumToken))
            {
                if (obj["state"].Type == JTokenType.String)
                {
                    obj["state"] = DecodeEnumValue(typeof(ItemState), obj["state"].Value<string>()!);
                }
            }
            return obj;
        }

        private static string EncodeEnumValue(Type enumType, long value)
        {
            var enumValue = Enum.ToObject(enumType, value);
            var name = Enum.GetName(enumType, enumValue) ?? value.ToString();
            var member = enumType.GetMember(name).FirstOrDefault();
            var mapping = member?.GetCustomAttributes(typeof(EnumMemberAttribute), false)
                .OfType<EnumMemberAttribute>().FirstOrDefault()?.Value;
            return mapping ?? name;
        }

        private static long DecodeEnumValue(Type enumType, string value)
        {
            foreach (var member in enumType.GetFields().Where(field => field.IsStatic))
            {
                var mapping = member.GetCustomAttributes(typeof(EnumMemberAttribute), false)
                    .OfType<EnumMemberAttribute>().FirstOrDefault()?.Value;
                if (string.Equals(mapping ?? member.Name, value, StringComparison.Ordinal))
                {
                    return Convert.ToInt64(member.GetValue(null));
                }
            }
            if (long.TryParse(value, out var numericValue))
            {
                return numericValue;
            }
            throw new InvalidOperationException($"Unknown {enumType.Name} wire value '{value}'.");
        }

        private static string EncodeBytes(byte[] bytes, string encoding)
        {
            var base64 = Convert.ToBase64String(bytes);
            return encoding switch
            {
                "base64_raw" => base64.TrimEnd('='),
                "base64url" => base64.Replace('+', '-').Replace('/', '_'),
                "base64url_raw" => base64.Replace('+', '-').Replace('/', '_').TrimEnd('='),
                "hex" => Convert.ToHexString(bytes).ToLowerInvariant(),
                _ => base64
            };
        }

        private static string ReencodeBytes(string encoded, string fromEncoding, string toEncoding)
        {
            return EncodeBytes(DecodeBytes(encoded, fromEncoding), toEncoding);
        }

        private static byte[] DecodeBytes(string encoded, string encoding)
        {
            return encoding switch
            {
                "hex" => Convert.FromHexString(encoded),
                "base64url" => Convert.FromBase64String(NormalizeBase64(encoded.Replace('-', '+').Replace('_', '/'))),
                "base64url_raw" => Convert.FromBase64String(NormalizeBase64(encoded.Replace('-', '+').Replace('_', '/'))),
                "base64_raw" => Convert.FromBase64String(NormalizeBase64(encoded)),
                _ => Convert.FromBase64String(NormalizeBase64(encoded))
            };
        }

        private static string NormalizeBase64(string value)
        {
            var remainder = value.Length % 4;
            if (remainder == 0)
            {
                return value;
            }
            return value + new string('=', 4 - remainder);
        }

        private static string FormatPathValue(object? value)
        {
            return value?.ToString() ?? string.Empty;
        }

        private static string FormatQueryValue(object? value)
        {
            return value?.ToString() ?? string.Empty;
        }

    }

    public static class ServiceContracts
    {
        public static class ContractService
        {
            public const string Name = "ContractService";
            public const string BasePath = "";
            public static class FetchItem
            {
                public const string HttpMethod = "POST";
                public const string Path = "/";
                public const string RequestType = "FetchItemRequest";
                public const string ResponseType = "Item";
            }
        }
    }
}
