// Code generated by protoc-gen-csharp-http. DO NOT EDIT.
#nullable enable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Net.Http;
using System.Runtime.Serialization;
using System.Text;
using System.Threading;
using System.Threading.Tasks;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;

namespace Test.Contracts
{
    public enum ItemState
    {
        [EnumMember(Value = "STATE_UNSPECIFIED")]
        StateUnspecified = 0,
        [EnumMember(Value = "STATE_READY")]
        StateReady = 1,
    }

    public sealed class ApiException : Exception
    {
        public int StatusCode { get; }
        public string ResponseBody { get; }

        public ApiException(int statusCode, string responseBody)
            : base($\"Request failed with status {statusCode}: {responseBody}\")
        {
            StatusCode = statusCode;
            ResponseBody = responseBody;
        }
    }

    public sealed class Item
    {
        [JsonProperty("id")]
        public string Id { get; set; }
        [JsonProperty("tags")]
        public List<string> Tags { get; set; }
        [JsonProperty("meta")]
        public Dictionary<string, object>? Meta { get; set; }
        [JsonProperty("state")]
        [JsonConverter(typeof(StringEnumConverter))]
        public ItemState State { get; set; }
        [JsonProperty("details")]
        public ItemDetails? Details { get; set; }
    }

    public sealed class ItemDetails
    {
        [JsonProperty("note")]
        public string Note { get; set; }
        [JsonProperty("scores")]
        public List<int> Scores { get; set; }
    }

    public sealed class FetchItemRequest
    {
        [JsonProperty("id")]
        public string Id { get; set; }
    }

    public sealed class ContractServiceClientOptions
    {
        public HttpClient? HttpClient { get; set; }
        public Dictionary<string, string>? DefaultHeaders { get; set; }
    }

    public sealed class ContractServiceCallOptions
    {
        public Dictionary<string, string>? Headers { get; set; }
    }

    public interface IContractServiceClient
    {
        Task<Item> FetchItemAsync(FetchItemRequest req, ContractServiceCallOptions? options = null, CancellationToken cancellationToken = default);
    }

    public sealed class ContractServiceClient : IContractServiceClient
    {
        private readonly string _baseUrl;
        private readonly HttpClient _httpClient;
        private readonly Dictionary<string, string> _defaultHeaders;

        public ContractServiceClient(string baseUrl, ContractServiceClientOptions? options = null)
        {
            _baseUrl = baseUrl.TrimEnd('/');
            _httpClient = options?.HttpClient ?? new HttpClient();
            _defaultHeaders = options?.DefaultHeaders is null
                ? new Dictionary<string, string>()
                : new Dictionary<string, string>(options.DefaultHeaders);
        }

        public async Task<Item> FetchItemAsync(FetchItemRequest req, ContractServiceCallOptions? options = null, CancellationToken cancellationToken = default)
        {
            var path = "/";
            var query = new List<string>();
            var requestUri = query.Count == 0 ? path : path + "?" + string.Join("&", query);
            var headers = BuildHeaders(options);
            return await SendAsync<Item>(HttpMethod.Post, requestUri, req, headers, cancellationToken);
        }

        private Dictionary<string, string> BuildHeaders(ContractServiceCallOptions? options)
        {
            var headers = new Dictionary<string, string>(_defaultHeaders);
            if (options?.Headers is not null)
            {
                foreach (var pair in options.Headers)
                {
                    headers[pair.Key] = pair.Value;
                }
            }
            return headers;
        }

        private async Task<TResponse> SendAsync<TResponse>(HttpMethod method, string requestUri, object? body, Dictionary<string, string> headers, CancellationToken cancellationToken) where TResponse : new()
        {
            using var request = new HttpRequestMessage(method, _baseUrl + requestUri);
            foreach (var header in headers)
            {
                request.Headers.TryAddWithoutValidation(header.Key, header.Value);
            }
            if (body is not null)
            {
                request.Content = new StringContent(SerializeRequest(body), Encoding.UTF8, "application/json");
            }
            using var response = await _httpClient.SendAsync(request, cancellationToken);
            var responseBody = response.Content is null ? string.Empty : await response.Content.ReadAsStringAsync(cancellationToken);
            if (!response.IsSuccessStatusCode)
            {
                throw new ApiException((int)response.StatusCode, responseBody);
            }
            if (typeof(TResponse) == typeof(Empty) && string.IsNullOrWhiteSpace(responseBody))
            {
                return new TResponse();
            }
            if (string.IsNullOrWhiteSpace(responseBody))
            {
                return new TResponse();
            }
            var result = DeserializeResponse<TResponse>(responseBody);
            return result is null ? new TResponse() : result;
        }

        private string SerializeRequest(object value)
        {
            var json = JsonConvert.SerializeObject(value);
            return NormalizeSerializedJson(value, json);
        }

        private static TResponse? DeserializeResponse<TResponse>(string json)
        {
            json = NormalizeResponseJson(typeof(TResponse), json);
            return JsonConvert.DeserializeObject<TResponse>(json);
        }

        private static string NormalizeSerializedJson(object value, string json)
        {
            return json;
        }

        private static string NormalizeResponseJson(Type responseType, string json)
        {
            return json;
        }

        private static string EncodeBytes(byte[] bytes, string encoding)
        {
            var base64 = Convert.ToBase64String(bytes);
            return encoding switch
            {
                "base64_raw" => base64.TrimEnd('='),
                "base64url" => base64.Replace('+', '-').Replace('/', '_'),
                "base64url_raw" => base64.Replace('+', '-').Replace('/', '_').TrimEnd('='),
                "hex" => Convert.ToHexString(bytes).ToLowerInvariant(),
                _ => base64
            };
        }

        private static string ReencodeBytes(string encoded, string fromEncoding, string toEncoding)
        {
            return EncodeBytes(DecodeBytes(encoded, fromEncoding), toEncoding);
        }

        private static byte[] DecodeBytes(string encoded, string encoding)
        {
            return encoding switch
            {
                "hex" => Convert.FromHexString(encoded),
                "base64url" => Convert.FromBase64String(NormalizeBase64(encoded.Replace('-', '+').Replace('_', '/'))),
                "base64url_raw" => Convert.FromBase64String(NormalizeBase64(encoded.Replace('-', '+').Replace('_', '/'))),
                "base64_raw" => Convert.FromBase64String(NormalizeBase64(encoded)),
                _ => Convert.FromBase64String(NormalizeBase64(encoded))
            };
        }

        private static string NormalizeBase64(string value)
        {
            var remainder = value.Length % 4;
            if (remainder == 0)
            {
                return value;
            }
            return value + new string('=', 4 - remainder);
        }

        private static string FormatPathValue(object? value)
        {
            return value?.ToString() ?? string.Empty;
        }

        private static string FormatQueryValue(object? value)
        {
            return value?.ToString() ?? string.Empty;
        }

    }

    public static class ServiceContracts
    {
        public static class ContractService
        {
            public const string Name = "ContractService";
            public const string BasePath = "";
            public static class FetchItem
            {
                public const string HttpMethod = "POST";
                public const string Path = "/";
                public const string RequestType = "FetchItemRequest";
                public const string ResponseType = "Item";
            }
        }
    }
}
