// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        v6.32.0
// source: proto/sebuf/http/annotations.proto

package http

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HttpConfig defines HTTP-specific configuration for an RPC method
type HttpConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The HTTP path for this method
	Path          string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HttpConfig) Reset() {
	*x = HttpConfig{}
	mi := &file_proto_sebuf_http_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpConfig) ProtoMessage() {}

func (x *HttpConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sebuf_http_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpConfig.ProtoReflect.Descriptor instead.
func (*HttpConfig) Descriptor() ([]byte, []int) {
	return file_proto_sebuf_http_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *HttpConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// ServiceConfig defines HTTP-specific configuration for an entire service
type ServiceConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Base path prefix for all methods in this service
	BasePath      string `protobuf:"bytes,1,opt,name=base_path,json=basePath,proto3" json:"base_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServiceConfig) Reset() {
	*x = ServiceConfig{}
	mi := &file_proto_sebuf_http_annotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfig) ProtoMessage() {}

func (x *ServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sebuf_http_annotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfig.ProtoReflect.Descriptor instead.
func (*ServiceConfig) Descriptor() ([]byte, []int) {
	return file_proto_sebuf_http_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceConfig) GetBasePath() string {
	if x != nil {
		return x.BasePath
	}
	return ""
}

// FieldExamples defines example values for a field
type FieldExamples struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// List of example values for this field
	Values        []string `protobuf:"bytes,1,rep,name=values,proto3" json:"values,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldExamples) Reset() {
	*x = FieldExamples{}
	mi := &file_proto_sebuf_http_annotations_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldExamples) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldExamples) ProtoMessage() {}

func (x *FieldExamples) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sebuf_http_annotations_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldExamples.ProtoReflect.Descriptor instead.
func (*FieldExamples) Descriptor() ([]byte, []int) {
	return file_proto_sebuf_http_annotations_proto_rawDescGZIP(), []int{2}
}

func (x *FieldExamples) GetValues() []string {
	if x != nil {
		return x.Values
	}
	return nil
}

// ErrorConfig defines error handling configuration for methods
type ErrorConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Whether to use custom error types (looks for ${RpcName}Error message)
	CustomError bool `protobuf:"varint,1,opt,name=custom_error,json=customError,proto3" json:"custom_error,omitempty"`
	// Default HTTP status code for errors (if not using custom errors)
	DefaultStatusCode int32 `protobuf:"varint,2,opt,name=default_status_code,json=defaultStatusCode,proto3" json:"default_status_code,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *ErrorConfig) Reset() {
	*x = ErrorConfig{}
	mi := &file_proto_sebuf_http_annotations_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ErrorConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ErrorConfig) ProtoMessage() {}

func (x *ErrorConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sebuf_http_annotations_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ErrorConfig.ProtoReflect.Descriptor instead.
func (*ErrorConfig) Descriptor() ([]byte, []int) {
	return file_proto_sebuf_http_annotations_proto_rawDescGZIP(), []int{3}
}

func (x *ErrorConfig) GetCustomError() bool {
	if x != nil {
		return x.CustomError
	}
	return false
}

func (x *ErrorConfig) GetDefaultStatusCode() int32 {
	if x != nil {
		return x.DefaultStatusCode
	}
	return 0
}

var file_proto_sebuf_http_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*HttpConfig)(nil),
		Field:         50003,
		Name:          "sebuf.http.config",
		Tag:           "bytes,50003,opt,name=config",
		Filename:      "proto/sebuf/http/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceConfig)(nil),
		Field:         50004,
		Name:          "sebuf.http.service_config",
		Tag:           "bytes,50004,opt,name=service_config",
		Filename:      "proto/sebuf/http/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.FieldOptions)(nil),
		ExtensionType: (*FieldExamples)(nil),
		Field:         50007,
		Name:          "sebuf.http.field_examples",
		Tag:           "bytes,50007,opt,name=field_examples",
		Filename:      "proto/sebuf/http/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*ErrorConfig)(nil),
		Field:         50008,
		Name:          "sebuf.http.error_config",
		Tag:           "bytes,50008,opt,name=error_config",
		Filename:      "proto/sebuf/http/annotations.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional sebuf.http.HttpConfig config = 50003;
	E_Config = &file_proto_sebuf_http_annotations_proto_extTypes[0]
	// optional sebuf.http.ErrorConfig error_config = 50008;
	E_ErrorConfig = &file_proto_sebuf_http_annotations_proto_extTypes[3]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional sebuf.http.ServiceConfig service_config = 50004;
	E_ServiceConfig = &file_proto_sebuf_http_annotations_proto_extTypes[1]
)

// Extension fields to descriptorpb.FieldOptions.
var (
	// optional sebuf.http.FieldExamples field_examples = 50007;
	E_FieldExamples = &file_proto_sebuf_http_annotations_proto_extTypes[2]
)

var File_proto_sebuf_http_annotations_proto protoreflect.FileDescriptor

const file_proto_sebuf_http_annotations_proto_rawDesc = "" +
	"\n" +
	"\"proto/sebuf/http/annotations.proto\x12\n" +
	"sebuf.http\x1a google/protobuf/descriptor.proto\" \n" +
	"\n" +
	"HttpConfig\x12\x12\n" +
	"\x04path\x18\x01 \x01(\tR\x04path\",\n" +
	"\rServiceConfig\x12\x1b\n" +
	"\tbase_path\x18\x01 \x01(\tR\bbasePath\"'\n" +
	"\rFieldExamples\x12\x16\n" +
	"\x06values\x18\x01 \x03(\tR\x06values\"`\n" +
	"\vErrorConfig\x12!\n" +
	"\fcustom_error\x18\x01 \x01(\bR\vcustomError\x12.\n" +
	"\x13default_status_code\x18\x02 \x01(\x05R\x11defaultStatusCode:P\n" +
	"\x06config\x12\x1e.google.protobuf.MethodOptions\x18ӆ\x03 \x01(\v2\x16.sebuf.http.HttpConfigR\x06config:c\n" +
	"\x0eservice_config\x12\x1f.google.protobuf.ServiceOptions\x18Ԇ\x03 \x01(\v2\x19.sebuf.http.ServiceConfigR\rserviceConfig:a\n" +
	"\x0efield_examples\x12\x1d.google.protobuf.FieldOptions\x18׆\x03 \x01(\v2\x19.sebuf.http.FieldExamplesR\rfieldExamples:\\\n" +
	"\ferror_config\x12\x1e.google.protobuf.MethodOptions\x18؆\x03 \x01(\v2\x17.sebuf.http.ErrorConfigR\verrorConfigB+Z)github.com/SebastienMelki/sebuf/http;httpb\x06proto3"

var (
	file_proto_sebuf_http_annotations_proto_rawDescOnce sync.Once
	file_proto_sebuf_http_annotations_proto_rawDescData []byte
)

func file_proto_sebuf_http_annotations_proto_rawDescGZIP() []byte {
	file_proto_sebuf_http_annotations_proto_rawDescOnce.Do(func() {
		file_proto_sebuf_http_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sebuf_http_annotations_proto_rawDesc), len(file_proto_sebuf_http_annotations_proto_rawDesc)))
	})
	return file_proto_sebuf_http_annotations_proto_rawDescData
}

var file_proto_sebuf_http_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_sebuf_http_annotations_proto_goTypes = []any{
	(*HttpConfig)(nil),                  // 0: sebuf.http.HttpConfig
	(*ServiceConfig)(nil),               // 1: sebuf.http.ServiceConfig
	(*FieldExamples)(nil),               // 2: sebuf.http.FieldExamples
	(*ErrorConfig)(nil),                 // 3: sebuf.http.ErrorConfig
	(*descriptorpb.MethodOptions)(nil),  // 4: google.protobuf.MethodOptions
	(*descriptorpb.ServiceOptions)(nil), // 5: google.protobuf.ServiceOptions
	(*descriptorpb.FieldOptions)(nil),   // 6: google.protobuf.FieldOptions
}
var file_proto_sebuf_http_annotations_proto_depIdxs = []int32{
	4, // 0: sebuf.http.config:extendee -> google.protobuf.MethodOptions
	5, // 1: sebuf.http.service_config:extendee -> google.protobuf.ServiceOptions
	6, // 2: sebuf.http.field_examples:extendee -> google.protobuf.FieldOptions
	4, // 3: sebuf.http.error_config:extendee -> google.protobuf.MethodOptions
	0, // 4: sebuf.http.config:type_name -> sebuf.http.HttpConfig
	1, // 5: sebuf.http.service_config:type_name -> sebuf.http.ServiceConfig
	2, // 6: sebuf.http.field_examples:type_name -> sebuf.http.FieldExamples
	3, // 7: sebuf.http.error_config:type_name -> sebuf.http.ErrorConfig
	8, // [8:8] is the sub-list for method output_type
	8, // [8:8] is the sub-list for method input_type
	4, // [4:8] is the sub-list for extension type_name
	0, // [0:4] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sebuf_http_annotations_proto_init() }
func file_proto_sebuf_http_annotations_proto_init() {
	if File_proto_sebuf_http_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sebuf_http_annotations_proto_rawDesc), len(file_proto_sebuf_http_annotations_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 4,
			NumServices:   0,
		},
		GoTypes:           file_proto_sebuf_http_annotations_proto_goTypes,
		DependencyIndexes: file_proto_sebuf_http_annotations_proto_depIdxs,
		MessageInfos:      file_proto_sebuf_http_annotations_proto_msgTypes,
		ExtensionInfos:    file_proto_sebuf_http_annotations_proto_extTypes,
	}.Build()
	File_proto_sebuf_http_annotations_proto = out.File
	file_proto_sebuf_http_annotations_proto_goTypes = nil
	file_proto_sebuf_http_annotations_proto_depIdxs = nil
}
