// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: proto/services/suggestion_service.proto

package suggestionv1

import (
	"encoding/json"

	"google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSONSebuf implements sebufMarshaler for OptionsContract.
// This method handles enum_value fields and nested messages: type
func (x *OptionsContract) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Rewrite type to custom enum_value strings
	for _, k := range []string{"type"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := optionTypeFromJSON[s]; ok {
			raw[k], _ = json.Marshal(optionTypeToJSON[e])
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for OptionsContract.
func (x *OptionsContract) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for OptionsContract.
// This method handles enum_value fields and nested messages: type
func (x *OptionsContract) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Rewrite type from custom enum_value strings to proto names
	for _, k := range []string{"type"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := optionTypeFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for OptionsContract.
func (x *OptionsContract) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for EasyOptionSuggestion.
// This method handles enum_value fields and nested messages: risk_level, options_contract
func (x *EasyOptionSuggestion) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Rewrite risk_level to custom enum_value strings
	for _, k := range []string{"riskLevel", "risk_level"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := riskLevelFromJSON[s]; ok {
			raw[k], _ = json.Marshal(riskLevelToJSON[e])
		}
	}

	// Re-serialize "optionsContract" forwarding opts when child supports MarshalJSONSebuf
	if x.OptionsContract != nil {
		if m, ok := any(x.OptionsContract).(interface {
			MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
		}); ok {
			childData, childErr := m.MarshalJSONSebuf(opts)
			if childErr != nil {
				return nil, childErr
			}
			for _, k := range []string{"optionsContract", "options_contract"} {
				if _, ok := raw[k]; ok {
					raw[k] = childData
				}
			}
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for EasyOptionSuggestion.
func (x *EasyOptionSuggestion) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for EasyOptionSuggestion.
// This method handles enum_value fields and nested messages: risk_level, options_contract
func (x *EasyOptionSuggestion) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Rewrite risk_level from custom enum_value strings to proto names
	for _, k := range []string{"riskLevel", "risk_level"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := riskLevelFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Handle "optionsContract" using its custom unmarshaler
	for _, k := range []string{"optionsContract", "options_contract"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		inner := &OptionsContract{}
		if u, ok := any(inner).(interface {
			UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
		}); ok {
			if err := u.UnmarshalJSONSebuf(rawVal, opts); err != nil {
				return err
			}
		} else if err := json.Unmarshal(rawVal, inner); err != nil {
			return err
		}
		innerJSON, marshalErr := protojson.Marshal(inner)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = innerJSON
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for EasyOptionSuggestion.
func (x *EasyOptionSuggestion) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for GetEasyOptionsResponse.
// This method handles enum_value fields and nested messages: overall_risk, option_suggestions
func (x *GetEasyOptionsResponse) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Rewrite overall_risk to custom enum_value strings
	for _, k := range []string{"overallRisk", "overall_risk"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := riskLevelFromJSON[s]; ok {
			raw[k], _ = json.Marshal(riskLevelToJSON[e])
		}
	}

	// Re-serialize repeated "optionSuggestions" forwarding opts to each element
	if len(x.OptionSuggestions) > 0 {
		items := make([]json.RawMessage, 0, len(x.OptionSuggestions))
		for _, item := range x.OptionSuggestions {
			if m, ok := any(item).(interface {
				MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
			}); ok {
				itemData, itemErr := m.MarshalJSONSebuf(opts)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			} else {
				itemData, itemErr := opts.Marshal(item)
				if itemErr != nil {
					return nil, itemErr
				}
				items = append(items, itemData)
			}
		}
		listData, listErr := json.Marshal(items)
		if listErr != nil {
			return nil, listErr
		}
		for _, k := range []string{"optionSuggestions", "option_suggestions"} {
			if _, ok := raw[k]; ok {
				raw[k] = listData
			}
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for GetEasyOptionsResponse.
func (x *GetEasyOptionsResponse) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for GetEasyOptionsResponse.
// This method handles enum_value fields and nested messages: overall_risk, option_suggestions
func (x *GetEasyOptionsResponse) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Rewrite overall_risk from custom enum_value strings to proto names
	for _, k := range []string{"overallRisk", "overall_risk"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := riskLevelFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Handle "optionSuggestions" using its custom unmarshaler
	for _, k := range []string{"optionSuggestions", "option_suggestions"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		var rawItems []json.RawMessage
		if err := json.Unmarshal(rawVal, &rawItems); err != nil {
			return err
		}
		protoItems := make([]json.RawMessage, len(rawItems))
		for i, itemRaw := range rawItems {
			inner := &EasyOptionSuggestion{}
			if u, ok := any(inner).(interface {
				UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
			}); ok {
				if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
					return err
				}
			} else if err := json.Unmarshal(itemRaw, inner); err != nil {
				return err
			}
			itemJSON, marshalErr := protojson.Marshal(inner)
			if marshalErr != nil {
				return marshalErr
			}
			protoItems[i] = itemJSON
		}
		protoJSON, marshalErr := json.Marshal(protoItems)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = protoJSON
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for GetEasyOptionsResponse.
func (x *GetEasyOptionsResponse) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for GetEasyOptionsRequest.
// This method handles enum_value fields and nested messages: requested_risk
func (x *GetEasyOptionsRequest) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Rewrite requested_risk to custom enum_value strings
	for _, k := range []string{"requestedRisk", "requested_risk"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := riskLevelFromJSON[s]; ok {
			raw[k], _ = json.Marshal(riskLevelToJSON[e])
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for GetEasyOptionsRequest.
func (x *GetEasyOptionsRequest) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for GetEasyOptionsRequest.
// This method handles enum_value fields and nested messages: requested_risk
func (x *GetEasyOptionsRequest) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings and nested messages
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Rewrite requested_risk from custom enum_value strings to proto names
	for _, k := range []string{"requestedRisk", "requested_risk"} {
		v, ok := raw[k]
		if !ok {
			continue
		}
		var s string
		if err := json.Unmarshal(v, &s); err != nil {
			continue
		}
		if e, ok := riskLevelFromJSON[s]; ok {
			raw[k], _ = json.Marshal(e.String())
		}
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for GetEasyOptionsRequest.
func (x *GetEasyOptionsRequest) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}
