// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: proto/services/suggestion_service.proto

package suggestionv1

import (
	"encoding/json"
	"fmt"
)

var riskLevelToJSON = map[RiskLevel]string{
	RiskLevel_RISK_LEVEL_UNSPECIFIED: "RISK_LEVEL_UNSPECIFIED",
	RiskLevel_RISK_LEVEL_LOW:         "low",
	RiskLevel_RISK_LEVEL_MEDIUM:      "medium",
	RiskLevel_RISK_LEVEL_HIGH:        "high",
}

var riskLevelFromJSON = map[string]RiskLevel{
	"RISK_LEVEL_UNSPECIFIED": RiskLevel_RISK_LEVEL_UNSPECIFIED,
	"low":                    RiskLevel_RISK_LEVEL_LOW,
	"medium":                 RiskLevel_RISK_LEVEL_MEDIUM,
	"high":                   RiskLevel_RISK_LEVEL_HIGH,
	"RISK_LEVEL_LOW":         RiskLevel_RISK_LEVEL_LOW,
	"RISK_LEVEL_MEDIUM":      RiskLevel_RISK_LEVEL_MEDIUM,
	"RISK_LEVEL_HIGH":        RiskLevel_RISK_LEVEL_HIGH,
}

func (x RiskLevel) MarshalJSON() ([]byte, error) {
	if s, ok := riskLevelToJSON[x]; ok {
		return json.Marshal(s)
	}
	return json.Marshal(x.String())
}

func (x *RiskLevel) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		if v, ok := riskLevelFromJSON[s]; ok {
			*x = v
			return nil
		}
		return fmt.Errorf("unknown RiskLevel value: %q", s)
	}

	var n int32
	if err := json.Unmarshal(data, &n); err == nil {
		*x = RiskLevel(n)
		return nil
	}

	return fmt.Errorf("cannot unmarshal %s into RiskLevel", string(data))
}

var optionTypeToJSON = map[OptionType]string{
	OptionType_OPTION_TYPE_UNSPECIFIED: "OPTION_TYPE_UNSPECIFIED",
	OptionType_OPTION_TYPE_CALL:        "call",
	OptionType_OPTION_TYPE_PUT:         "put",
}

var optionTypeFromJSON = map[string]OptionType{
	"OPTION_TYPE_UNSPECIFIED": OptionType_OPTION_TYPE_UNSPECIFIED,
	"call":                    OptionType_OPTION_TYPE_CALL,
	"put":                     OptionType_OPTION_TYPE_PUT,
	"OPTION_TYPE_CALL":        OptionType_OPTION_TYPE_CALL,
	"OPTION_TYPE_PUT":         OptionType_OPTION_TYPE_PUT,
}

func (x OptionType) MarshalJSON() ([]byte, error) {
	if s, ok := optionTypeToJSON[x]; ok {
		return json.Marshal(s)
	}
	return json.Marshal(x.String())
}

func (x *OptionType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		if v, ok := optionTypeFromJSON[s]; ok {
			*x = v
			return nil
		}
		return fmt.Errorf("unknown OptionType value: %q", s)
	}

	var n int32
	if err := json.Unmarshal(data, &n); err == nil {
		*x = OptionType(n)
		return nil
	}

	return fmt.Errorf("cannot unmarshal %s into OptionType", string(data))
}
