package csharpgen

import (
	"flag"
	"fmt"
	"net/http"
	"path"
	"slices"
	"strings"

	"google.golang.org/protobuf/compiler/protogen"

	sebufhttp "github.com/SebastienMelki/sebuf/http"
	"github.com/SebastienMelki/sebuf/internal/contractmodel"
	"github.com/SebastienMelki/sebuf/internal/tscommon"
)

const (
	csharpObjectType = "object"
	csharpStringType = "string"
	csharpDoubleType = "double"
	csharpBoolType   = "bool"
	csharpLongType   = "long"
	emptyTypeName    = "Empty"
)

type Options struct {
	Namespace string
	JSONLib   string
}

type Generator struct {
	plugin *protogen.Plugin
	opts   Options
}

func New(plugin *protogen.Plugin, opts Options) *Generator {
	return &Generator{plugin: plugin, opts: opts}
}

func NewOptions() (protogen.Options, *Options) {
	var flags flag.FlagSet
	cfg := &Options{}
	flags.StringVar(&cfg.Namespace, "namespace", "Sebuf.Generated", "C# namespace")
	flags.StringVar(&cfg.JSONLib, "json_lib", "newtonsoft", "JSON annotation library: newtonsoft or system_text_json")
	return protogen.Options{ParamFunc: flags.Set}, cfg
}

func (g *Generator) Generate() error {
	for _, pkg := range contractmodel.Packages(g.plugin.Files) {
		if err := g.generatePackage(pkg); err != nil {
			return err
		}
	}
	return nil
}

func (g *Generator) generatePackage(pkg *contractmodel.Package) error {
	messages := g.packageMessages(pkg)
	messageIndex := make(map[string]*contractmodel.Message, len(messages))
	for _, message := range messages {
		messageIndex[message.Name] = message
	}

	packagePath := strings.ReplaceAll(pkg.Name, ".", "/")
	gf := g.plugin.NewGeneratedFile(path.Join(packagePath, "Contracts.g.cs"), "")
	gf.P("// Code generated by protoc-gen-csharp-http. DO NOT EDIT.")
	gf.P("#nullable enable")
	gf.P("using System;")
	gf.P("using System.Collections.Generic;")
	gf.P("using System.Linq;")
	gf.P("using System.Net.Http;")
	gf.P("using System.Runtime.Serialization;")
	gf.P("using System.Text;")
	gf.P("using System.Threading;")
	gf.P("using System.Threading.Tasks;")
	if g.useNewtonsoft() {
		gf.P("using Newtonsoft.Json;")
		gf.P("using Newtonsoft.Json.Converters;")
	} else {
		gf.P("using System.Text.Json;")
		gf.P("using System.Text.Json.Serialization;")
	}
	gf.P()
	gf.P("namespace ", g.opts.Namespace)
	gf.P("{")
	g.generateEnums(gf, pkg.Enums)
	g.generateAPIException(gf)
	g.generateMessages(gf, messages, messageIndex)
	g.generateServiceClients(gf, pkg.Services, messageIndex)
	g.generateServices(gf, pkg.Services)
	gf.P("}")
	return nil
}

type generatedProperty struct {
	jsonName  string
	name      string
	typ       string
	converter string
}

func (g *Generator) messageProperties(
	message *contractmodel.Message,
	messageIndex map[string]*contractmodel.Message,
) []generatedProperty {
	var properties []generatedProperty
	usedJSONNames := make(map[string]bool)
	skippedFields := make(map[string]bool)

	g.markOneofFields(message, skippedFields)
	g.appendStandardMessageProperties(&properties, usedJSONNames, skippedFields, message, messageIndex)
	g.appendOneofProperties(&properties, usedJSONNames, message, messageIndex)

	return properties
}

func (g *Generator) generateEnums(gf *protogen.GeneratedFile, enums []*contractmodel.Enum) {
	for _, enum := range enums {
		gf.P("    public enum ", enum.Name)
		gf.P("    {")
		for _, value := range enum.Values {
			gf.P(`        [EnumMember(Value = "`, value.JSONValue, `")]`)
			gf.P("        ", pascalCase(value.Name), " = ", value.Number, ",")
		}
		gf.P("    }")
		gf.P()
	}
}

func (g *Generator) generateMessages(
	gf *protogen.GeneratedFile,
	messages []*contractmodel.Message,
	messageIndex map[string]*contractmodel.Message,
) {
	for _, message := range messages {
		if isRootUnwrapMessage(message) {
			gf.P("    public sealed class ", message.Name, " : ", rootUnwrapBaseType(message))
			gf.P("    {")
			gf.P("    }")
			gf.P()
			continue
		}

		gf.P("    public sealed class ", message.Name)
		gf.P("    {")
		for _, property := range g.messageProperties(message, messageIndex) {
			gf.P("        ", g.jsonAttribute(property.jsonName))
			if property.converter != "" {
				gf.P("        ", property.converter)
			}
			gf.P("        public ", property.typ, " ", property.name, " { get; set; }")
		}
		gf.P("    }")
		gf.P()
	}
}

func (g *Generator) packageMessages(pkg *contractmodel.Package) []*contractmodel.Message {
	messages := slices.Clone(pkg.Messages)
	if g.needsSyntheticEmpty(pkg) {
		messages = append(messages, &contractmodel.Message{Name: emptyTypeName})
	}
	return messages
}

func (g *Generator) needsSyntheticEmpty(pkg *contractmodel.Package) bool {
	if hasMessageNamed(pkg.Messages, emptyTypeName) {
		return false
	}
	for _, service := range pkg.Services {
		for _, method := range service.Methods {
			if method.InputType == emptyTypeName || method.ResponseType == emptyTypeName {
				return true
			}
		}
	}
	return false
}

func hasMessageNamed(messages []*contractmodel.Message, name string) bool {
	for _, message := range messages {
		if message.Name == name {
			return true
		}
	}
	return false
}

func (g *Generator) generateAPIException(gf *protogen.GeneratedFile) {
	gf.P("    public sealed class ApiException : Exception")
	gf.P("    {")
	gf.P("        public int StatusCode { get; }")
	gf.P("        public string ResponseBody { get; }")
	gf.P()
	gf.P("        public ApiException(int statusCode, string responseBody)")
	gf.P(`            : base($\"Request failed with status {statusCode}: {responseBody}\")`)
	gf.P("        {")
	gf.P("            StatusCode = statusCode;")
	gf.P("            ResponseBody = responseBody;")
	gf.P("        }")
	gf.P("    }")
	gf.P()
}

func (g *Generator) generateServices(gf *protogen.GeneratedFile, services []*contractmodel.Service) {
	gf.P("    public static class ServiceContracts")
	gf.P("    {")
	for _, service := range services {
		gf.P("        public static class ", service.Name)
		gf.P("        {")
		gf.P(`            public const string Name = "`, service.Name, `";`)
		gf.P(`            public const string BasePath = "`, service.BasePath, `";`)
		for _, method := range service.Methods {
			gf.P("            public static class ", method.Name)
			gf.P("            {")
			gf.P(`                public const string HttpMethod = "`, method.HTTPMethod, `";`)
			gf.P(`                public const string Path = "`, method.Path, `";`)
			gf.P(`                public const string RequestType = "`, method.InputType, `";`)
			gf.P(`                public const string ResponseType = "`, method.ResponseType, `";`)
			gf.P("            }")
		}
		gf.P("        }")
	}
	gf.P("    }")
}

func (g *Generator) generateServiceClients(
	gf *protogen.GeneratedFile,
	services []*contractmodel.Service,
	messageIndex map[string]*contractmodel.Message,
) {
	for _, service := range services {
		g.generateServiceClientOptions(gf, service)
		g.generateServiceCallOptions(gf, service)
		g.generateServiceClientInterface(gf, service)
		g.generateServiceClientClass(gf, service, messageIndex)
	}
}

func (g *Generator) generateServiceClientOptions(gf *protogen.GeneratedFile, service *contractmodel.Service) {
	gf.P("    public sealed class ", service.Name, "ClientOptions")
	gf.P("    {")
	gf.P("        public HttpClient? HttpClient { get; set; }")
	gf.P("        public Dictionary<string, string>? DefaultHeaders { get; set; }")
	for _, header := range service.Headers {
		gf.P("        public string? ", upperFirst(tscommon.HeaderNameToPropertyName(header.Name)), " { get; set; }")
	}
	gf.P("    }")
	gf.P()
}

func (g *Generator) generateServiceCallOptions(gf *protogen.GeneratedFile, service *contractmodel.Service) {
	gf.P("    public sealed class ", service.Name, "CallOptions")
	gf.P("    {")
	gf.P("        public Dictionary<string, string>? Headers { get; set; }")
	for _, header := range serviceCallHeaders(service) {
		gf.P("        public string? ", upperFirst(tscommon.HeaderNameToPropertyName(header.Name)), " { get; set; }")
	}
	gf.P("    }")
	gf.P()
}

func (g *Generator) generateServiceClientInterface(gf *protogen.GeneratedFile, service *contractmodel.Service) {
	gf.P("    public interface I", service.Name, "Client")
	gf.P("    {")
	for _, method := range service.Methods {
		responseType := clientResponseType(method)
		gf.P(
			"        Task<", responseType, "> ", method.Name,
			"Async(", method.InputType, " req, ", service.Name,
			"CallOptions? options = null, CancellationToken cancellationToken = default);",
		)
	}
	gf.P("    }")
	gf.P()
}

func (g *Generator) generateServiceClientClass(
	gf *protogen.GeneratedFile,
	service *contractmodel.Service,
	messageIndex map[string]*contractmodel.Message,
) {
	gf.P("    public sealed class ", service.Name, "Client : I", service.Name, "Client")
	gf.P("    {")
	gf.P("        private readonly string _baseUrl;")
	gf.P("        private readonly HttpClient _httpClient;")
	gf.P("        private readonly Dictionary<string, string> _defaultHeaders;")
	if !g.useNewtonsoft() {
		gf.P("        private static readonly JsonSerializerOptions JsonOptions = new()")
		gf.P("        {")
		gf.P("            PropertyNamingPolicy = null,")
		gf.P("            DefaultIgnoreCondition = JsonIgnoreCondition.WhenWritingNull")
		gf.P("        };")
	}
	gf.P()
	g.generateServiceClientConstructor(gf, service)
	for _, method := range service.Methods {
		g.generateServiceClientMethod(gf, service, method, messageIndex)
	}
	g.generateServiceClientHelpers(gf, service)
	gf.P("    }")
	gf.P()
}

func (g *Generator) generateServiceClientConstructor(gf *protogen.GeneratedFile, service *contractmodel.Service) {
	gf.P(
		"        public ", service.Name, "Client(string baseUrl, ", service.Name, "ClientOptions? options = null)",
	)
	gf.P("        {")
	gf.P(`            _baseUrl = baseUrl.TrimEnd('/');`)
	gf.P("            _httpClient = options?.HttpClient ?? new HttpClient();")
	gf.P("            _defaultHeaders = options?.DefaultHeaders is null")
	gf.P("                ? new Dictionary<string, string>()")
	gf.P("                : new Dictionary<string, string>(options.DefaultHeaders);")
	for _, header := range service.Headers {
		prop := upperFirst(tscommon.HeaderNameToPropertyName(header.Name))
		gf.P("            if (!string.IsNullOrEmpty(options?.", prop, "))")
		gf.P("            {")
		gf.P(`                _defaultHeaders["`, header.Name, `"] = options.`, prop, "!;")
		gf.P("            }")
	}
	gf.P("        }")
	gf.P()
}

func (g *Generator) generateServiceClientMethod(
	gf *protogen.GeneratedFile,
	service *contractmodel.Service,
	method *contractmodel.Method,
	messageIndex map[string]*contractmodel.Message,
) {
	requestMessage := messageIndex[method.InputType]
	responseType := clientResponseType(method)
	gf.P(
		"        public async Task<", responseType, "> ", method.Name, "Async(",
		method.InputType, " req, ", service.Name,
		"CallOptions? options = null, CancellationToken cancellationToken = default)",
	)
	gf.P("        {")
	gf.P(`            var path = "`, method.Path, `";`)
	for _, pathParam := range method.PathParams {
		gf.P(
			`            path = path.Replace("{`, pathParam, `}", Uri.EscapeDataString(FormatPathValue(req.`,
			pascalCase(pathParam), ")));",
		)
	}
	if requestMessage != nil {
		g.generateQueryString(gf, requestMessage, method)
	} else {
		gf.P("            var query = new List<string>();")
	}
	gf.P(`            var requestUri = query.Count == 0 ? path : path + "?" + string.Join("&", query);`)
	gf.P("            var headers = BuildHeaders(options);")
	for _, header := range method.Headers {
		prop := upperFirst(tscommon.HeaderNameToPropertyName(header.Name))
		gf.P("            if (!string.IsNullOrEmpty(options?.", prop, "))")
		gf.P("            {")
		gf.P(`                headers["`, header.Name, `"] = options.`, prop, "!;")
		gf.P("            }")
	}
	bodyExpr := "null"
	if methodHasBody(method) {
		bodyExpr = "req"
	}
	gf.P(
		"            return await SendAsync<", responseType, ">(HttpMethod.",
		httpMethodName(method.HTTPMethod), ", requestUri, ", bodyExpr, ", headers, cancellationToken);",
	)
	gf.P("        }")
	gf.P()
}

func (g *Generator) generateQueryString(
	gf *protogen.GeneratedFile,
	requestMessage *contractmodel.Message,
	method *contractmodel.Method,
) {
	gf.P("            var query = new List<string>();")
	if requestMessage == nil || (method.HTTPMethod != http.MethodGet && method.HTTPMethod != http.MethodDelete) {
		return
	}

	for _, field := range requestMessage.Fields {
		if field.Annotations.Query == nil {
			continue
		}
		prop := pascalCase(field.Name)
		paramName := field.Annotations.Query.Name
		if field.Repeated {
			gf.P("            if (req.", prop, " is not null)")
			gf.P("            {")
			gf.P("                foreach (var item in req.", prop, ")")
			gf.P("                {")
			gf.P(
				`                    query.Add(Uri.EscapeDataString("`,
				paramName,
				`") + "=" + Uri.EscapeDataString(FormatQueryValue(item)));`,
			)
			gf.P("                }")
			gf.P("            }")
			continue
		}
		gf.P("            if (", csharpQueryCondition(field, "req."+prop), ")")
		gf.P("            {")
		gf.P(
			`                query.Add(Uri.EscapeDataString("`,
			paramName,
			`") + "=" + Uri.EscapeDataString(FormatQueryValue(req.`,
			prop,
			")));",
		)
		gf.P("            }")
	}
}

func (g *Generator) generateServiceClientHelpers(gf *protogen.GeneratedFile, service *contractmodel.Service) {
	gf.P("        private Dictionary<string, string> BuildHeaders(", service.Name, "CallOptions? options)")
	gf.P("        {")
	gf.P("            var headers = new Dictionary<string, string>(_defaultHeaders);")
	gf.P("            if (options?.Headers is not null)")
	gf.P("            {")
	gf.P("                foreach (var pair in options.Headers)")
	gf.P("                {")
	gf.P("                    headers[pair.Key] = pair.Value;")
	gf.P("                }")
	gf.P("            }")
	for _, header := range service.Headers {
		prop := upperFirst(tscommon.HeaderNameToPropertyName(header.Name))
		gf.P("            if (!string.IsNullOrEmpty(options?.", prop, "))")
		gf.P("            {")
		gf.P(`                headers["`, header.Name, `"] = options.`, prop, "!;")
		gf.P("            }")
	}
	gf.P("            return headers;")
	gf.P("        }")
	gf.P()
	g.generateSendAsync(gf)
	g.generateSerializeRequest(gf)
	g.generateDeserializeResponse(gf)
	g.generatePathAndQueryHelpers(gf)
}

func (g *Generator) generateSendAsync(gf *protogen.GeneratedFile) {
	gf.P(
		"        private async Task<TResponse> SendAsync<TResponse>(",
		"HttpMethod method, string requestUri, object? body, Dictionary<string, string> headers, CancellationToken cancellationToken) where TResponse : new()",
	)
	gf.P("        {")
	gf.P("            using var request = new HttpRequestMessage(method, _baseUrl + requestUri);")
	gf.P("            foreach (var header in headers)")
	gf.P("            {")
	gf.P("                request.Headers.TryAddWithoutValidation(header.Key, header.Value);")
	gf.P("            }")
	gf.P("            if (body is not null)")
	gf.P("            {")
	gf.P(
		`                request.Content = new StringContent(SerializeRequest(body), Encoding.UTF8, "application/json");`,
	)
	gf.P("            }")
	gf.P("            using var response = await _httpClient.SendAsync(request, cancellationToken);")
	gf.P(
		`            var responseBody = response.Content is null ? string.Empty : await response.Content.ReadAsStringAsync(cancellationToken);`,
	)
	gf.P("            if (!response.IsSuccessStatusCode)")
	gf.P("            {")
	gf.P("                throw new ApiException((int)response.StatusCode, responseBody);")
	gf.P("            }")
	gf.P("            if (typeof(TResponse) == typeof(", emptyTypeName, ") && string.IsNullOrWhiteSpace(responseBody))")
	gf.P("            {")
	gf.P("                return new TResponse();")
	gf.P("            }")
	gf.P("            if (string.IsNullOrWhiteSpace(responseBody))")
	gf.P("            {")
	gf.P("                return new TResponse();")
	gf.P("            }")
	gf.P("            var result = DeserializeResponse<TResponse>(responseBody);")
	gf.P("            return result is null ? new TResponse() : result;")
	gf.P("        }")
	gf.P()
}

func (g *Generator) generateSerializeRequest(gf *protogen.GeneratedFile) {
	gf.P("        private string SerializeRequest(object value)")
	gf.P("        {")
	if g.useNewtonsoft() {
		gf.P("            return JsonConvert.SerializeObject(value);")
	} else {
		gf.P("            return JsonSerializer.Serialize(value, JsonOptions);")
	}
	gf.P("        }")
	gf.P()
}

func (g *Generator) generateDeserializeResponse(gf *protogen.GeneratedFile) {
	gf.P("        private static TResponse? DeserializeResponse<TResponse>(string json)")
	gf.P("        {")
	if g.useNewtonsoft() {
		gf.P("            return JsonConvert.DeserializeObject<TResponse>(json);")
	} else {
		gf.P("            return JsonSerializer.Deserialize<TResponse>(json, JsonOptions);")
	}
	gf.P("        }")
	gf.P()
}

func (g *Generator) generatePathAndQueryHelpers(gf *protogen.GeneratedFile) {
	gf.P("        private static string FormatPathValue(object? value)")
	gf.P("        {")
	gf.P(`            return value?.ToString() ?? string.Empty;`)
	gf.P("        }")
	gf.P()
	gf.P("        private static string FormatQueryValue(object? value)")
	gf.P("        {")
	gf.P(`            return value?.ToString() ?? string.Empty;`)
	gf.P("        }")
	gf.P()
}

func serviceCallHeaders(service *contractmodel.Service) []*contractmodel.Header {
	headers := make([]*contractmodel.Header, 0, len(service.Headers))
	seen := make(map[string]bool)
	for _, header := range service.Headers {
		if header == nil || seen[header.Name] {
			continue
		}
		seen[header.Name] = true
		headers = append(headers, header)
	}
	for _, method := range service.Methods {
		for _, header := range method.Headers {
			if header == nil || seen[header.Name] {
				continue
			}
			seen[header.Name] = true
			headers = append(headers, header)
		}
	}
	return headers
}

func methodHasBody(method *contractmodel.Method) bool {
	switch method.HTTPMethod {
	case http.MethodPost, http.MethodPut, http.MethodPatch:
		return true
	default:
		return false
	}
}

func httpMethodName(method string) string {
	switch method {
	case http.MethodGet:
		return "Get"
	case http.MethodPost:
		return "Post"
	case http.MethodPut:
		return "Put"
	case http.MethodDelete:
		return "Delete"
	case http.MethodPatch:
		return "Patch"
	default:
		return "Post"
	}
}

func clientResponseType(method *contractmodel.Method) string {
	if method.ResponseType == "" {
		return emptyTypeName
	}
	return method.ResponseType
}

func csharpQueryCondition(field *contractmodel.Field, expr string) string {
	if field == nil || field.Type == nil {
		return expr + " != null"
	}
	if field.Optional || field.HasPresence {
		return expr + " != null"
	}
	switch field.Type.Kind {
	case contractmodel.KindScalar:
		switch field.Type.Name {
		case csharpStringType, "bytes":
			return "!string.IsNullOrEmpty(" + expr + ")"
		case "bool":
			return expr
		case "int32", "fixed32", "uint32", "sfixed32", "sint32", "int64", "uint64", "fixed64", "sfixed64", "sint64":
			return expr + " != 0"
		case "float", "double":
			return expr + " != 0"
		default:
			return expr + " != null"
		}
	case contractmodel.KindEnum:
		return expr + " != 0"
	case contractmodel.KindMessage, contractmodel.KindWellKnown, contractmodel.KindMap:
		return expr + " != null"
	default:
		return expr + " != null"
	}
}

func (g *Generator) markOneofFields(message *contractmodel.Message, skippedFields map[string]bool) {
	for _, oneof := range message.Oneofs {
		for _, variant := range oneof.Variants {
			skippedFields[variant.FieldName] = true
		}
	}
}

func (g *Generator) appendStandardMessageProperties(
	properties *[]generatedProperty,
	usedJSONNames map[string]bool,
	skippedFields map[string]bool,
	message *contractmodel.Message,
	messageIndex map[string]*contractmodel.Message,
) {
	for _, field := range message.Fields {
		if skippedFields[field.Name] {
			continue
		}
		if field.Annotations.Flatten && g.appendFlattenedProperties(properties, usedJSONNames, field, messageIndex) {
			continue
		}
		g.appendProperty(
			properties,
			usedJSONNames,
			field.Name,
			pascalCase(field.Name),
			csharpPropertyType(field, false),
			g.enumConverterAttribute(field),
		)
	}
}

func (g *Generator) appendOneofProperties(
	properties *[]generatedProperty,
	usedJSONNames map[string]bool,
	message *contractmodel.Message,
	messageIndex map[string]*contractmodel.Message,
) {
	for _, oneof := range message.Oneofs {
		if oneof.Discriminator != "" {
			g.appendProperty(
				properties,
				usedJSONNames,
				oneof.Discriminator,
				pascalCase(oneof.Discriminator),
				"string?",
				"",
			)
		}
		for _, variant := range oneof.Variants {
			if oneof.Flatten && variant.IsMessage &&
				g.appendFlattenedVariantProperties(properties, usedJSONNames, variant, messageIndex) {
				continue
			}

			variantField := findField(message, variant.FieldName)
			if variantField == nil {
				continue
			}
			g.appendProperty(
				properties,
				usedJSONNames,
				variant.FieldName,
				pascalCase(variant.FieldName),
				csharpPropertyType(variantField, true),
				g.enumConverterAttribute(variantField),
			)
		}
	}
}

func (g *Generator) appendFlattenedProperties(
	properties *[]generatedProperty,
	usedJSONNames map[string]bool,
	field *contractmodel.Field,
	messageIndex map[string]*contractmodel.Message,
) bool {
	child := childMessage(messageIndex, field)
	if child == nil {
		return false
	}

	for _, childField := range child.Fields {
		jsonName := field.Annotations.FlattenPrefix + childField.Name
		g.appendProperty(
			properties,
			usedJSONNames,
			jsonName,
			pascalCase(jsonName),
			csharpPropertyType(childField, true),
			g.enumConverterAttribute(childField),
		)
	}
	return true
}

func (g *Generator) appendFlattenedVariantProperties(
	properties *[]generatedProperty,
	usedJSONNames map[string]bool,
	variant *contractmodel.OneofVariant,
	messageIndex map[string]*contractmodel.Message,
) bool {
	child := messageIndex[variant.Type.Name]
	if child == nil {
		return false
	}

	for _, childField := range child.Fields {
		jsonName := childField.Name
		if usedJSONNames[jsonName] {
			return false
		}
	}

	for _, childField := range child.Fields {
		jsonName := childField.Name
		g.appendProperty(
			properties,
			usedJSONNames,
			jsonName,
			pascalCase(jsonName),
			csharpPropertyType(childField, true),
			g.enumConverterAttribute(childField),
		)
	}
	return true
}

func (g *Generator) appendProperty(
	properties *[]generatedProperty,
	usedJSONNames map[string]bool,
	jsonName string,
	name string,
	typ string,
	converter string,
) {
	if usedJSONNames[jsonName] {
		return
	}
	usedJSONNames[jsonName] = true
	*properties = append(*properties, generatedProperty{
		jsonName:  jsonName,
		name:      name,
		typ:       typ,
		converter: converter,
	})
}

func childMessage(messageIndex map[string]*contractmodel.Message, field *contractmodel.Field) *contractmodel.Message {
	if field == nil || field.Type == nil || field.Type.Kind != contractmodel.KindMessage {
		return nil
	}
	return messageIndex[field.Type.Name]
}

func findField(message *contractmodel.Message, name string) *contractmodel.Field {
	for _, field := range message.Fields {
		if field.Name == name {
			return field
		}
	}
	return nil
}

func isRootUnwrapMessage(message *contractmodel.Message) bool {
	return message != nil && message.Unwrap != nil && message.Unwrap.IsRoot && len(message.Fields) == 1
}

func rootUnwrapBaseType(message *contractmodel.Message) string {
	if message == nil || len(message.Fields) == 0 {
		return csharpObjectType
	}
	field := message.Fields[0]
	if field.IsMap {
		return csharpBaseType(field)
	}
	if field.Repeated && field.Type != nil {
		return "List<" + csharpBaseType(&contractmodel.Field{Type: field.Type, Annotations: field.Annotations}) + ">"
	}
	return csharpPropertyType(field, false)
}

func (g *Generator) useNewtonsoft() bool {
	return strings.EqualFold(g.opts.JSONLib, "newtonsoft")
}

func (g *Generator) jsonAttribute(name string) string {
	if g.useNewtonsoft() {
		return `[JsonProperty("` + name + `")]`
	}
	return `[JsonPropertyName("` + name + `")]`
}

func csharpType(field *contractmodel.Field) string {
	return csharpPropertyType(field, false)
}

func csharpPropertyType(field *contractmodel.Field, forceNullable bool) string {
	ref := field.Type
	if ref == nil {
		return csharpObjectType
	}
	base := csharpBaseType(field)
	if field.Repeated {
		if forceNullable {
			return "List<" + base + ">?"
		}
		return "List<" + base + ">"
	}
	if field.IsMap {
		if forceNullable {
			return base + "?"
		}
		return base
	}
	if shouldUseNullableType(field, ref, forceNullable) {
		return base + "?"
	}
	return base
}

func csharpBaseType(field *contractmodel.Field) string {
	ref := field.Type
	if ref == nil {
		return csharpObjectType
	}

	switch ref.Kind {
	case contractmodel.KindMessage:
		return ref.Name
	case contractmodel.KindEnum:
		return ref.Name
	case contractmodel.KindWellKnown:
		return csharpWellKnownType(field)
	case contractmodel.KindMap:
		return fmt.Sprintf("Dictionary<%s, %s>", csharpBaseTypeForRef(ref.MapKey), csharpBaseTypeForRef(ref.MapValue))
	case contractmodel.KindScalar:
		return csharpScalar(field)
	default:
		return csharpObjectType
	}
}

func csharpBaseTypeForRef(ref *contractmodel.TypeRef) string {
	return csharpBaseType(&contractmodel.Field{Type: ref})
}

func csharpWellKnownType(field *contractmodel.Field) string {
	ref := field.Type
	switch ref.WellKnown {
	case contractmodel.WellKnownStruct:
		return "Dictionary<string, object>"
	case contractmodel.WellKnownTimestamp:
		switch field.Annotations.TimestampFormat {
		case sebufhttp.TimestampFormat_TIMESTAMP_FORMAT_UNIX_SECONDS,
			sebufhttp.TimestampFormat_TIMESTAMP_FORMAT_UNIX_MILLIS:
			return csharpLongType
		case sebufhttp.TimestampFormat_TIMESTAMP_FORMAT_UNSPECIFIED,
			sebufhttp.TimestampFormat_TIMESTAMP_FORMAT_RFC3339,
			sebufhttp.TimestampFormat_TIMESTAMP_FORMAT_DATE:
			return csharpStringType
		default:
			return csharpStringType
		}
	case contractmodel.WellKnownDuration, contractmodel.WellKnownFieldMask:
		return csharpStringType
	case contractmodel.WellKnownListValue:
		return "List<object>"
	case contractmodel.WellKnownAny, contractmodel.WellKnownValue:
		return csharpObjectType
	case contractmodel.WellKnownEmpty:
		return "object"
	case contractmodel.WellKnownDoubleWrap,
		contractmodel.WellKnownFloatWrap,
		contractmodel.WellKnownInt64Wrap,
		contractmodel.WellKnownUInt64Wrap,
		contractmodel.WellKnownInt32Wrap,
		contractmodel.WellKnownUInt32Wrap,
		contractmodel.WellKnownBoolWrap,
		contractmodel.WellKnownStringWrap,
		contractmodel.WellKnownBytesWrap:
		return csharpScalar(&contractmodel.Field{Type: ref, Annotations: field.Annotations})
	default:
		return csharpObjectType
	}
}

func csharpScalar(field *contractmodel.Field) string {
	kind := field.Type.Name
	switch kind {
	case csharpDoubleType, "float":
		return csharpDoubleType
	case "int64", "uint64", "fixed64", "sfixed64", "sint64":
		if field.Annotations.Int64Encoding != sebufhttp.Int64Encoding_INT64_ENCODING_NUMBER {
			return csharpStringType
		}
		return csharpLongType
	case "int32", "fixed32", "uint32", "sfixed32", "sint32":
		return "int"
	case csharpBoolType:
		return csharpBoolType
	case csharpStringType, "bytes":
		return csharpStringType
	default:
		return csharpObjectType
	}
}

func (g *Generator) enumConverterAttribute(field *contractmodel.Field) string {
	if field.Type == nil || field.Type.Kind != contractmodel.KindEnum {
		return ""
	}
	if field.Annotations.EnumEncoding == sebufhttp.EnumEncoding_ENUM_ENCODING_NUMBER {
		return ""
	}
	if g.useNewtonsoft() {
		return `[JsonConverter(typeof(StringEnumConverter))]`
	}
	return `[JsonConverter(typeof(JsonStringEnumConverter))]`
}

func shouldUseNullableType(field *contractmodel.Field, ref *contractmodel.TypeRef, forceNullable bool) bool {
	if ref == nil {
		return false
	}
	if forceNullable {
		return true
	}
	if ref.Kind == contractmodel.KindWellKnown && isWrapper(ref.WellKnown) {
		return true
	}
	if field.Annotations.Nullable || field.Annotations.EmptyBehavior == sebufhttp.EmptyBehavior_EMPTY_BEHAVIOR_NULL ||
		field.Annotations.EmptyBehavior == sebufhttp.EmptyBehavior_EMPTY_BEHAVIOR_OMIT {
		return true
	}
	if !field.Optional && !field.HasPresence && !field.IsOneofVariant {
		return false
	}
	return true
}

func isWrapper(kind contractmodel.WellKnownType) bool {
	switch kind {
	case contractmodel.WellKnownDoubleWrap,
		contractmodel.WellKnownFloatWrap,
		contractmodel.WellKnownInt64Wrap,
		contractmodel.WellKnownUInt64Wrap,
		contractmodel.WellKnownInt32Wrap,
		contractmodel.WellKnownUInt32Wrap,
		contractmodel.WellKnownBoolWrap,
		contractmodel.WellKnownStringWrap,
		contractmodel.WellKnownBytesWrap:
		return true
	case contractmodel.WellKnownAny,
		contractmodel.WellKnownDuration,
		contractmodel.WellKnownEmpty,
		contractmodel.WellKnownFieldMask,
		contractmodel.WellKnownListValue,
		contractmodel.WellKnownStruct,
		contractmodel.WellKnownTimestamp,
		contractmodel.WellKnownValue:
		return false
	default:
		return false
	}
}

func pascalCase(name string) string {
	parts := strings.Split(name, "_")
	for i, part := range parts {
		if part == "" {
			continue
		}
		part = strings.ToLower(part)
		parts[i] = strings.ToUpper(part[:1]) + part[1:]
	}
	return strings.Join(parts, "")
}

func upperFirst(value string) string {
	if value == "" {
		return ""
	}
	return strings.ToUpper(value[:1]) + value[1:]
}
