// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.35.1
// 	protoc        v5.29.3
// source: sebuf/http/annotations.proto

package httpgen

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// HttpConfig defines HTTP-specific configuration for an RPC method
type HttpConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// The HTTP path for this method
	Path string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
}

func (x *HttpConfig) Reset() {
	*x = HttpConfig{}
	mi := &file_sebuf_http_annotations_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HttpConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HttpConfig) ProtoMessage() {}

func (x *HttpConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sebuf_http_annotations_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HttpConfig.ProtoReflect.Descriptor instead.
func (*HttpConfig) Descriptor() ([]byte, []int) {
	return file_sebuf_http_annotations_proto_rawDescGZIP(), []int{0}
}

func (x *HttpConfig) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

// ServiceConfig defines HTTP-specific configuration for an entire service
type ServiceConfig struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// Base path prefix for all methods in this service
	BasePath string `protobuf:"bytes,1,opt,name=base_path,json=basePath,proto3" json:"base_path,omitempty"`
}

func (x *ServiceConfig) Reset() {
	*x = ServiceConfig{}
	mi := &file_sebuf_http_annotations_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServiceConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServiceConfig) ProtoMessage() {}

func (x *ServiceConfig) ProtoReflect() protoreflect.Message {
	mi := &file_sebuf_http_annotations_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServiceConfig.ProtoReflect.Descriptor instead.
func (*ServiceConfig) Descriptor() ([]byte, []int) {
	return file_sebuf_http_annotations_proto_rawDescGZIP(), []int{1}
}

func (x *ServiceConfig) GetBasePath() string {
	if x != nil {
		return x.BasePath
	}
	return ""
}

var file_sebuf_http_annotations_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*HttpConfig)(nil),
		Field:         72295728,
		Name:          "sebuf.http.config",
		Tag:           "bytes,72295728,opt,name=config",
		Filename:      "sebuf/http/annotations.proto",
	},
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*ServiceConfig)(nil),
		Field:         72295729,
		Name:          "sebuf.http.service_config",
		Tag:           "bytes,72295729,opt,name=service_config",
		Filename:      "sebuf/http/annotations.proto",
	},
}

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional sebuf.http.HttpConfig config = 72295728;
	E_Config = &file_sebuf_http_annotations_proto_extTypes[0]
)

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional sebuf.http.ServiceConfig service_config = 72295729;
	E_ServiceConfig = &file_sebuf_http_annotations_proto_extTypes[1]
)

var File_sebuf_http_annotations_proto protoreflect.FileDescriptor

var file_sebuf_http_annotations_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x73, 0x65, 0x62, 0x75, 0x66, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x2f, 0x61, 0x6e, 0x6e,
	0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0a,
	0x73, 0x65, 0x62, 0x75, 0x66, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x1a, 0x20, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x64, 0x65, 0x73, 0x63,
	0x72, 0x69, 0x70, 0x74, 0x6f, 0x72, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x20, 0x0a, 0x0a,
	0x48, 0x74, 0x74, 0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x12, 0x0a, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61, 0x74, 0x68, 0x22, 0x2c,
	0x0a, 0x0d, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12,
	0x1b, 0x0a, 0x09, 0x62, 0x61, 0x73, 0x65, 0x5f, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x62, 0x61, 0x73, 0x65, 0x50, 0x61, 0x74, 0x68, 0x3a, 0x51, 0x0a, 0x06,
	0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x12, 0x1e, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x4d, 0x65, 0x74, 0x68, 0x6f, 0x64, 0x4f,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0xb0, 0xca, 0xbc, 0x22, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x16, 0x2e, 0x73, 0x65, 0x62, 0x75, 0x66, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x48, 0x74, 0x74,
	0x70, 0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x06, 0x63, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x3a,
	0x64, 0x0a, 0x0e, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x5f, 0x63, 0x6f, 0x6e, 0x66, 0x69,
	0x67, 0x12, 0x1f, 0x2e, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x62, 0x75, 0x66, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x4f, 0x70, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x18, 0xb1, 0xca, 0xbc, 0x22, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x19, 0x2e, 0x73, 0x65,
	0x62, 0x75, 0x66, 0x2e, 0x68, 0x74, 0x74, 0x70, 0x2e, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x43, 0x6f, 0x6e, 0x66, 0x69, 0x67, 0x52, 0x0d, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x43,
	0x6f, 0x6e, 0x66, 0x69, 0x67, 0x42, 0x3a, 0x5a, 0x38, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2e,
	0x63, 0x6f, 0x6d, 0x2f, 0x53, 0x65, 0x62, 0x61, 0x73, 0x74, 0x69, 0x65, 0x6e, 0x4d, 0x65, 0x6c,
	0x6b, 0x69, 0x2f, 0x73, 0x65, 0x62, 0x75, 0x66, 0x2f, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61,
	0x6c, 0x2f, 0x68, 0x74, 0x74, 0x70, 0x67, 0x65, 0x6e, 0x3b, 0x68, 0x74, 0x74, 0x70, 0x67, 0x65,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_sebuf_http_annotations_proto_rawDescOnce sync.Once
	file_sebuf_http_annotations_proto_rawDescData = file_sebuf_http_annotations_proto_rawDesc
)

func file_sebuf_http_annotations_proto_rawDescGZIP() []byte {
	file_sebuf_http_annotations_proto_rawDescOnce.Do(func() {
		file_sebuf_http_annotations_proto_rawDescData = protoimpl.X.CompressGZIP(file_sebuf_http_annotations_proto_rawDescData)
	})
	return file_sebuf_http_annotations_proto_rawDescData
}

var file_sebuf_http_annotations_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_sebuf_http_annotations_proto_goTypes = []any{
	(*HttpConfig)(nil),                  // 0: sebuf.http.HttpConfig
	(*ServiceConfig)(nil),               // 1: sebuf.http.ServiceConfig
	(*descriptorpb.MethodOptions)(nil),  // 2: google.protobuf.MethodOptions
	(*descriptorpb.ServiceOptions)(nil), // 3: google.protobuf.ServiceOptions
}
var file_sebuf_http_annotations_proto_depIdxs = []int32{
	2, // 0: sebuf.http.config:extendee -> google.protobuf.MethodOptions
	3, // 1: sebuf.http.service_config:extendee -> google.protobuf.ServiceOptions
	0, // 2: sebuf.http.config:type_name -> sebuf.http.HttpConfig
	1, // 3: sebuf.http.service_config:type_name -> sebuf.http.ServiceConfig
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_sebuf_http_annotations_proto_init() }
func file_sebuf_http_annotations_proto_init() {
	if File_sebuf_http_annotations_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_sebuf_http_annotations_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_sebuf_http_annotations_proto_goTypes,
		DependencyIndexes: file_sebuf_http_annotations_proto_depIdxs,
		MessageInfos:      file_sebuf_http_annotations_proto_msgTypes,
		ExtensionInfos:    file_sebuf_http_annotations_proto_extTypes,
	}.Build()
	File_sebuf_http_annotations_proto = out.File
	file_sebuf_http_annotations_proto_rawDesc = nil
	file_sebuf_http_annotations_proto_goTypes = nil
	file_sebuf_http_annotations_proto_depIdxs = nil
}
