package tsservergen

import (
	"google.golang.org/protobuf/compiler/protogen"

	"github.com/SebastienMelki/sebuf/internal/tscommon"
)

// generateModules emits shared canonical type modules and an errors module
// (via tscommon), plus one slimmed server module per service file that imports
// its request/response types and the error helpers, then a per-package barrel
// (index.ts) re-exporting each package directory's modules.
func (g *Generator) generateModules() error {
	moduleFiles, err := tscommon.EmitSharedModules(g.plugin, g.runtime)
	if err != nil {
		return err
	}
	for _, file := range g.plugin.Files {
		if !file.Generate || len(file.Services) == 0 {
			continue
		}
		name, emitErr := g.emitServerModule(file)
		if emitErr != nil {
			return emitErr
		}
		moduleFiles = append(moduleFiles, name)
	}
	tscommon.EmitPackageBarrels(g.plugin, moduleFiles)
	return nil
}

// emitServerModule writes a service file's server framework types + handlers,
// importing the request/response types from their canonical modules and the
// shared error helpers. It returns the output-relative filename it emitted
// (ending in ".ts"), so the caller can fold it into the per-package barrel.
func (g *Generator) emitServerModule(file *protogen.File) (string, error) {
	module := file.GeneratedFilenamePrefix + "_server"
	gf := g.plugin.NewGeneratedFile(module+".ts", "")
	tracker := tscommon.NewImportTracker()
	g.ctx = &tscommon.EmitContext{SelfModule: module, Imports: tracker, MessageRuntime: g.runtime}
	defer func() { g.ctx = nil }()

	var body []string
	bp := tscommon.BufferedPrinter(&body)

	g.writeServerTypes(bp)
	if g.fileUsesHeaders(file) {
		g.writeHeaderValidationHelpers(bp)
	}
	for _, service := range file.Services {
		if err := g.generateService(bp, service); err != nil {
			return "", err
		}
	}
	// Import only the error helpers actually referenced in the body.
	g.ctx.NeedErrors(tscommon.UsedErrorSymbols(body)...)

	dp := tscommon.DirectPrinter(gf)
	dp("// Code generated by protoc-gen-ts-server. DO NOT EDIT.")
	dp("// source: %s", file.Desc.Path())
	dp("")
	tracker.Render(dp)
	for _, line := range body {
		gf.P(line)
	}
	return module + ".ts", nil
}
