// Code generated by protoc-gen-ts-client. DO NOT EDIT.
// source: complex_features.proto

export interface ListNotesRequest {
  page: number;
  pageSize: number;
  filter: string;
}

export interface ListNotesResponse {
  notes: Note[];
  totalCount: number;
}

export interface Note {
  id: string;
  title: string;
  content: string;
  priority: Priority;
  status: Status;
  tags: Tag[];
  metadata: Record<string, string>;
  dueDate?: string;
  address?: Address;
}

export interface Tag {
  name: string;
  color: string;
}

export interface Address {
  street: string;
  city: string;
  zipCode: string;
}

export interface GetNoteRequest {
  noteId: string;
}

export interface CreateNoteRequest {
  title: string;
  content: string;
  priority: Priority;
  status: Status;
  tags: Tag[];
  metadata: Record<string, string>;
  dueDate?: string;
  address?: Address;
}

export interface UpdateNoteRequest {
  noteId: string;
  title: string;
  content: string;
  priority: Priority;
}

export interface GetNoteListRequest {
  category: string;
}

export interface NoteList {
  notes: Note[];
}

export interface GetNoteMapRequest {
  ownerId: string;
}

export interface NoteMap {
  notes: Record<string, Note>;
}

export interface GetBarsBySymbolRequest {
  symbols: string[];
}

export interface BarsBySymbol {
  data: Record<string, Bar[][]>;
}

export interface BarWrapper {
  bars: Bar[];
}

export interface Bar {
  symbol: string;
  price: number;
  volume: string;
}

export interface GetCombinedUnwrapRequest {
  market: string;
}

export interface CombinedUnwrap {
  data: Record<string, Bar[][]>;
}

export type Priority = "PRIORITY_UNSPECIFIED" | "PRIORITY_LOW" | "PRIORITY_MEDIUM" | "PRIORITY_HIGH" | "PRIORITY_URGENT";

export type Status = "STATUS_UNSPECIFIED" | "STATUS_PENDING" | "STATUS_IN_PROGRESS" | "STATUS_DONE" | "STATUS_ARCHIVED";

export interface FieldViolation {
  field: string;
  description: string;
}

export class ValidationError extends Error {
  violations: FieldViolation[];

  constructor(violations: FieldViolation[]) {
    super("Validation failed");
    this.name = "ValidationError";
    this.violations = violations;
  }
}

export class ApiError extends Error {
  statusCode: number;
  body: string;

  constructor(statusCode: number, message: string, body: string) {
    super(message);
    this.name = "ApiError";
    this.statusCode = statusCode;
    this.body = body;
  }
}

export interface FeatureServiceClientOptions {
  fetch?: typeof fetch;
  defaultHeaders?: Record<string, string>;
  apiKey?: string;
  tenantId?: string;
}

export interface FeatureServiceCallOptions {
  headers?: Record<string, string>;
  signal?: AbortSignal;
  apiKey?: string;
  tenantId?: string;
  requestId?: string;
  idempotencyKey?: string;
}

export class FeatureServiceClient {
  private baseURL: string;
  private fetchFn: typeof fetch;
  private defaultHeaders: Record<string, string>;

  constructor(baseURL: string, options?: FeatureServiceClientOptions) {
    this.baseURL = baseURL.replace(/\/+$/, "");
    this.fetchFn = options?.fetch ?? globalThis.fetch;
    this.defaultHeaders = { ...options?.defaultHeaders };
    if (options?.apiKey) {
      this.defaultHeaders["X-API-Key"] = options.apiKey;
    }
    if (options?.tenantId) {
      this.defaultHeaders["X-Tenant-ID"] = options.tenantId;
    }
  }

  async listNotes(req: ListNotesRequest, options?: FeatureServiceCallOptions): Promise<ListNotesResponse> {
    let path = "/api/v1/notes";
    const params = new URLSearchParams();
    if (req.page != null && req.page !== 0) params.set("page", String(req.page));
    if (req.pageSize != null && req.pageSize !== 0) params.set("page_size", String(req.pageSize));
    if (req.filter != null && req.filter !== "") params.set("filter", String(req.filter));
    const url = this.baseURL + path + (params.toString() ? "?" + params.toString() : "");

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };
    if (options?.apiKey) headers["X-API-Key"] = options.apiKey;
    if (options?.tenantId) headers["X-Tenant-ID"] = options.tenantId;

    const resp = await this.fetchFn(url, {
      method: "GET",
      headers,
      signal: options?.signal,
    });

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as ListNotesResponse;
  }

  async getNote(req: GetNoteRequest, options?: FeatureServiceCallOptions): Promise<Note> {
    let path = "/api/v1/notes/{note_id}";
    path = path.replace("{note_id}", encodeURIComponent(String(req.noteId)));
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };
    if (options?.apiKey) headers["X-API-Key"] = options.apiKey;
    if (options?.tenantId) headers["X-Tenant-ID"] = options.tenantId;

    const resp = await this.fetchFn(url, {
      method: "GET",
      headers,
      signal: options?.signal,
    });

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as Note;
  }

  async createNote(req: CreateNoteRequest, options?: FeatureServiceCallOptions): Promise<Note> {
    let path = "/api/v1/notes";
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };
    if (options?.apiKey) headers["X-API-Key"] = options.apiKey;
    if (options?.tenantId) headers["X-Tenant-ID"] = options.tenantId;
    if (options?.requestId) headers["X-Request-ID"] = options.requestId;

    const resp = await this.fetchFn(url, {
      method: "POST",
      headers,
      body: JSON.stringify(req),
      signal: options?.signal,
    });

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as Note;
  }

  async updateNote(req: UpdateNoteRequest, options?: FeatureServiceCallOptions): Promise<Note> {
    let path = "/api/v1/notes/{note_id}";
    path = path.replace("{note_id}", encodeURIComponent(String(req.noteId)));
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };
    if (options?.apiKey) headers["X-API-Key"] = options.apiKey;
    if (options?.tenantId) headers["X-Tenant-ID"] = options.tenantId;
    if (options?.idempotencyKey) headers["X-Idempotency-Key"] = options.idempotencyKey;

    const resp = await this.fetchFn(url, {
      method: "PUT",
      headers,
      body: JSON.stringify(req),
      signal: options?.signal,
    });

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as Note;
  }

  async getNoteList(req: GetNoteListRequest, options?: FeatureServiceCallOptions): Promise<Note[]> {
    let path = "/api/v1/notes/list";
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };
    if (options?.apiKey) headers["X-API-Key"] = options.apiKey;
    if (options?.tenantId) headers["X-Tenant-ID"] = options.tenantId;

    const resp = await this.fetchFn(url, {
      method: "POST",
      headers,
      body: JSON.stringify(req),
      signal: options?.signal,
    });

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as Note[];
  }

  async getNoteMap(req: GetNoteMapRequest, options?: FeatureServiceCallOptions): Promise<Record<string, Note>> {
    let path = "/api/v1/notes/map";
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };
    if (options?.apiKey) headers["X-API-Key"] = options.apiKey;
    if (options?.tenantId) headers["X-Tenant-ID"] = options.tenantId;

    const resp = await this.fetchFn(url, {
      method: "POST",
      headers,
      body: JSON.stringify(req),
      signal: options?.signal,
    });

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as Record<string, Note>;
  }

  async getBarsBySymbol(req: GetBarsBySymbolRequest, options?: FeatureServiceCallOptions): Promise<BarsBySymbol> {
    let path = "/api/v1/bars";
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };
    if (options?.apiKey) headers["X-API-Key"] = options.apiKey;
    if (options?.tenantId) headers["X-Tenant-ID"] = options.tenantId;

    const resp = await this.fetchFn(url, {
      method: "POST",
      headers,
      body: JSON.stringify(req),
      signal: options?.signal,
    });

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as BarsBySymbol;
  }

  async getCombinedUnwrap(req: GetCombinedUnwrapRequest, options?: FeatureServiceCallOptions): Promise<Record<string, Bar[][]>> {
    let path = "/api/v1/bars/combined";
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };
    if (options?.apiKey) headers["X-API-Key"] = options.apiKey;
    if (options?.tenantId) headers["X-Tenant-ID"] = options.tenantId;

    const resp = await this.fetchFn(url, {
      method: "POST",
      headers,
      body: JSON.stringify(req),
      signal: options?.signal,
    });

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as Record<string, Bar[][]>;
  }

  private async handleError(resp: Response): Promise<never> {
    const body = await resp.text();
    if (resp.status === 400) {
      try {
        const parsed = JSON.parse(body);
        if (parsed.violations) {
          throw new ValidationError(parsed.violations);
        }
      } catch (e) {
        if (e instanceof ValidationError) throw e;
      }
    }
    throw new ApiError(resp.status, `Request failed with status ${resp.status}`, body);
  }
}

