// Code generated by protoc-gen-ts-client. DO NOT EDIT.
// source: http_verbs_comprehensive.proto

import { ApiError, ValidationError } from "./errors";
import type { CreateResourceRequest, DefaultPostRequest, DefaultPostResponse, DeleteResourceRequest, DeleteResourceResponse, GetNestedResourceRequest, GetResourceRequest, LegacyRequest, LegacyResponse, ListResourcesRequest, ListResourcesResponse, PatchResourceRequest, Resource, SearchResourcesRequest, UpdateResourceRequest } from "./http_verbs_comprehensive";

export interface RESTfulAPIServiceClientOptions {
  fetch?: typeof fetch;
  defaultHeaders?: Record<string, string>;
  apiKey?: string;
}

export interface RESTfulAPIServiceCallOptions {
  headers?: Record<string, string>;
  signal?: AbortSignal;
  apiKey?: string;
  requestId?: string;
}

export class RESTfulAPIServiceClient {
  private baseURL: string;
  private fetchFn: typeof fetch;
  private defaultHeaders: Record<string, string>;

  constructor(baseURL: string, options?: RESTfulAPIServiceClientOptions) {
    this.baseURL = baseURL.replace(/\/+$/, "");
    this.fetchFn = options?.fetch ?? globalThis.fetch;
    this.defaultHeaders = { ...options?.defaultHeaders };
    if (options?.apiKey) {
      this.defaultHeaders["X-API-Key"] = options.apiKey;
    }
  }

  async listResources(req: ListResourcesRequest, options?: RESTfulAPIServiceCallOptions): Promise<ListResourcesResponse> {
    let path = "/api/v1/resources";
    const params = new URLSearchParams();
    if (req.page != null && req.page !== 0) params.set("page", String(req.page));
    if (req.pageSize != null && req.pageSize !== 0) params.set("page_size", String(req.pageSize));
    if (req.filter != null && req.filter !== "") params.set("filter", String(req.filter));
    if (req.includeDeleted) params.set("include_deleted", String(req.includeDeleted));
    if (req.sinceTimestamp != null && req.sinceTimestamp !== "0") params.set("since_timestamp", String(req.sinceTimestamp));
    if (req.maxId != null && req.maxId !== "0") params.set("max_id", String(req.maxId));
    if (req.minScore != null && req.minScore !== 0) params.set("min_score", String(req.minScore));
    if (req.maxScore != null && req.maxScore !== 0) params.set("max_score", String(req.maxScore));
    const url = this.baseURL + path + (params.toString() ? "?" + params.toString() : "");

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };
    if (options?.apiKey) headers["X-API-Key"] = options.apiKey;

    const resp = await this.fetchFn(url, {
      method: "GET",
      headers,
      signal: options?.signal,
    });

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as ListResourcesResponse;
  }

  async getResource(req: GetResourceRequest, options?: RESTfulAPIServiceCallOptions): Promise<Resource> {
    let path = "/api/v1/resources/{resource_id}";
    path = path.replace("{resource_id}", encodeURIComponent(String(req.resourceId)));
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };
    if (options?.apiKey) headers["X-API-Key"] = options.apiKey;

    const resp = await this.fetchFn(url, {
      method: "GET",
      headers,
      signal: options?.signal,
    });

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as Resource;
  }

  async getNestedResource(req: GetNestedResourceRequest, options?: RESTfulAPIServiceCallOptions): Promise<Resource> {
    let path = "/api/v1/orgs/{org_id}/teams/{team_id}/resources/{resource_id}";
    path = path.replace("{org_id}", encodeURIComponent(String(req.orgId)));
    path = path.replace("{team_id}", encodeURIComponent(String(req.teamId)));
    path = path.replace("{resource_id}", encodeURIComponent(String(req.resourceId)));
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };
    if (options?.apiKey) headers["X-API-Key"] = options.apiKey;

    const resp = await this.fetchFn(url, {
      method: "GET",
      headers,
      signal: options?.signal,
    });

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as Resource;
  }

  async createResource(req: CreateResourceRequest, options?: RESTfulAPIServiceCallOptions): Promise<Resource> {
    let path = "/api/v1/resources";
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };
    if (options?.apiKey) headers["X-API-Key"] = options.apiKey;
    if (options?.requestId) headers["X-Request-ID"] = options.requestId;

    const resp = await this.fetchFn(url, {
      method: "POST",
      headers,
      body: JSON.stringify(req),
      signal: options?.signal,
    });

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as Resource;
  }

  async updateResource(req: UpdateResourceRequest, options?: RESTfulAPIServiceCallOptions): Promise<Resource> {
    let path = "/api/v1/resources/{resource_id}";
    path = path.replace("{resource_id}", encodeURIComponent(String(req.resourceId)));
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };
    if (options?.apiKey) headers["X-API-Key"] = options.apiKey;

    const resp = await this.fetchFn(url, {
      method: "PUT",
      headers,
      body: JSON.stringify(req),
      signal: options?.signal,
    });

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as Resource;
  }

  async patchResource(req: PatchResourceRequest, options?: RESTfulAPIServiceCallOptions): Promise<Resource> {
    let path = "/api/v1/resources/{resource_id}";
    path = path.replace("{resource_id}", encodeURIComponent(String(req.resourceId)));
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };
    if (options?.apiKey) headers["X-API-Key"] = options.apiKey;

    const resp = await this.fetchFn(url, {
      method: "PATCH",
      headers,
      body: JSON.stringify(req),
      signal: options?.signal,
    });

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as Resource;
  }

  async deleteResource(req: DeleteResourceRequest, options?: RESTfulAPIServiceCallOptions): Promise<DeleteResourceResponse> {
    let path = "/api/v1/resources/{resource_id}";
    path = path.replace("{resource_id}", encodeURIComponent(String(req.resourceId)));
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };
    if (options?.apiKey) headers["X-API-Key"] = options.apiKey;

    const resp = await this.fetchFn(url, {
      method: "DELETE",
      headers,
      signal: options?.signal,
    });

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as DeleteResourceResponse;
  }

  async defaultPostMethod(req: DefaultPostRequest, options?: RESTfulAPIServiceCallOptions): Promise<DefaultPostResponse> {
    let path = "/api/v1/legacy/action";
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };
    if (options?.apiKey) headers["X-API-Key"] = options.apiKey;

    const resp = await this.fetchFn(url, {
      method: "POST",
      headers,
      body: JSON.stringify(req),
      signal: options?.signal,
    });

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as DefaultPostResponse;
  }

  async searchResources(req: SearchResourcesRequest, options?: RESTfulAPIServiceCallOptions): Promise<ListResourcesResponse> {
    let path = "/api/v1/resources/search";
    const params = new URLSearchParams();
    if (req.statusFilter != null && req.statusFilter !== "RESOURCE_STATUS_UNSPECIFIED") params.set("status", String(req.statusFilter));
    if (req.query != null && req.query !== "") params.set("q", String(req.query));
    const url = this.baseURL + path + (params.toString() ? "?" + params.toString() : "");

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };
    if (options?.apiKey) headers["X-API-Key"] = options.apiKey;

    const resp = await this.fetchFn(url, {
      method: "GET",
      headers,
      signal: options?.signal,
    });

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as ListResourcesResponse;
  }

  private async handleError(resp: Response): Promise<never> {
    const body = await resp.text();
    if (resp.status === 400) {
      try {
        const parsed = JSON.parse(body);
        if (parsed.violations) {
          throw new ValidationError(parsed.violations);
        }
      } catch (e) {
        if (e instanceof ValidationError) throw e;
      }
    }
    throw new ApiError(resp.status, `Request failed with status ${resp.status}`, body);
  }
}

export interface BackwardCompatServiceClientOptions {
  fetch?: typeof fetch;
  defaultHeaders?: Record<string, string>;
}

export interface BackwardCompatServiceCallOptions {
  headers?: Record<string, string>;
  signal?: AbortSignal;
}

export class BackwardCompatServiceClient {
  private baseURL: string;
  private fetchFn: typeof fetch;
  private defaultHeaders: Record<string, string>;

  constructor(baseURL: string, options?: BackwardCompatServiceClientOptions) {
    this.baseURL = baseURL.replace(/\/+$/, "");
    this.fetchFn = options?.fetch ?? globalThis.fetch;
    this.defaultHeaders = { ...options?.defaultHeaders };
  }

  async legacyAction(req: LegacyRequest, options?: BackwardCompatServiceCallOptions): Promise<LegacyResponse> {
    let path = "/legacyAction";
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };

    const resp = await this.fetchFn(url, {
      method: "POST",
      headers,
      body: JSON.stringify(req),
      signal: options?.signal,
    });

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as LegacyResponse;
  }

  private async handleError(resp: Response): Promise<never> {
    const body = await resp.text();
    if (resp.status === 400) {
      try {
        const parsed = JSON.parse(body);
        if (parsed.violations) {
          throw new ValidationError(parsed.violations);
        }
      } catch (e) {
        if (e instanceof ValidationError) throw e;
      }
    }
    throw new ApiError(resp.status, `Request failed with status ${resp.status}`, body);
  }
}

