// Code generated by protoc-gen-ts-client. DO NOT EDIT.
// source: int64_encoding.proto

export interface GetInt64TestRequest {
  id: string;
}

export interface Int64EncodingTest {
  defaultInt64: string;
  stringInt64: string;
  numberInt64: number;
  defaultUint64: string;
  numberUint64: number;
  numberSint64: number;
  numberSfixed64: number;
  numberFixed64: number;
  repeatedNumberInt64: number[];
  repeatedDefaultInt64: string[];
  optionalNumberInt64?: number;
  commentedNumberInt64: number;
}

export interface FieldViolation {
  field: string;
  description: string;
}

export class ValidationError extends Error {
  violations: FieldViolation[];

  constructor(violations: FieldViolation[]) {
    super("Validation failed");
    this.name = "ValidationError";
    this.violations = violations;
  }
}

export class ApiError extends Error {
  statusCode: number;
  body: string;

  constructor(statusCode: number, message: string, body: string) {
    super(message);
    this.name = "ApiError";
    this.statusCode = statusCode;
    this.body = body;
  }
}

export interface Int64EncodingServiceClientOptions {
  fetch?: typeof fetch;
  defaultHeaders?: Record<string, string>;
}

export interface Int64EncodingServiceCallOptions {
  headers?: Record<string, string>;
  signal?: AbortSignal;
}

export class Int64EncodingServiceClient {
  private baseURL: string;
  private fetchFn: typeof fetch;
  private defaultHeaders: Record<string, string>;

  constructor(baseURL: string, options?: Int64EncodingServiceClientOptions) {
    this.baseURL = baseURL.replace(/\/+$/, "");
    this.fetchFn = options?.fetch ?? globalThis.fetch;
    this.defaultHeaders = { ...options?.defaultHeaders };
  }

  async getInt64Test(req: GetInt64TestRequest, options?: Int64EncodingServiceCallOptions): Promise<Int64EncodingTest> {
    let path = "/api/v1/test/int64/{id}";
    path = path.replace("{id}", encodeURIComponent(String(req.id)));
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };

    const resp = await this.fetchFn(url, {
      method: "GET",
      headers,
      signal: options?.signal,
    });

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as Int64EncodingTest;
  }

  private async handleError(resp: Response): Promise<never> {
    const body = await resp.text();
    if (resp.status === 400) {
      try {
        const parsed = JSON.parse(body);
        if (parsed.violations) {
          throw new ValidationError(parsed.violations);
        }
      } catch (e) {
        if (e instanceof ValidationError) throw e;
      }
    }
    throw new ApiError(resp.status, `Request failed with status ${resp.status}`, body);
  }
}

