// Code generated by protoc-gen-ts-client. DO NOT EDIT.
// source: message_only.proto

export interface DashboardState {
  status: string;
  workers: Worker[];
  metrics?: Struct;
}

export interface Worker {
  id: string;
  name: string;
}

export interface Struct {
  fields: Record<string, Value>;
}

export interface Value {
  nullValue: NullValue;
  numberValue: number;
  stringValue: string;
  boolValue: boolean;
  structValue?: Struct;
  listValue?: ListValue;
}

export interface ListValue {
  values: Value[];
}

export type NullValue = "NULL_VALUE";

export interface FieldViolation {
  field: string;
  description: string;
}

export class ValidationError extends Error {
  violations: FieldViolation[];

  constructor(violations: FieldViolation[]) {
    super("Validation failed");
    this.name = "ValidationError";
    this.violations = violations;
  }
}

export class ApiError extends Error {
  statusCode: number;
  body: string;

  constructor(statusCode: number, message: string, body: string) {
    super(message);
    this.name = "ApiError";
    this.statusCode = statusCode;
    this.body = body;
  }
}

