// Code generated by sebuf. DO NOT EDIT.
// source: oneof_discriminator.proto

export type FlattenedEventContent =
  | { type: "text"; body: string }
  | { type: "img"; url: string; width: number; height: number };

export interface FlattenedEventBase {
  id: string;
}

export type FlattenedEvent = FlattenedEventBase & FlattenedEventContent;

export interface TextContent {
  body: string;
}

export interface ImageContent {
  url: string;
  width: number;
  height: number;
}

export type NestedEventContent =
  | { kind: "text"; text?: TextContent }
  | { kind: "image"; image?: ImageContent }
  | { kind: "vid"; video?: VideoContent };

export interface NestedEvent {
  id: string;
  content?: NestedEventContent;
}

export interface VideoContent {
  url: string;
  duration: number;
}

export interface PlainEvent {
  id: string;
  text?: TextContent;
  image?: ImageContent;
}

