// Code generated by protoc-gen-ts-client. DO NOT EDIT.
// source: timestamp_format.proto

export interface TimestampFormatTest {
  defaultTs?: string;
  rfc3339Ts?: string;
  unixSecondsTs?: number;
  unixMillisTs?: number;
  dateTs?: string;
}

export interface TimestampFormatRequest {
  id: string;
}

export interface FieldViolation {
  field: string;
  description: string;
}

export class ValidationError extends Error {
  violations: FieldViolation[];

  constructor(violations: FieldViolation[]) {
    super("Validation failed");
    this.name = "ValidationError";
    this.violations = violations;
  }
}

export class ApiError extends Error {
  statusCode: number;
  body: string;

  constructor(statusCode: number, message: string, body: string) {
    super(message);
    this.name = "ApiError";
    this.statusCode = statusCode;
    this.body = body;
  }
}

export interface TimestampFormatServiceClientOptions {
  fetch?: typeof fetch;
  defaultHeaders?: Record<string, string>;
}

export interface TimestampFormatServiceCallOptions {
  headers?: Record<string, string>;
  signal?: AbortSignal;
}

export class TimestampFormatServiceClient {
  private baseURL: string;
  private fetchFn: typeof fetch;
  private defaultHeaders: Record<string, string>;

  constructor(baseURL: string, options?: TimestampFormatServiceClientOptions) {
    this.baseURL = baseURL.replace(/\/+$/, "");
    this.fetchFn = options?.fetch ?? globalThis.fetch;
    this.defaultHeaders = { ...options?.defaultHeaders };
  }

  async createTimestampFormat(req: TimestampFormatTest, options?: TimestampFormatServiceCallOptions): Promise<TimestampFormatTest> {
    let path = "/api/v1/timestamp-format";
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };

    const resp = await this.fetchFn(url, {
      method: "POST",
      headers,
      body: JSON.stringify(req),
      signal: options?.signal,
    });

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as TimestampFormatTest;
  }

  async getTimestampFormat(req: TimestampFormatRequest, options?: TimestampFormatServiceCallOptions): Promise<TimestampFormatTest> {
    let path = "/api/v1/timestamp-format/{id}";
    path = path.replace("{id}", encodeURIComponent(String(req.id)));
    const url = this.baseURL + path;

    const headers: Record<string, string> = {
      "Content-Type": "application/json",
      ...this.defaultHeaders,
      ...options?.headers,
    };

    const resp = await this.fetchFn(url, {
      method: "GET",
      headers,
      signal: options?.signal,
    });

    if (!resp.ok) {
      return this.handleError(resp);
    }

    return await resp.json() as TimestampFormatTest;
  }

  private async handleError(resp: Response): Promise<never> {
    const body = await resp.text();
    if (resp.status === 400) {
      try {
        const parsed = JSON.parse(body);
        if (parsed.violations) {
          throw new ValidationError(parsed.violations);
        }
      } catch (e) {
        if (e instanceof ValidationError) throw e;
      }
    }
    throw new ApiError(resp.status, `Request failed with status ${resp.status}`, body);
  }
}

