// Code generated by protoc-gen-go-client. DO NOT EDIT.
// source: enum_nested.proto

package enumnested

import (
	"encoding/json"
	"fmt"
)

var gradeToJSON = map[Grade]string{
	Grade_GRADE_UNSPECIFIED: "GRADE_UNSPECIFIED",
	Grade_GRADE_A:           "a",
	Grade_GRADE_B:           "b",
}

var gradeFromJSON = map[string]Grade{
	"GRADE_UNSPECIFIED": Grade_GRADE_UNSPECIFIED,
	"a":                 Grade_GRADE_A,
	"b":                 Grade_GRADE_B,
	"GRADE_A":           Grade_GRADE_A,
	"GRADE_B":           Grade_GRADE_B,
}

func (x Grade) MarshalJSON() ([]byte, error) {
	if s, ok := gradeToJSON[x]; ok {
		return json.Marshal(s)
	}
	return json.Marshal(x.String())
}

func (x *Grade) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err == nil {
		if v, ok := gradeFromJSON[s]; ok {
			*x = v
			return nil
		}
		return fmt.Errorf("unknown Grade value: %q", s)
	}

	var n int32
	if err := json.Unmarshal(data, &n); err == nil {
		*x = Grade(n)
		return nil
	}

	return fmt.Errorf("cannot unmarshal %s into Grade", string(data))
}
