// Code generated by protoc-gen-go-client. DO NOT EDIT.
// source: enum_encoding.proto

package enumencoding

import (
	"encoding/json"

	"google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSONSebuf implements sebufMarshaler for EnumEncodingTest.
// This method handles enum_value fields: status, status_list, optional_status, status_map
func (x *EnumEncodingTest) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	// Use protojson for base serialization (handles all other fields correctly)
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}

	// Parse into a map to rewrite enum fields to their custom enum_value strings
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Rewrite status to custom enum_value strings
	if v, ok := raw["status"]; ok {
		var s string
		if err := json.Unmarshal(v, &s); err == nil {
			if e, ok := statusFromJSON[s]; ok {
				raw["status"], _ = json.Marshal(statusToJSON[e])
			}
		}
	}

	// Rewrite status_list to custom enum_value strings
	if v, ok := raw["statusList"]; ok {
		var arr []string
		if err := json.Unmarshal(v, &arr); err == nil {
			for i, s := range arr {
				if e, ok := statusFromJSON[s]; ok {
					arr[i] = statusToJSON[e]
				}
			}
			raw["statusList"], _ = json.Marshal(arr)
		}
	}

	// Rewrite optional_status to custom enum_value strings
	if v, ok := raw["optionalStatus"]; ok {
		var s string
		if err := json.Unmarshal(v, &s); err == nil {
			if e, ok := statusFromJSON[s]; ok {
				raw["optionalStatus"], _ = json.Marshal(statusToJSON[e])
			}
		}
	}

	// Rewrite status_map to custom enum_value strings
	if v, ok := raw["statusMap"]; ok {
		var m map[string]string
		if err := json.Unmarshal(v, &m); err == nil {
			for k, s := range m {
				if e, ok := statusFromJSON[s]; ok {
					m[k] = statusToJSON[e]
				}
			}
			raw["statusMap"], _ = json.Marshal(m)
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for EnumEncodingTest.
func (x *EnumEncodingTest) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for EnumEncodingTest.
// This method handles enum_value fields: status, status_list, optional_status, status_map
func (x *EnumEncodingTest) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	// Parse the raw JSON to rewrite custom enum_value strings back to proto names
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Rewrite status from custom enum_value strings to proto names
	if v, ok := raw["status"]; ok {
		var s string
		if err := json.Unmarshal(v, &s); err == nil {
			if e, ok := statusFromJSON[s]; ok {
				raw["status"], _ = json.Marshal(e.String())
			}
		}
	}

	// Rewrite status_list from custom enum_value strings to proto names
	if v, ok := raw["statusList"]; ok {
		var arr []string
		if err := json.Unmarshal(v, &arr); err == nil {
			for i, s := range arr {
				if e, ok := statusFromJSON[s]; ok {
					arr[i] = e.String()
				}
			}
			raw["statusList"], _ = json.Marshal(arr)
		}
	}

	// Rewrite optional_status from custom enum_value strings to proto names
	if v, ok := raw["optionalStatus"]; ok {
		var s string
		if err := json.Unmarshal(v, &s); err == nil {
			if e, ok := statusFromJSON[s]; ok {
				raw["optionalStatus"], _ = json.Marshal(e.String())
			}
		}
	}

	// Rewrite status_map from custom enum_value strings to proto names
	if v, ok := raw["statusMap"]; ok {
		var m map[string]string
		if err := json.Unmarshal(v, &m); err == nil {
			for k, s := range m {
				if e, ok := statusFromJSON[s]; ok {
					m[k] = e.String()
				}
			}
			raw["statusMap"], _ = json.Marshal(m)
		}
	}

	// Re-marshal with proto value names for protojson
	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}

	// Use protojson to unmarshal the rest
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for EnumEncodingTest.
func (x *EnumEncodingTest) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}
