// Code generated by protoc-gen-go-client. DO NOT EDIT.
// source: query_params.proto

package generated

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"

	sebufhttp "github.com/SebastienMelki/sebuf/http"
)

const (
	// ContentTypeJSON is the content type for JSON requests/responses.
	ContentTypeJSON = "application/json"
	// ContentTypeProto is the content type for binary protobuf requests/responses.
	ContentTypeProto = "application/x-protobuf"
)

// QueryParamServiceClient is the client API for QueryParamService service.
type QueryParamServiceClient interface {
	SearchWithTypes(ctx context.Context, req *SearchWithTypesRequest, opts ...QueryParamServiceCallOption) (*SearchResponse, error)
	SearchRequired(ctx context.Context, req *SearchRequiredRequest, opts ...QueryParamServiceCallOption) (*SearchResponse, error)
	SearchCustomNames(ctx context.Context, req *SearchCustomNamesRequest, opts ...QueryParamServiceCallOption) (*SearchResponse, error)
	GetWithFilters(ctx context.Context, req *GetWithFiltersRequest, opts ...QueryParamServiceCallOption) (*SearchResponse, error)
}

// queryParamServiceClient is the implementation of QueryParamServiceClient.
type queryParamServiceClient struct {
	baseURL        string
	httpClient     *http.Client
	contentType    string
	defaultHeaders map[string]string
}

var _ QueryParamServiceClient = (*queryParamServiceClient)(nil)

// QueryParamServiceClientOption configures a QueryParamService client.
type QueryParamServiceClientOption func(*queryParamServiceClient)

// WithQueryParamServiceHTTPClient sets the HTTP client to use for requests.
func WithQueryParamServiceHTTPClient(client *http.Client) QueryParamServiceClientOption {
	return func(c *queryParamServiceClient) {
		c.httpClient = client
	}
}

// WithQueryParamServiceContentType sets the default content type for requests.
// Use ContentTypeJSON or ContentTypeProto.
func WithQueryParamServiceContentType(contentType string) QueryParamServiceClientOption {
	return func(c *queryParamServiceClient) {
		c.contentType = contentType
	}
}

// WithQueryParamServiceDefaultHeader sets a default header to include in all requests.
func WithQueryParamServiceDefaultHeader(key, value string) QueryParamServiceClientOption {
	return func(c *queryParamServiceClient) {
		if c.defaultHeaders == nil {
			c.defaultHeaders = make(map[string]string)
		}
		c.defaultHeaders[key] = value
	}
}

// QueryParamServiceCallOption configures a single RPC call.
type QueryParamServiceCallOption func(*queryParamServiceCallOptions)

// queryParamServiceCallOptions holds options for a single RPC call.
type queryParamServiceCallOptions struct {
	headers     map[string]string
	contentType string
}

// WithQueryParamServiceHeader adds a header to a single request.
func WithQueryParamServiceHeader(key, value string) QueryParamServiceCallOption {
	return func(o *queryParamServiceCallOptions) {
		if o.headers == nil {
			o.headers = make(map[string]string)
		}
		o.headers[key] = value
	}
}

// WithQueryParamServiceCallContentType sets the content type for a single request.
func WithQueryParamServiceCallContentType(contentType string) QueryParamServiceCallOption {
	return func(o *queryParamServiceCallOptions) {
		o.contentType = contentType
	}
}

// NewQueryParamServiceClient creates a new QueryParamService client.
func NewQueryParamServiceClient(baseURL string, opts ...QueryParamServiceClientOption) QueryParamServiceClient {
	c := &queryParamServiceClient{
		baseURL:        strings.TrimSuffix(baseURL, "/"),
		httpClient:     http.DefaultClient,
		contentType:    ContentTypeJSON,
		defaultHeaders: make(map[string]string),
	}

	for _, opt := range opts {
		opt(c)
	}

	return c
}

// SearchWithTypes calls the SearchWithTypes RPC.
func (c *queryParamServiceClient) SearchWithTypes(ctx context.Context, req *SearchWithTypesRequest, opts ...QueryParamServiceCallOption) (*SearchResponse, error) {
	callOpts := &queryParamServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/search/typed"
	reqURL := c.baseURL + path

	// Add query parameters
	queryParams := url.Values{}
	if req.Query != "" {
		queryParams.Set("q", fmt.Sprint(req.Query))
	}
	if req.Limit != 0 {
		queryParams.Set("limit", fmt.Sprint(req.Limit))
	}
	if req.Offset != 0 {
		queryParams.Set("offset", fmt.Sprint(req.Offset))
	}
	if req.Active != false {
		queryParams.Set("active", fmt.Sprint(req.Active))
	}
	if req.MinScore != 0 {
		queryParams.Set("min_score", fmt.Sprint(req.MinScore))
	}
	if req.MaxScore != 0 {
		queryParams.Set("max_score", fmt.Sprint(req.MaxScore))
	}
	if req.Page != 0 {
		queryParams.Set("page", fmt.Sprint(req.Page))
	}
	if req.Timestamp != 0 {
		queryParams.Set("ts", fmt.Sprint(req.Timestamp))
	}
	if len(queryParams) > 0 {
		reqURL += "?" + queryParams.Encode()
	}

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Unmarshal response
	result := &SearchResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// SearchRequired calls the SearchRequired RPC.
func (c *queryParamServiceClient) SearchRequired(ctx context.Context, req *SearchRequiredRequest, opts ...QueryParamServiceCallOption) (*SearchResponse, error) {
	callOpts := &queryParamServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/search/required"
	reqURL := c.baseURL + path

	// Add query parameters
	queryParams := url.Values{}
	if req.Query != "" {
		queryParams.Set("q", fmt.Sprint(req.Query))
	}
	if req.Page != 0 {
		queryParams.Set("page", fmt.Sprint(req.Page))
	}
	if req.PageSize != 0 {
		queryParams.Set("page_size", fmt.Sprint(req.PageSize))
	}
	if len(queryParams) > 0 {
		reqURL += "?" + queryParams.Encode()
	}

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Unmarshal response
	result := &SearchResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// SearchCustomNames calls the SearchCustomNames RPC.
func (c *queryParamServiceClient) SearchCustomNames(ctx context.Context, req *SearchCustomNamesRequest, opts ...QueryParamServiceCallOption) (*SearchResponse, error) {
	callOpts := &queryParamServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/search/custom"
	reqURL := c.baseURL + path

	// Add query parameters
	queryParams := url.Values{}
	if req.SearchTerm != "" {
		queryParams.Set("q", fmt.Sprint(req.SearchTerm))
	}
	if req.ResultsPerPage != 0 {
		queryParams.Set("limit", fmt.Sprint(req.ResultsPerPage))
	}
	if req.PageNumber != 0 {
		queryParams.Set("page", fmt.Sprint(req.PageNumber))
	}
	if req.SortField != "" {
		queryParams.Set("sort", fmt.Sprint(req.SortField))
	}
	if req.DescendingOrder != false {
		queryParams.Set("desc", fmt.Sprint(req.DescendingOrder))
	}
	if len(queryParams) > 0 {
		reqURL += "?" + queryParams.Encode()
	}

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Unmarshal response
	result := &SearchResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

// GetWithFilters calls the GetWithFilters RPC.
func (c *queryParamServiceClient) GetWithFilters(ctx context.Context, req *GetWithFiltersRequest, opts ...QueryParamServiceCallOption) (*SearchResponse, error) {
	callOpts := &queryParamServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/resources/{resource_id}/items"
	path = strings.Replace(path, "{resource_id}", url.PathEscape(fmt.Sprint(req.ResourceId)), 1)
	reqURL := c.baseURL + path

	// Add query parameters
	queryParams := url.Values{}
	if req.Filter != "" {
		queryParams.Set("filter", fmt.Sprint(req.Filter))
	}
	if req.Limit != 0 {
		queryParams.Set("limit", fmt.Sprint(req.Limit))
	}
	if len(queryParams) > 0 {
		reqURL += "?" + queryParams.Encode()
	}

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Unmarshal response
	result := &SearchResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

func (c *queryParamServiceClient) marshalRequest(req proto.Message, contentType string) ([]byte, error) {
	switch contentType {
	case ContentTypeJSON:
		// Check for custom JSON marshaler (unwrap support)
		if marshaler, ok := req.(json.Marshaler); ok {
			return marshaler.MarshalJSON()
		}
		return protojson.Marshal(req)
	case ContentTypeProto:
		return proto.Marshal(req)
	default:
		return protojson.Marshal(req)
	}
}

func (c *queryParamServiceClient) handleErrorResponse(statusCode int, body []byte, contentType string) error {
	// Try to parse as ValidationError first (for 400 errors)
	if statusCode == http.StatusBadRequest {
		validationErr := &sebufhttp.ValidationError{}
		if unmarshalErr := c.unmarshalResponse(body, validationErr, contentType); unmarshalErr == nil {
			return validationErr
		}
	}

	// Try to parse as generic Error
	genericErr := &sebufhttp.Error{}
	if unmarshalErr := c.unmarshalResponse(body, genericErr, contentType); unmarshalErr == nil {
		return genericErr
	}

	// Fallback to raw error message
	return fmt.Errorf("request failed with status %d: %s", statusCode, string(body))
}

func (c *queryParamServiceClient) unmarshalResponse(body []byte, msg proto.Message, contentType string) error {
	if len(body) == 0 {
		return nil
	}

	switch contentType {
	case ContentTypeJSON:
		// Check for custom JSON unmarshaler (unwrap support)
		if unmarshaler, ok := msg.(json.Unmarshaler); ok {
			return unmarshaler.UnmarshalJSON(body)
		}
		return protojson.Unmarshal(body, msg)
	case ContentTypeProto:
		return proto.Unmarshal(body, msg)
	default:
		return protojson.Unmarshal(body, msg)
	}
}
