// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: proto/models/unwrap_coverage.proto

package models

import (
	"encoding/json"

	"google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSONSebuf implements sebufMarshaler for TradeList.
// This method performs root-level unwrap, serializing the message as just the array value.
func (x *TradeList) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	items := make([]json.RawMessage, 0, len(x.Trades))
	for _, item := range x.Trades {
		var data []byte
		var err error
		if m, ok := any(item).(interface {
			MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
		}); ok {
			data, err = m.MarshalJSONSebuf(opts)
		} else {
			data, err = opts.Marshal(item)
		}
		if err != nil {
			return nil, err
		}
		items = append(items, data)
	}
	return json.Marshal(items)

}

// MarshalJSON implements json.Marshaler for TradeList.
func (x *TradeList) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for TradeList.
// This method performs root-level unwrap, deserializing from just the array value.
func (x *TradeList) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	var itemsRaw []json.RawMessage
	if err := json.Unmarshal(data, &itemsRaw); err != nil {
		return err
	}
	x.Trades = make([]*Trade, 0, len(itemsRaw))
	for _, itemRaw := range itemsRaw {
		item := &Trade{}
		if u, ok := any(item).(interface {
			UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
		}); ok {
			if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
				return err
			}
		} else if err := opts.Unmarshal(itemRaw, item); err != nil {
			return err
		}
		x.Trades = append(x.Trades, item)
	}
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for TradeList.
func (x *TradeList) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for QuotesBySymbol.
// This method performs root-level unwrap, serializing the message as just the map value.
func (x *QuotesBySymbol) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	out := make(map[string]json.RawMessage)
	for k, v := range x.Quotes {
		if v != nil {
			var data []byte
			var err error
			if m, ok := any(v).(interface {
				MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
			}); ok {
				data, err = m.MarshalJSONSebuf(opts)
			} else {
				data, err = opts.Marshal(v)
			}
			if err != nil {
				return nil, err
			}
			out[k] = data
		}
	}
	return json.Marshal(out)
}

// MarshalJSON implements json.Marshaler for QuotesBySymbol.
func (x *QuotesBySymbol) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for QuotesBySymbol.
// This method performs root-level unwrap, deserializing from just the map value.
func (x *QuotesBySymbol) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	var mapRaw map[string]json.RawMessage
	if err := json.Unmarshal(data, &mapRaw); err != nil {
		return err
	}
	x.Quotes = make(map[string]*Quote)
	for k, v := range mapRaw {
		item := &Quote{}
		if u, ok := any(item).(interface {
			UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
		}); ok {
			if err := u.UnmarshalJSONSebuf(v, opts); err != nil {
				return err
			}
		} else if err := opts.Unmarshal(v, item); err != nil {
			return err
		}
		x.Quotes[k] = item
	}
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for QuotesBySymbol.
func (x *QuotesBySymbol) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for SymbolNames.
// This method performs root-level unwrap, serializing the message as just the map value.
func (x *SymbolNames) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	return json.Marshal(x.Names)
}

// MarshalJSON implements json.Marshaler for SymbolNames.
func (x *SymbolNames) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for SymbolNames.
// This method performs root-level unwrap, deserializing from just the map value.
func (x *SymbolNames) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	return json.Unmarshal(data, &x.Names)
}

// UnmarshalJSON implements json.Unmarshaler for SymbolNames.
func (x *SymbolNames) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for BarsBySymbol.
// This method performs root-level unwrap, serializing the message as just the map value.
func (x *BarsBySymbol) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	out := make(map[string]json.RawMessage)
	for k, wrapper := range x.Bars {
		if wrapper != nil {
			items := make([]json.RawMessage, 0, len(wrapper.GetBars()))
			for _, item := range wrapper.GetBars() {
				var data []byte
				var err error
				if m, ok := any(item).(interface {
					MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
				}); ok {
					data, err = m.MarshalJSONSebuf(opts)
				} else {
					data, err = opts.Marshal(item)
				}
				if err != nil {
					return nil, err
				}
				items = append(items, data)
			}
			arrayData, err := json.Marshal(items)
			if err != nil {
				return nil, err
			}
			out[k] = arrayData
		}
	}
	return json.Marshal(out)
}

// MarshalJSON implements json.Marshaler for BarsBySymbol.
func (x *BarsBySymbol) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for BarsBySymbol.
// This method performs root-level unwrap, deserializing from just the map value.
func (x *BarsBySymbol) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	var mapRaw map[string]json.RawMessage
	if err := json.Unmarshal(data, &mapRaw); err != nil {
		return err
	}
	x.Bars = make(map[string]*OptionBarsList)
	for k, arrayRaw := range mapRaw {
		var itemsRaw []json.RawMessage
		if err := json.Unmarshal(arrayRaw, &itemsRaw); err != nil {
			return err
		}
		items := make([]*OptionBar, 0, len(itemsRaw))
		for _, itemRaw := range itemsRaw {
			item := &OptionBar{}
			if u, ok := any(item).(interface {
				UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
			}); ok {
				if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
					return err
				}
			} else if err := opts.Unmarshal(itemRaw, item); err != nil {
				return err
			}
			items = append(items, item)
		}
		x.Bars[k] = &OptionBarsList{Bars: items}
	}
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for BarsBySymbol.
func (x *BarsBySymbol) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for BarListSequence.
// This method performs root-level unwrap, serializing the message as just the array value.
func (x *BarListSequence) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}

	items := make([]json.RawMessage, 0, len(x.Lists))
	for _, item := range x.Lists {
		var data []byte
		var err error
		if m, ok := any(item).(interface {
			MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
		}); ok {
			data, err = m.MarshalJSONSebuf(opts)
		} else {
			data, err = opts.Marshal(item)
		}
		if err != nil {
			return nil, err
		}
		items = append(items, data)
	}
	return json.Marshal(items)

}

// MarshalJSON implements json.Marshaler for BarListSequence.
func (x *BarListSequence) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for BarListSequence.
// This method performs root-level unwrap, deserializing from just the array value.
func (x *BarListSequence) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	var itemsRaw []json.RawMessage
	if err := json.Unmarshal(data, &itemsRaw); err != nil {
		return err
	}
	x.Lists = make([]*OptionBarsList, 0, len(itemsRaw))
	for _, itemRaw := range itemsRaw {
		item := &OptionBarsList{}
		if u, ok := any(item).(interface {
			UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
		}); ok {
			if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
				return err
			}
		} else if err := opts.Unmarshal(itemRaw, item); err != nil {
			return err
		}
		x.Lists = append(x.Lists, item)
	}
	return nil
}

// UnmarshalJSON implements json.Unmarshaler for BarListSequence.
func (x *BarListSequence) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}
