// Code generated by protoc-gen-go-client. DO NOT EDIT.
// source: proto/services/quotes.proto

package services

import (
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"google.golang.org/protobuf/encoding/protojson"
	"google.golang.org/protobuf/proto"

	sebufhttp "github.com/SebastienMelki/sebuf/http"
)

const (
	// ContentTypeJSON is the content type for JSON requests/responses.
	ContentTypeJSON = "application/json"
	// ContentTypeProto is the content type for binary protobuf requests/responses.
	ContentTypeProto = "application/x-protobuf"
)

// QuoteServiceClient is the client API for QuoteService service.
type QuoteServiceClient interface {
	GetQuote(ctx context.Context, req *GetQuoteRequest, opts ...QuoteServiceCallOption) (*QuoteResponse, error)
}

// quoteServiceClient is the implementation of QuoteServiceClient.
type quoteServiceClient struct {
	baseURL              string
	httpClient           *http.Client
	contentType          string
	defaultHeaders       map[string]string
	discardUnknownFields bool
}

var _ QuoteServiceClient = (*quoteServiceClient)(nil)

// QuoteServiceClientOption configures a QuoteService client.
type QuoteServiceClientOption func(*quoteServiceClient)

// WithQuoteServiceHTTPClient sets the HTTP client to use for requests.
func WithQuoteServiceHTTPClient(client *http.Client) QuoteServiceClientOption {
	return func(c *quoteServiceClient) {
		c.httpClient = client
	}
}

// WithQuoteServiceContentType sets the default content type for requests.
// Use ContentTypeJSON or ContentTypeProto.
func WithQuoteServiceContentType(contentType string) QuoteServiceClientOption {
	return func(c *quoteServiceClient) {
		c.contentType = contentType
	}
}

// WithQuoteServiceDefaultHeader sets a default header to include in all requests.
func WithQuoteServiceDefaultHeader(key, value string) QuoteServiceClientOption {
	return func(c *quoteServiceClient) {
		if c.defaultHeaders == nil {
			c.defaultHeaders = make(map[string]string)
		}
		c.defaultHeaders[key] = value
	}
}

// WithQuoteServiceDiscardUnknownFields sets whether to discard unknown fields in JSON responses.
// When true, unknown fields are silently ignored instead of causing unmarshal errors.
func WithQuoteServiceDiscardUnknownFields(discard bool) QuoteServiceClientOption {
	return func(c *quoteServiceClient) {
		c.discardUnknownFields = discard
	}
}

// QuoteServiceCallOption configures a single RPC call.
type QuoteServiceCallOption func(*quoteServiceCallOptions)

// quoteServiceCallOptions holds options for a single RPC call.
type quoteServiceCallOptions struct {
	headers              map[string]string
	contentType          string
	discardUnknownFields *bool
}

// WithQuoteServiceHeader adds a header to a single request.
func WithQuoteServiceHeader(key, value string) QuoteServiceCallOption {
	return func(o *quoteServiceCallOptions) {
		if o.headers == nil {
			o.headers = make(map[string]string)
		}
		o.headers[key] = value
	}
}

// WithQuoteServiceCallContentType sets the content type for a single request.
func WithQuoteServiceCallContentType(contentType string) QuoteServiceCallOption {
	return func(o *quoteServiceCallOptions) {
		o.contentType = contentType
	}
}

// WithQuoteServiceCallDiscardUnknownFields sets whether to discard unknown fields for a single request.
// Overrides the client-level setting from WithQuoteServiceDiscardUnknownFields.
func WithQuoteServiceCallDiscardUnknownFields(discard bool) QuoteServiceCallOption {
	return func(o *quoteServiceCallOptions) {
		o.discardUnknownFields = &discard
	}
}

// NewQuoteServiceClient creates a new QuoteService client.
func NewQuoteServiceClient(baseURL string, opts ...QuoteServiceClientOption) QuoteServiceClient {
	c := &quoteServiceClient{
		baseURL:        strings.TrimSuffix(baseURL, "/"),
		httpClient:     http.DefaultClient,
		contentType:    ContentTypeJSON,
		defaultHeaders: make(map[string]string),
	}

	for _, opt := range opts {
		opt(c)
	}

	return c
}

// GetQuote calls the GetQuote RPC.
func (c *quoteServiceClient) GetQuote(ctx context.Context, req *GetQuoteRequest, opts ...QuoteServiceCallOption) (*QuoteResponse, error) {
	callOpts := &quoteServiceCallOptions{}
	for _, opt := range opts {
		opt(callOpts)
	}

	// Build URL
	path := "/api/v1/quotes/{symbol}"
	path = strings.Replace(path, "{symbol}", url.PathEscape(fmt.Sprint(req.Symbol)), 1)
	reqURL := c.baseURL + path

	contentType := c.contentType
	if callOpts.contentType != "" {
		contentType = callOpts.contentType
	}

	// Create HTTP request
	httpReq, err := http.NewRequestWithContext(ctx, "GET", reqURL, nil)
	if err != nil {
		return nil, fmt.Errorf("failed to create request: %w", err)
	}

	// Set headers
	httpReq.Header.Set("Content-Type", contentType)
	for k, v := range c.defaultHeaders {
		httpReq.Header.Set(k, v)
	}
	for k, v := range callOpts.headers {
		httpReq.Header.Set(k, v)
	}

	// Execute request
	resp, err := c.httpClient.Do(httpReq)
	if err != nil {
		return nil, fmt.Errorf("failed to execute request: %w", err)
	}
	defer resp.Body.Close()

	// Read response body
	respBody, err := io.ReadAll(resp.Body)
	if err != nil {
		return nil, fmt.Errorf("failed to read response body: %w", err)
	}

	// Check for error status codes
	if resp.StatusCode >= 400 {
		return nil, c.handleErrorResponse(resp.StatusCode, respBody, contentType)
	}

	// Resolve discardUnknownFields: per-call option overrides client default
	discardUnknown := c.discardUnknownFields
	if callOpts.discardUnknownFields != nil {
		discardUnknown = *callOpts.discardUnknownFields
	}

	// Unmarshal response
	result := &QuoteResponse{}
	if err := c.unmarshalResponse(respBody, result, contentType, discardUnknown); err != nil {
		return nil, fmt.Errorf("failed to unmarshal response: %w", err)
	}

	return result, nil
}

func (c *quoteServiceClient) marshalRequest(req proto.Message, contentType string) ([]byte, error) {
	switch contentType {
	case ContentTypeJSON:
		// Check for custom JSON marshaler (unwrap support)
		if marshaler, ok := req.(json.Marshaler); ok {
			return marshaler.MarshalJSON()
		}
		return protojson.Marshal(req)
	case ContentTypeProto:
		return proto.Marshal(req)
	default:
		return protojson.Marshal(req)
	}
}

func (c *quoteServiceClient) handleErrorResponse(statusCode int, body []byte, contentType string) error {
	// Try to parse as ValidationError first (for 400 errors)
	// Always use strict mode (false) for error parsing to avoid loose JSON
	// falsely matching ValidationError or Error types.
	if statusCode == http.StatusBadRequest {
		validationErr := &sebufhttp.ValidationError{}
		if unmarshalErr := c.unmarshalResponse(body, validationErr, contentType, false); unmarshalErr == nil {
			return validationErr
		}
	}

	// Try to parse as generic Error
	genericErr := &sebufhttp.Error{}
	if unmarshalErr := c.unmarshalResponse(body, genericErr, contentType, false); unmarshalErr == nil {
		return genericErr
	}

	// Fallback to raw error message
	return fmt.Errorf("request failed with status %d: %s", statusCode, string(body))
}

func (c *quoteServiceClient) unmarshalResponse(body []byte, msg proto.Message, contentType string, discardUnknown bool) error {
	if len(body) == 0 {
		return nil
	}

	switch contentType {
	case ContentTypeJSON:
		// Check for custom JSON unmarshaler (unwrap support)
		if unmarshaler, ok := msg.(json.Unmarshaler); ok {
			return unmarshaler.UnmarshalJSON(body)
		}
		if discardUnknown {
			opts := protojson.UnmarshalOptions{DiscardUnknown: true}
			return opts.Unmarshal(body, msg)
		}
		return protojson.Unmarshal(body, msg)
	case ContentTypeProto:
		return proto.Unmarshal(body, msg)
	default:
		if discardUnknown {
			opts := protojson.UnmarshalOptions{DiscardUnknown: true}
			return opts.Unmarshal(body, msg)
		}
		return protojson.Unmarshal(body, msg)
	}
}
