// Code generated by sebuf. DO NOT EDIT.
// source: enum_encoding.proto

export interface GetEnumTestRequest {
  id: string;
}

export interface EnumEncodingTest {
  status: Status;
  priorityAsNumber: number;
  priorityAsString: Priority;
  defaultPriority: Priority;
  statusList: Status[];
  numberPriorityList: number[];
  optionalStatus?: Status;
  statusMap: { [key: string]: Status };
}

export type Priority = "PRIORITY_LOW" | "PRIORITY_MEDIUM" | "PRIORITY_HIGH";

export type Status = "unknown" | "active" | "inactive";

