// Code generated by protoc-gen-ts-server. DO NOT EDIT.
// source: query_params.proto

export interface SearchWithTypesRequest {
  query: string;
  limit: number;
  offset: string;
  active: boolean;
  minScore: number;
  maxScore: number;
  page: number;
  timestamp: string;
}

export interface SearchResponse {
  results: string[];
  total: number;
}

export interface SearchRequiredRequest {
  query: string;
  page: number;
  pageSize: number;
}

export interface SearchCustomNamesRequest {
  searchTerm: string;
  resultsPerPage: number;
  pageNumber: number;
  sortField: string;
  descendingOrder: boolean;
}

export interface GetWithFiltersRequest {
  resourceId: string;
  filter: string;
  limit: number;
}

export interface FieldViolation {
  field: string;
  description: string;
}

export class ValidationError extends Error {
  violations: FieldViolation[];

  constructor(violations: FieldViolation[]) {
    super("Validation failed");
    this.name = "ValidationError";
    this.violations = violations;
  }
}

export class ApiError extends Error {
  statusCode: number;
  body: string;

  constructor(statusCode: number, message: string, body: string) {
    super(message);
    this.name = "ApiError";
    this.statusCode = statusCode;
    this.body = body;
  }
}

export interface ServerContext {
  request: Request;
  pathParams: Record<string, string>;
  headers: Record<string, string>;
}

export interface ServerOptions {
  onError?: (error: unknown, req: Request) => Response | Promise<Response>;
  validateRequest?: (methodName: string, body: unknown) => FieldViolation[] | undefined;
}

export interface RouteDescriptor {
  method: string;
  path: string;
  handler: (req: Request) => Promise<Response>;
}

export interface QueryParamServiceHandler {
  searchWithTypes(ctx: ServerContext, req: SearchWithTypesRequest): Promise<SearchResponse>;
  searchRequired(ctx: ServerContext, req: SearchRequiredRequest): Promise<SearchResponse>;
  searchCustomNames(ctx: ServerContext, req: SearchCustomNamesRequest): Promise<SearchResponse>;
  getWithFilters(ctx: ServerContext, req: GetWithFiltersRequest): Promise<SearchResponse>;
}

export function createQueryParamServiceRoutes(
  handler: QueryParamServiceHandler,
  options?: ServerOptions,
): RouteDescriptor[] {
  return [
    {
      method: "GET",
      path: "/api/search/typed",
      handler: async (req: Request): Promise<Response> => {
        try {
          const pathParams: Record<string, string> = {};
          const url = new URL(req.url, "http://localhost");
          const params = url.searchParams;
          const body: SearchWithTypesRequest = {
            query: params.get("q") ?? "",
            limit: Number(params.get("limit") ?? "0"),
            offset: params.get("offset") ?? "",
            active: params.get("active") === "true",
            minScore: Number(params.get("min_score") ?? "0"),
            maxScore: Number(params.get("max_score") ?? "0"),
            page: Number(params.get("page") ?? "0"),
            timestamp: params.get("ts") ?? "",
          };
          if (options?.validateRequest) {
            const bodyViolations = options.validateRequest("searchWithTypes", body);
            if (bodyViolations) {
              throw new ValidationError(bodyViolations);
            }
          }

          const ctx: ServerContext = {
            request: req,
            pathParams,
            headers: Object.fromEntries(req.headers.entries()),
          };

          const result = await handler.searchWithTypes(ctx, body);
          return new Response(JSON.stringify(result as SearchResponse), {
            status: 200,
            headers: { "Content-Type": "application/json" },
          });
        } catch (err: unknown) {
          if (err instanceof ValidationError) {
            return new Response(JSON.stringify({ violations: err.violations }), {
              status: 400,
              headers: { "Content-Type": "application/json" },
            });
          }
          if (options?.onError) {
            return options.onError(err, req);
          }
          const message = err instanceof Error ? err.message : String(err);
          return new Response(JSON.stringify({ message }), {
            status: 500,
            headers: { "Content-Type": "application/json" },
          });
        }
      },
    },
    {
      method: "GET",
      path: "/api/search/required",
      handler: async (req: Request): Promise<Response> => {
        try {
          const pathParams: Record<string, string> = {};
          const url = new URL(req.url, "http://localhost");
          const params = url.searchParams;
          const body: SearchRequiredRequest = {
            query: params.get("q") ?? "",
            page: Number(params.get("page") ?? "0"),
            pageSize: Number(params.get("page_size") ?? "0"),
          };
          if (options?.validateRequest) {
            const bodyViolations = options.validateRequest("searchRequired", body);
            if (bodyViolations) {
              throw new ValidationError(bodyViolations);
            }
          }

          const ctx: ServerContext = {
            request: req,
            pathParams,
            headers: Object.fromEntries(req.headers.entries()),
          };

          const result = await handler.searchRequired(ctx, body);
          return new Response(JSON.stringify(result as SearchResponse), {
            status: 200,
            headers: { "Content-Type": "application/json" },
          });
        } catch (err: unknown) {
          if (err instanceof ValidationError) {
            return new Response(JSON.stringify({ violations: err.violations }), {
              status: 400,
              headers: { "Content-Type": "application/json" },
            });
          }
          if (options?.onError) {
            return options.onError(err, req);
          }
          const message = err instanceof Error ? err.message : String(err);
          return new Response(JSON.stringify({ message }), {
            status: 500,
            headers: { "Content-Type": "application/json" },
          });
        }
      },
    },
    {
      method: "GET",
      path: "/api/search/custom",
      handler: async (req: Request): Promise<Response> => {
        try {
          const pathParams: Record<string, string> = {};
          const url = new URL(req.url, "http://localhost");
          const params = url.searchParams;
          const body: SearchCustomNamesRequest = {
            searchTerm: params.get("q") ?? "",
            resultsPerPage: Number(params.get("limit") ?? "0"),
            pageNumber: Number(params.get("page") ?? "0"),
            sortField: params.get("sort") ?? "",
            descendingOrder: params.get("desc") === "true",
          };
          if (options?.validateRequest) {
            const bodyViolations = options.validateRequest("searchCustomNames", body);
            if (bodyViolations) {
              throw new ValidationError(bodyViolations);
            }
          }

          const ctx: ServerContext = {
            request: req,
            pathParams,
            headers: Object.fromEntries(req.headers.entries()),
          };

          const result = await handler.searchCustomNames(ctx, body);
          return new Response(JSON.stringify(result as SearchResponse), {
            status: 200,
            headers: { "Content-Type": "application/json" },
          });
        } catch (err: unknown) {
          if (err instanceof ValidationError) {
            return new Response(JSON.stringify({ violations: err.violations }), {
              status: 400,
              headers: { "Content-Type": "application/json" },
            });
          }
          if (options?.onError) {
            return options.onError(err, req);
          }
          const message = err instanceof Error ? err.message : String(err);
          return new Response(JSON.stringify({ message }), {
            status: 500,
            headers: { "Content-Type": "application/json" },
          });
        }
      },
    },
    {
      method: "GET",
      path: "/api/resources/{resource_id}/items",
      handler: async (req: Request): Promise<Response> => {
        try {
          const pathParams: Record<string, string> = {};
          const url = new URL(req.url, "http://localhost");
          const pathSegments = url.pathname.split("/");
          pathParams["resource_id"] = decodeURIComponent(pathSegments[3] ?? "");

          const url = new URL(req.url, "http://localhost");
          const params = url.searchParams;
          const body: GetWithFiltersRequest = {
            filter: params.get("filter") ?? "",
            limit: Number(params.get("limit") ?? "0"),
          };
          if (options?.validateRequest) {
            const bodyViolations = options.validateRequest("getWithFilters", body);
            if (bodyViolations) {
              throw new ValidationError(bodyViolations);
            }
          }

          const ctx: ServerContext = {
            request: req,
            pathParams,
            headers: Object.fromEntries(req.headers.entries()),
          };

          const result = await handler.getWithFilters(ctx, body);
          return new Response(JSON.stringify(result as SearchResponse), {
            status: 200,
            headers: { "Content-Type": "application/json" },
          });
        } catch (err: unknown) {
          if (err instanceof ValidationError) {
            return new Response(JSON.stringify({ violations: err.violations }), {
              status: 400,
              headers: { "Content-Type": "application/json" },
            });
          }
          if (options?.onError) {
            return options.onError(err, req);
          }
          const message = err instanceof Error ? err.message : String(err);
          return new Response(JSON.stringify({ message }), {
            status: 500,
            headers: { "Content-Type": "application/json" },
          });
        }
      },
    },
  ];
}

