// Code generated by protoc-gen-ts-server. DO NOT EDIT.
// source: structpb_types.proto

import { FieldViolation, ValidationError } from "./errors.js";
import type { GetStructPBTypesRequest, StructPBTypes } from "./structpb_types.js";

export interface ServerContext {
  request: Request;
  pathParams: Record<string, string>;
  headers: Record<string, string>;
}

export interface ServerOptions {
  onError?: (error: unknown, req: Request) => Response | Promise<Response>;
  validateRequest?: (methodName: string, body: unknown) => FieldViolation[] | undefined;
}

export interface RouteDescriptor {
  method: string;
  path: string;
  handler: (req: Request) => Promise<Response>;
}

export interface StructPBTypesServiceHandler {
  createStructPBTypes(ctx: ServerContext, req: StructPBTypes): Promise<StructPBTypes>;
  getStructPBTypes(ctx: ServerContext, req: GetStructPBTypesRequest): Promise<StructPBTypes>;
}

export function createStructPBTypesServiceRoutes(
  handler: StructPBTypesServiceHandler,
  options?: ServerOptions,
): RouteDescriptor[] {
  return [
    {
      method: "POST",
      path: "/api/v1/structpb-types",
      handler: async (req: Request): Promise<Response> => {
        try {
          const pathParams: Record<string, string> = {};
          const body = await req.json() as StructPBTypes;
          if (options?.validateRequest) {
            const bodyViolations = options.validateRequest("createStructPBTypes", body);
            if (bodyViolations) {
              throw new ValidationError(bodyViolations);
            }
          }

          const ctx: ServerContext = {
            request: req,
            pathParams,
            headers: Object.fromEntries(req.headers.entries()),
          };

          const result = await handler.createStructPBTypes(ctx, body);
          return new Response(JSON.stringify(result as StructPBTypes), {
            status: 200,
            headers: { "Content-Type": "application/json" },
          });
        } catch (err: unknown) {
          if (err instanceof ValidationError) {
            return new Response(JSON.stringify({ violations: err.violations }), {
              status: 400,
              headers: { "Content-Type": "application/json" },
            });
          }
          if (options?.onError) {
            return options.onError(err, req);
          }
          const message = err instanceof Error ? err.message : String(err);
          return new Response(JSON.stringify({ message }), {
            status: 500,
            headers: { "Content-Type": "application/json" },
          });
        }
      },
    },
    {
      method: "GET",
      path: "/api/v1/structpb-types/{id}",
      handler: async (req: Request): Promise<Response> => {
        try {
          const pathParams: Record<string, string> = {};
          const url = new URL(req.url, "http://localhost");
          const pathSegments = url.pathname.split("/");
          pathParams["id"] = decodeURIComponent(pathSegments[4] ?? "");

          const body: GetStructPBTypesRequest = {
            id: pathParams["id"],
          };

          const ctx: ServerContext = {
            request: req,
            pathParams,
            headers: Object.fromEntries(req.headers.entries()),
          };

          const result = await handler.getStructPBTypes(ctx, body);
          return new Response(JSON.stringify(result as StructPBTypes), {
            status: 200,
            headers: { "Content-Type": "application/json" },
          });
        } catch (err: unknown) {
          if (err instanceof ValidationError) {
            return new Response(JSON.stringify({ violations: err.violations }), {
              status: 400,
              headers: { "Content-Type": "application/json" },
            });
          }
          if (options?.onError) {
            return options.onError(err, req);
          }
          const message = err instanceof Error ? err.message : String(err);
          return new Response(JSON.stringify({ message }), {
            status: 500,
            headers: { "Content-Type": "application/json" },
          });
        }
      },
    },
  ];
}

