// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: proto/sebuf/krakend/krakend.proto

package krakend

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	descriptorpb "google.golang.org/protobuf/types/descriptorpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// GatewayConfig sets service-wide KrakenD defaults.
// Applied to a service via (sebuf.krakend.gateway_config).
type GatewayConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Backend host URLs (e.g., "http://backend:8080"). Required.
	// Must include scheme (http:// or https://).
	// Multiple hosts enable KrakenD load balancing.
	Host []string `protobuf:"bytes,1,rep,name=host,proto3" json:"host,omitempty"`
	// Default timeout for all endpoints in this service.
	// KrakenD duration format: "2s", "500ms", "1m".
	// Omit to use KrakenD's built-in default.
	Timeout       string `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GatewayConfig) Reset() {
	*x = GatewayConfig{}
	mi := &file_proto_sebuf_krakend_krakend_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GatewayConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GatewayConfig) ProtoMessage() {}

func (x *GatewayConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sebuf_krakend_krakend_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GatewayConfig.ProtoReflect.Descriptor instead.
func (*GatewayConfig) Descriptor() ([]byte, []int) {
	return file_proto_sebuf_krakend_krakend_proto_rawDescGZIP(), []int{0}
}

func (x *GatewayConfig) GetHost() []string {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *GatewayConfig) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

// EndpointConfig overrides service-level defaults for a specific RPC.
// Applied to an rpc method via (sebuf.krakend.endpoint_config).
type EndpointConfig struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Override backend host for this specific endpoint.
	Host []string `protobuf:"bytes,1,rep,name=host,proto3" json:"host,omitempty"`
	// Override timeout for this specific endpoint.
	Timeout       string `protobuf:"bytes,2,opt,name=timeout,proto3" json:"timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EndpointConfig) Reset() {
	*x = EndpointConfig{}
	mi := &file_proto_sebuf_krakend_krakend_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EndpointConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EndpointConfig) ProtoMessage() {}

func (x *EndpointConfig) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sebuf_krakend_krakend_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EndpointConfig.ProtoReflect.Descriptor instead.
func (*EndpointConfig) Descriptor() ([]byte, []int) {
	return file_proto_sebuf_krakend_krakend_proto_rawDescGZIP(), []int{1}
}

func (x *EndpointConfig) GetHost() []string {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *EndpointConfig) GetTimeout() string {
	if x != nil {
		return x.Timeout
	}
	return ""
}

var file_proto_sebuf_krakend_krakend_proto_extTypes = []protoimpl.ExtensionInfo{
	{
		ExtendedType:  (*descriptorpb.ServiceOptions)(nil),
		ExtensionType: (*GatewayConfig)(nil),
		Field:         51001,
		Name:          "sebuf.krakend.gateway_config",
		Tag:           "bytes,51001,opt,name=gateway_config",
		Filename:      "proto/sebuf/krakend/krakend.proto",
	},
	{
		ExtendedType:  (*descriptorpb.MethodOptions)(nil),
		ExtensionType: (*EndpointConfig)(nil),
		Field:         51002,
		Name:          "sebuf.krakend.endpoint_config",
		Tag:           "bytes,51002,opt,name=endpoint_config",
		Filename:      "proto/sebuf/krakend/krakend.proto",
	},
}

// Extension fields to descriptorpb.ServiceOptions.
var (
	// optional sebuf.krakend.GatewayConfig gateway_config = 51001;
	E_GatewayConfig = &file_proto_sebuf_krakend_krakend_proto_extTypes[0]
)

// Extension fields to descriptorpb.MethodOptions.
var (
	// optional sebuf.krakend.EndpointConfig endpoint_config = 51002;
	E_EndpointConfig = &file_proto_sebuf_krakend_krakend_proto_extTypes[1]
)

var File_proto_sebuf_krakend_krakend_proto protoreflect.FileDescriptor

const file_proto_sebuf_krakend_krakend_proto_rawDesc = "" +
	"\n" +
	"!proto/sebuf/krakend/krakend.proto\x12\rsebuf.krakend\x1a google/protobuf/descriptor.proto\"=\n" +
	"\rGatewayConfig\x12\x12\n" +
	"\x04host\x18\x01 \x03(\tR\x04host\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\tR\atimeout\">\n" +
	"\x0eEndpointConfig\x12\x12\n" +
	"\x04host\x18\x01 \x03(\tR\x04host\x12\x18\n" +
	"\atimeout\x18\x02 \x01(\tR\atimeout:f\n" +
	"\x0egateway_config\x12\x1f.google.protobuf.ServiceOptions\x18\xb9\x8e\x03 \x01(\v2\x1c.sebuf.krakend.GatewayConfigR\rgatewayConfig:h\n" +
	"\x0fendpoint_config\x12\x1e.google.protobuf.MethodOptions\x18\xba\x8e\x03 \x01(\v2\x1d.sebuf.krakend.EndpointConfigR\x0eendpointConfigB1Z/github.com/SebastienMelki/sebuf/krakend;krakendb\x06proto3"

var (
	file_proto_sebuf_krakend_krakend_proto_rawDescOnce sync.Once
	file_proto_sebuf_krakend_krakend_proto_rawDescData []byte
)

func file_proto_sebuf_krakend_krakend_proto_rawDescGZIP() []byte {
	file_proto_sebuf_krakend_krakend_proto_rawDescOnce.Do(func() {
		file_proto_sebuf_krakend_krakend_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sebuf_krakend_krakend_proto_rawDesc), len(file_proto_sebuf_krakend_krakend_proto_rawDesc)))
	})
	return file_proto_sebuf_krakend_krakend_proto_rawDescData
}

var file_proto_sebuf_krakend_krakend_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_sebuf_krakend_krakend_proto_goTypes = []any{
	(*GatewayConfig)(nil),               // 0: sebuf.krakend.GatewayConfig
	(*EndpointConfig)(nil),              // 1: sebuf.krakend.EndpointConfig
	(*descriptorpb.ServiceOptions)(nil), // 2: google.protobuf.ServiceOptions
	(*descriptorpb.MethodOptions)(nil),  // 3: google.protobuf.MethodOptions
}
var file_proto_sebuf_krakend_krakend_proto_depIdxs = []int32{
	2, // 0: sebuf.krakend.gateway_config:extendee -> google.protobuf.ServiceOptions
	3, // 1: sebuf.krakend.endpoint_config:extendee -> google.protobuf.MethodOptions
	0, // 2: sebuf.krakend.gateway_config:type_name -> sebuf.krakend.GatewayConfig
	1, // 3: sebuf.krakend.endpoint_config:type_name -> sebuf.krakend.EndpointConfig
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	2, // [2:4] is the sub-list for extension type_name
	0, // [0:2] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sebuf_krakend_krakend_proto_init() }
func file_proto_sebuf_krakend_krakend_proto_init() {
	if File_proto_sebuf_krakend_krakend_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sebuf_krakend_krakend_proto_rawDesc), len(file_proto_sebuf_krakend_krakend_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 2,
			NumServices:   0,
		},
		GoTypes:           file_proto_sebuf_krakend_krakend_proto_goTypes,
		DependencyIndexes: file_proto_sebuf_krakend_krakend_proto_depIdxs,
		MessageInfos:      file_proto_sebuf_krakend_krakend_proto_msgTypes,
		ExtensionInfos:    file_proto_sebuf_krakend_krakend_proto_extTypes,
	}.Build()
	File_proto_sebuf_krakend_krakend_proto = out.File
	file_proto_sebuf_krakend_krakend_proto_goTypes = nil
	file_proto_sebuf_krakend_krakend_proto_depIdxs = nil
}
