// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: proto/stock_service.proto

package stockdatav1

import (
	"context"

	sebufhttp "github.com/SebastienMelki/sebuf/http"
)

// StockDataServiceServer is the server API for StockDataService service.
type StockDataServiceServer interface {
	GetStockBars(context.Context, *GetStockBarsRequest) (*GetStockBarsResponse, error)
}

// RegisterStockDataServiceServer registers the HTTP handlers for service StockDataService to the given mux.
func RegisterStockDataServiceServer(server StockDataServiceServer, opts ...ServerOption) error {
	config := getConfiguration(opts...)

	serviceHeaders := getStockDataServiceHeaders()

	methodHeaders := getGetStockBarsHeaders()
	getStockBarsHandler := BindingMiddleware[GetStockBarsRequest](
		genericHandler(server.GetStockBars, config.errorHandler), serviceHeaders, methodHeaders,
		getStockBarsPathParams, getStockBarsQueryParams,
		"GET", config.errorHandler,
	)

	config.mux.Handle("GET /v1/stocks/bars", getStockBarsHandler)

	return nil
}

// getStockDataServiceHeaders returns the service-level required headers for StockDataService
func getStockDataServiceHeaders() []*sebufhttp.Header {
	return []*sebufhttp.Header{
		{
			Name:        "X-API-Key",
			Description: "API key for authentication",
			Type:        "string",
			Required:    true,
			Format:      "",
			Example:     "sk_live_xxxxx",
			Deprecated:  false,
		},
	}
}

// getGetStockBarsHeaders returns the method-level required headers for GetStockBars
func getGetStockBarsHeaders() []*sebufhttp.Header {
	return nil
}

// getStockBarsPathParams contains path parameter configuration for GetStockBars
var getStockBarsPathParams = []PathParamConfig{}

// getStockBarsQueryParams contains query parameter configuration for GetStockBars
var getStockBarsQueryParams = []QueryParamConfig{
	{QueryName: "symbols", FieldName: "symbols", Required: false},
	{QueryName: "timeframe", FieldName: "timeframe", Required: false},
	{QueryName: "start", FieldName: "start", Required: false},
	{QueryName: "end", FieldName: "end", Required: false},
	{QueryName: "limit", FieldName: "limit", Required: false},
}
