// Example: Unwrap annotation in same package, different file
// This file defines the wrapper message with the unwrap annotation

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: proto/stock_bar.proto

package stockdatav1

import (
	_ "github.com/SebastienMelki/sebuf/http"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// StockBar represents a stock OHLCV bar data point.
type StockBar struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Timestamp in RFC 3339 format.
	T string `protobuf:"bytes,1,opt,name=t,proto3" json:"t,omitempty"`
	// Open price.
	O float64 `protobuf:"fixed64,2,opt,name=o,proto3" json:"o,omitempty"`
	// High price.
	H float64 `protobuf:"fixed64,3,opt,name=h,proto3" json:"h,omitempty"`
	// Low price.
	L float64 `protobuf:"fixed64,4,opt,name=l,proto3" json:"l,omitempty"`
	// Close price.
	C float64 `protobuf:"fixed64,5,opt,name=c,proto3" json:"c,omitempty"`
	// Volume.
	V             int64 `protobuf:"varint,6,opt,name=v,proto3" json:"v,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockBar) Reset() {
	*x = StockBar{}
	mi := &file_proto_stock_bar_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockBar) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockBar) ProtoMessage() {}

func (x *StockBar) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stock_bar_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockBar.ProtoReflect.Descriptor instead.
func (*StockBar) Descriptor() ([]byte, []int) {
	return file_proto_stock_bar_proto_rawDescGZIP(), []int{0}
}

func (x *StockBar) GetT() string {
	if x != nil {
		return x.T
	}
	return ""
}

func (x *StockBar) GetO() float64 {
	if x != nil {
		return x.O
	}
	return 0
}

func (x *StockBar) GetH() float64 {
	if x != nil {
		return x.H
	}
	return 0
}

func (x *StockBar) GetL() float64 {
	if x != nil {
		return x.L
	}
	return 0
}

func (x *StockBar) GetC() float64 {
	if x != nil {
		return x.C
	}
	return 0
}

func (x *StockBar) GetV() int64 {
	if x != nil {
		return x.V
	}
	return 0
}

// StockBarsList is a wrapper for a list of bars that will be unwrapped in JSON.
// This enables map values to serialize as arrays instead of nested objects.
//
// IMPORTANT: This message is in a DIFFERENT FILE but SAME PACKAGE as the service
// that uses it. This tests the same-package-different-file unwrap resolution.
type StockBarsList struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The bars field is marked for unwrapping - when this message is a map value,
	// the JSON will collapse to just the array: {"AAPL": [...]} instead of {"AAPL": {"bars": [...]}}
	Bars          []*StockBar `protobuf:"bytes,1,rep,name=bars,proto3" json:"bars,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockBarsList) Reset() {
	*x = StockBarsList{}
	mi := &file_proto_stock_bar_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockBarsList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockBarsList) ProtoMessage() {}

func (x *StockBarsList) ProtoReflect() protoreflect.Message {
	mi := &file_proto_stock_bar_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockBarsList.ProtoReflect.Descriptor instead.
func (*StockBarsList) Descriptor() ([]byte, []int) {
	return file_proto_stock_bar_proto_rawDescGZIP(), []int{1}
}

func (x *StockBarsList) GetBars() []*StockBar {
	if x != nil {
		return x.Bars
	}
	return nil
}

var File_proto_stock_bar_proto protoreflect.FileDescriptor

const file_proto_stock_bar_proto_rawDesc = "" +
	"\n" +
	"\x15proto/stock_bar.proto\x12\fstockdata.v1\x1a\x1csebuf/http/annotations.proto\"\xc1\x01\n" +
	"\bStockBar\x12(\n" +
	"\x01t\x18\x01 \x01(\tB\x1a\xba\xb5\x18\x16\n" +
	"\x142025-12-15T15:05:00ZR\x01t\x12\x1a\n" +
	"\x01o\x18\x02 \x01(\x01B\f\xba\xb5\x18\b\n" +
	"\x06143.08R\x01o\x12\x1a\n" +
	"\x01h\x18\x03 \x01(\x01B\f\xba\xb5\x18\b\n" +
	"\x06145.00R\x01h\x12\x1a\n" +
	"\x01l\x18\x04 \x01(\x01B\f\xba\xb5\x18\b\n" +
	"\x06142.50R\x01l\x12\x1a\n" +
	"\x01c\x18\x05 \x01(\x01B\f\xba\xb5\x18\b\n" +
	"\x06144.25R\x01c\x12\x1b\n" +
	"\x01v\x18\x06 \x01(\x03B\r\xba\xb5\x18\t\n" +
	"\a1000000R\x01v\"A\n" +
	"\rStockBarsList\x120\n" +
	"\x04bars\x18\x01 \x03(\v2\x16.stockdata.v1.StockBarB\x04ȵ\x18\x01R\x04barsB\xce\x01\n" +
	"\x10com.stockdata.v1B\rStockBarProtoP\x01ZZgithub.com/SebastienMelki/sebuf/examples/market-data-unwrap-same-pkg/api/proto;stockdatav1\xa2\x02\x03SXX\xaa\x02\fStockdata.V1\xca\x02\fStockdata\\V1\xe2\x02\x18Stockdata\\V1\\GPBMetadata\xea\x02\rStockdata::V1b\x06proto3"

var (
	file_proto_stock_bar_proto_rawDescOnce sync.Once
	file_proto_stock_bar_proto_rawDescData []byte
)

func file_proto_stock_bar_proto_rawDescGZIP() []byte {
	file_proto_stock_bar_proto_rawDescOnce.Do(func() {
		file_proto_stock_bar_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_stock_bar_proto_rawDesc), len(file_proto_stock_bar_proto_rawDesc)))
	})
	return file_proto_stock_bar_proto_rawDescData
}

var file_proto_stock_bar_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_stock_bar_proto_goTypes = []any{
	(*StockBar)(nil),      // 0: stockdata.v1.StockBar
	(*StockBarsList)(nil), // 1: stockdata.v1.StockBarsList
}
var file_proto_stock_bar_proto_depIdxs = []int32{
	0, // 0: stockdata.v1.StockBarsList.bars:type_name -> stockdata.v1.StockBar
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_stock_bar_proto_init() }
func file_proto_stock_bar_proto_init() {
	if File_proto_stock_bar_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_stock_bar_proto_rawDesc), len(file_proto_stock_bar_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_proto_stock_bar_proto_goTypes,
		DependencyIndexes: file_proto_stock_bar_proto_depIdxs,
		MessageInfos:      file_proto_stock_bar_proto_msgTypes,
	}.Build()
	File_proto_stock_bar_proto = out.File
	file_proto_stock_bar_proto_goTypes = nil
	file_proto_stock_bar_proto_depIdxs = nil
}
