package pyclientgen

// writeTransport emits the HttpTransport Protocol and the stdlib UrllibTransport default.
// The Protocol uses duck typing so users can pass requests/httpx/aiohttp adapters
// without inheriting from any sebuf base class.
func writeTransport(p printer) {
	p("@dataclass")
	p("class HttpResponse:")
	p(`    """Minimal HTTP response shape returned by every HttpTransport."""`)
	p("    status: int")
	p("    headers: Mapping[str, str]")
	p("    body: bytes")
	p("")
	p("")
	p("class HttpTransport(Protocol):")
	p(`    """Duck-typed HTTP transport. Implement this to plug in requests/httpx/aiohttp."""`)
	p("    def request(")
	p("        self,")
	p("        method: str,")
	p("        url: str,")
	p("        headers: Mapping[str, str],")
	p("        body: Optional[bytes],")
	p("        timeout: Optional[float],")
	p("    ) -> HttpResponse: ...")
	p("")
	p("")
	p("class UrllibTransport:")
	p(`    """Default transport built on the Python standard library."""`)
	p("    def request(")
	p("        self,")
	p("        method: str,")
	p("        url: str,")
	p("        headers: Mapping[str, str],")
	p("        body: Optional[bytes],")
	p("        timeout: Optional[float],")
	p("    ) -> HttpResponse:")
	p("        req = urllib.request.Request(url=url, method=method, data=body)")
	p("        for key, value in headers.items():")
	p("            req.add_header(key, value)")
	p("        try:")
	p("            with urllib.request.urlopen(req, timeout=timeout) as resp:")
	p("                return HttpResponse(")
	p("                    status=resp.status,")
	p("                    headers={k: v for k, v in resp.headers.items()},")
	p("                    body=resp.read(),")
	p("                )")
	p("        except urllib.error.HTTPError as exc:")
	p("            return HttpResponse(")
	p("                status=exc.code,")
	p("                headers={k: v for k, v in exc.headers.items()} if exc.headers else {},")
	p("                body=exc.read() if hasattr(exc, \"read\") else b\"\",")
	p("            )")
	p("")
	p("")
}
