# Code generated by protoc-gen-py-client. DO NOT EDIT.
# source: sse.proto

from __future__ import annotations

import base64
import binascii
import json
import urllib.error
import urllib.parse
import urllib.request
from dataclasses import dataclass, field
from datetime import datetime, timezone
from enum import IntEnum
from typing import Any, AsyncIterator, Iterator, Mapping, Optional, Protocol, Sequence, Union

@dataclass
class HttpResponse:
    """Minimal HTTP response shape returned by every HttpTransport."""
    status: int
    headers: Mapping[str, str]
    body: bytes


class HttpTransport(Protocol):
    """Duck-typed HTTP transport. Implement this to plug in requests/httpx/aiohttp."""
    def request(
        self,
        method: str,
        url: str,
        headers: Mapping[str, str],
        body: Optional[bytes],
        timeout: Optional[float],
    ) -> HttpResponse: ...


class UrllibTransport:
    """Default transport built on the Python standard library."""
    def request(
        self,
        method: str,
        url: str,
        headers: Mapping[str, str],
        body: Optional[bytes],
        timeout: Optional[float],
    ) -> HttpResponse:
        req = urllib.request.Request(url=url, method=method, data=body)
        for key, value in headers.items():
            req.add_header(key, value)
        try:
            with urllib.request.urlopen(req, timeout=timeout) as resp:
                return HttpResponse(
                    status=resp.status,
                    headers={k: v for k, v in resp.headers.items()},
                    body=resp.read(),
                )
        except urllib.error.HTTPError as exc:
            return HttpResponse(
                status=exc.code,
                headers={k: v for k, v in exc.headers.items()} if exc.headers else {},
                body=exc.read() if hasattr(exc, "read") else b"",
            )


@dataclass
class FieldViolation:
    """Single validation violation, matching sebuf.http.FieldViolation."""
    field: str
    description: str = ""


class ApiError(Exception):
    """Base exception for any non-2xx HTTP response."""
    def __init__(
        self,
        status: int,
        body: bytes,
        headers: Optional[Mapping[str, str]] = None,
    ) -> None:
        self.status = status
        self.body = body
        self.headers = headers or {}
        super().__init__(f"HTTP {status}")


class ValidationError(ApiError):
    """Raised on HTTP 400 when the server returns sebuf.http.ValidationError JSON."""
    def __init__(
        self,
        status: int,
        body: bytes,
        headers: Optional[Mapping[str, str]] = None,
        violations: Optional[Sequence[FieldViolation]] = None,
    ) -> None:
        super().__init__(status, body, headers)
        self.violations: list[FieldViolation] = list(violations or [])


_ERROR_CLASSES: list[tuple[type[ApiError], set[str]]] = [
]


@dataclass
class Event:
    """Generated from proto message test.sse.Event."""
    id: str = ""
    type: str = ""
    payload: str = ""
    timestamp: str = "0"

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting sebuf JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["id"] = self.id
        d["type"] = self.type
        d["payload"] = self.payload
        d["timestamp"] = str(self.timestamp)
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "Event":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "id" in data and data["id"] is not None:
            kwargs["id"] = str(data["id"])
        if "type" in data and data["type"] is not None:
            kwargs["type"] = str(data["type"])
        if "payload" in data and data["payload"] is not None:
            kwargs["payload"] = str(data["payload"])
        if "timestamp" in data and data["timestamp"] is not None:
            kwargs["timestamp"] = str(data["timestamp"])
        return cls(**kwargs)

@dataclass
class GetStatusRequest:
    """Generated from proto message test.sse.GetStatusRequest."""

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting sebuf JSON mapping annotations."""
        d: dict[str, Any] = {}
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "GetStatusRequest":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        return cls(**kwargs)

@dataclass
class ResourceEvent:
    """Generated from proto message test.sse.ResourceEvent."""
    resource_id: str = ""
    event_type: str = ""
    data: str = ""

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting sebuf JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["resourceId"] = self.resource_id
        d["eventType"] = self.event_type
        d["data"] = self.data
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "ResourceEvent":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "resourceId" in data and data["resourceId"] is not None:
            kwargs["resource_id"] = str(data["resourceId"])
        if "eventType" in data and data["eventType"] is not None:
            kwargs["event_type"] = str(data["eventType"])
        if "data" in data and data["data"] is not None:
            kwargs["data"] = str(data["data"])
        return cls(**kwargs)

@dataclass
class StatusResponse:
    """Generated from proto message test.sse.StatusResponse."""
    status: str = ""
    uptime_seconds: str = "0"

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting sebuf JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["status"] = self.status
        d["uptimeSeconds"] = str(self.uptime_seconds)
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "StatusResponse":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "status" in data and data["status"] is not None:
            kwargs["status"] = str(data["status"])
        if "uptimeSeconds" in data and data["uptimeSeconds"] is not None:
            kwargs["uptime_seconds"] = str(data["uptimeSeconds"])
        return cls(**kwargs)

@dataclass
class StreamEventsRequest:
    """Generated from proto message test.sse.StreamEventsRequest."""

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting sebuf JSON mapping annotations."""
        d: dict[str, Any] = {}
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "StreamEventsRequest":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        return cls(**kwargs)

@dataclass
class StreamFilteredEventsRequest:
    """Generated from proto message test.sse.StreamFilteredEventsRequest."""
    event_type: str = ""
    limit: int = 0

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting sebuf JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["eventType"] = self.event_type
        d["limit"] = self.limit
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "StreamFilteredEventsRequest":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "eventType" in data and data["eventType"] is not None:
            kwargs["event_type"] = str(data["eventType"])
        if "limit" in data and data["limit"] is not None:
            kwargs["limit"] = int(data["limit"])
        return cls(**kwargs)

@dataclass
class StreamResourceEventsRequest:
    """Generated from proto message test.sse.StreamResourceEventsRequest."""
    resource_id: str = ""

    def to_dict(self) -> Any:
        """Serialize to a JSON-ready dict respecting sebuf JSON mapping annotations."""
        d: dict[str, Any] = {}
        d["resourceId"] = self.resource_id
        return d

    @classmethod
    def from_dict(cls, data: Any) -> "StreamResourceEventsRequest":
        """Deserialize from a JSON-decoded dict (or value, for root-unwrapped messages)."""
        if data is None:
            return cls()
        kwargs: dict[str, Any] = {}
        if "resourceId" in data and data["resourceId"] is not None:
            kwargs["resource_id"] = str(data["resourceId"])
        return cls(**kwargs)

@dataclass
class SSEServiceClientOptions:
    """Construct-time options for SSEServiceClient."""
    transport: Optional[HttpTransport] = None
    default_headers: Optional[Mapping[str, str]] = None
    timeout: Optional[float] = None
    content_type: str = "application/json"


@dataclass
class SSEServiceCallOptions:
    """Per-call options for SSEServiceClient methods."""
    headers: Optional[Mapping[str, str]] = None
    timeout: Optional[float] = None
    content_type: Optional[str] = None


class SSEServiceClient:
    """Generated client for test.sse.SSEService."""
    def __init__(
        self,
        base_url: str,
        options: Optional[SSEServiceClientOptions] = None,
    ) -> None:
        self._base_url = base_url.rstrip("/")
        opts = options or SSEServiceClientOptions()
        self._transport: HttpTransport = opts.transport or UrllibTransport()
        self._default_headers: dict[str, str] = dict(opts.default_headers or {})
        self._timeout = opts.timeout
        self._content_type = opts.content_type

    def get_status(
        self,
        req: GetStatusRequest,
        options: Optional[SSEServiceCallOptions] = None,
    ) -> StatusResponse:
        """Calls test.sse.SSEService.GetStatus."""
        opts = options or SSEServiceCallOptions()
        content_type = opts.content_type or self._content_type
        if content_type != "application/json":
            raise NotImplementedError("only application/json is implemented; see docs/python-generation.md")
        path = "/api/v1/status"
        headers: dict[str, str] = dict(self._default_headers)
        headers["Content-Type"] = content_type
        headers["Accept"] = "application/json"
        if opts.headers:
            headers.update(opts.headers)
        body: Optional[bytes] = None
        resp = self._transport.request(
            method="GET",
            url=self._base_url + path,
            headers=headers,
            body=body,
            timeout=opts.timeout if opts.timeout is not None else self._timeout,
        )
        if resp.status >= 400:
            self._raise_for_status(resp)
        if not resp.body:
            return StatusResponse()
        return StatusResponse.from_dict(json.loads(resp.body))

    def stream_events(
        self,
        req: StreamEventsRequest,
        options: Optional[SSEServiceCallOptions] = None,
    ) -> Iterator[Event]:
        """SSE streaming is not yet supported by protoc-gen-py-client."""
        raise NotImplementedError(
            "SSE streaming is not yet supported in py-client. "
            "Track support at https://github.com/SebastienMelki/sebuf/issues (label: py-client)."
        )
    def stream_resource_events(
        self,
        req: StreamResourceEventsRequest,
        options: Optional[SSEServiceCallOptions] = None,
    ) -> Iterator[ResourceEvent]:
        """SSE streaming is not yet supported by protoc-gen-py-client."""
        raise NotImplementedError(
            "SSE streaming is not yet supported in py-client. "
            "Track support at https://github.com/SebastienMelki/sebuf/issues (label: py-client)."
        )
    def stream_filtered_events(
        self,
        req: StreamFilteredEventsRequest,
        options: Optional[SSEServiceCallOptions] = None,
    ) -> Iterator[Event]:
        """SSE streaming is not yet supported by protoc-gen-py-client."""
        raise NotImplementedError(
            "SSE streaming is not yet supported in py-client. "
            "Track support at https://github.com/SebastienMelki/sebuf/issues (label: py-client)."
        )
    def _raise_for_status(self, resp: HttpResponse) -> None:
        """Map a non-2xx response to the most specific exception available."""
        body = resp.body or b""
        parsed: Any = None
        ctype = (resp.headers or {}).get("Content-Type", "")
        looks_jsonish = "json" in ctype.lower() or body[:1] in (b"{", b"[")
        if looks_jsonish:
            try:
                parsed = json.loads(body.decode("utf-8"))
            except (ValueError, UnicodeDecodeError):
                parsed = None
        if resp.status == 400 and isinstance(parsed, dict) and "violations" in parsed:
            violations = [
                FieldViolation(field=v.get("field", ""), description=v.get("description", ""))
                for v in parsed.get("violations", [])
            ]
            raise ValidationError(resp.status, body, resp.headers, violations)
        if isinstance(parsed, dict):
            for err_cls, required_keys in _ERROR_CLASSES:
                if required_keys and required_keys.issubset(parsed.keys()):
                    raise err_cls.populate(resp.status, body, resp.headers, parsed)
        raise ApiError(resp.status, body, resp.headers)

