// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: http_verbs_comprehensive.proto

package generated

import (
	"context"

	sebufhttp "github.com/SebastienMelki/sebuf/http"
)

// RESTfulAPIServiceServer is the server API for RESTfulAPIService service.
type RESTfulAPIServiceServer interface {
	ListResources(context.Context, *ListResourcesRequest) (*ListResourcesResponse, error)
	GetResource(context.Context, *GetResourceRequest) (*Resource, error)
	GetNestedResource(context.Context, *GetNestedResourceRequest) (*Resource, error)
	CreateResource(context.Context, *CreateResourceRequest) (*Resource, error)
	UpdateResource(context.Context, *UpdateResourceRequest) (*Resource, error)
	PatchResource(context.Context, *PatchResourceRequest) (*Resource, error)
	DeleteResource(context.Context, *DeleteResourceRequest) (*DeleteResourceResponse, error)
	DefaultPostMethod(context.Context, *DefaultPostRequest) (*DefaultPostResponse, error)
}

// RegisterRESTfulAPIServiceServer registers the HTTP handlers for service RESTfulAPIService to the given mux.
func RegisterRESTfulAPIServiceServer(server RESTfulAPIServiceServer, opts ...ServerOption) error {
	config := getConfiguration(opts...)

	serviceHeaders := getRESTfulAPIServiceHeaders()

	methodHeaders := getListResourcesHeaders()
	listResourcesHandler := BindingMiddleware[ListResourcesRequest](
		genericHandler(server.ListResources, config.errorHandler), serviceHeaders, methodHeaders,
		listResourcesPathParams, listResourcesQueryParams,
		"GET", config.errorHandler,
	)

	config.mux.Handle("GET /api/v1/resources", listResourcesHandler)

	methodHeaders = getGetResourceHeaders()
	getResourceHandler := BindingMiddleware[GetResourceRequest](
		genericHandler(server.GetResource, config.errorHandler), serviceHeaders, methodHeaders,
		getResourcePathParams, getResourceQueryParams,
		"GET", config.errorHandler,
	)

	config.mux.Handle("GET /api/v1/resources/{resource_id}", getResourceHandler)

	methodHeaders = getGetNestedResourceHeaders()
	getNestedResourceHandler := BindingMiddleware[GetNestedResourceRequest](
		genericHandler(server.GetNestedResource, config.errorHandler), serviceHeaders, methodHeaders,
		getNestedResourcePathParams, getNestedResourceQueryParams,
		"GET", config.errorHandler,
	)

	config.mux.Handle("GET /api/v1/orgs/{org_id}/teams/{team_id}/resources/{resource_id}", getNestedResourceHandler)

	methodHeaders = getCreateResourceHeaders()
	createResourceHandler := BindingMiddleware[CreateResourceRequest](
		genericHandler(server.CreateResource, config.errorHandler), serviceHeaders, methodHeaders,
		createResourcePathParams, createResourceQueryParams,
		"POST", config.errorHandler,
	)

	config.mux.Handle("POST /api/v1/resources", createResourceHandler)

	methodHeaders = getUpdateResourceHeaders()
	updateResourceHandler := BindingMiddleware[UpdateResourceRequest](
		genericHandler(server.UpdateResource, config.errorHandler), serviceHeaders, methodHeaders,
		updateResourcePathParams, updateResourceQueryParams,
		"PUT", config.errorHandler,
	)

	config.mux.Handle("PUT /api/v1/resources/{resource_id}", updateResourceHandler)

	methodHeaders = getPatchResourceHeaders()
	patchResourceHandler := BindingMiddleware[PatchResourceRequest](
		genericHandler(server.PatchResource, config.errorHandler), serviceHeaders, methodHeaders,
		patchResourcePathParams, patchResourceQueryParams,
		"PATCH", config.errorHandler,
	)

	config.mux.Handle("PATCH /api/v1/resources/{resource_id}", patchResourceHandler)

	methodHeaders = getDeleteResourceHeaders()
	deleteResourceHandler := BindingMiddleware[DeleteResourceRequest](
		genericHandler(server.DeleteResource, config.errorHandler), serviceHeaders, methodHeaders,
		deleteResourcePathParams, deleteResourceQueryParams,
		"DELETE", config.errorHandler,
	)

	config.mux.Handle("DELETE /api/v1/resources/{resource_id}", deleteResourceHandler)

	methodHeaders = getDefaultPostMethodHeaders()
	defaultPostMethodHandler := BindingMiddleware[DefaultPostRequest](
		genericHandler(server.DefaultPostMethod, config.errorHandler), serviceHeaders, methodHeaders,
		defaultPostMethodPathParams, defaultPostMethodQueryParams,
		"POST", config.errorHandler,
	)

	config.mux.Handle("POST /api/v1/legacy/action", defaultPostMethodHandler)

	return nil
}

// getRESTfulAPIServiceHeaders returns the service-level required headers for RESTfulAPIService
func getRESTfulAPIServiceHeaders() []*sebufhttp.Header {
	return []*sebufhttp.Header{
		{
			Name:        "X-API-Key",
			Description: "API key for authentication",
			Type:        "string",
			Required:    true,
			Format:      "uuid",
			Example:     "",
			Deprecated:  false,
		},
	}
}

// getListResourcesHeaders returns the method-level required headers for ListResources
func getListResourcesHeaders() []*sebufhttp.Header {
	return nil
}

// getGetResourceHeaders returns the method-level required headers for GetResource
func getGetResourceHeaders() []*sebufhttp.Header {
	return nil
}

// getGetNestedResourceHeaders returns the method-level required headers for GetNestedResource
func getGetNestedResourceHeaders() []*sebufhttp.Header {
	return nil
}

// getCreateResourceHeaders returns the method-level required headers for CreateResource
func getCreateResourceHeaders() []*sebufhttp.Header {
	return []*sebufhttp.Header{
		{
			Name:        "X-Request-ID",
			Description: "",
			Type:        "string",
			Required:    true,
			Format:      "uuid",
			Example:     "",
			Deprecated:  false,
		},
	}
}

// getUpdateResourceHeaders returns the method-level required headers for UpdateResource
func getUpdateResourceHeaders() []*sebufhttp.Header {
	return nil
}

// getPatchResourceHeaders returns the method-level required headers for PatchResource
func getPatchResourceHeaders() []*sebufhttp.Header {
	return nil
}

// getDeleteResourceHeaders returns the method-level required headers for DeleteResource
func getDeleteResourceHeaders() []*sebufhttp.Header {
	return nil
}

// getDefaultPostMethodHeaders returns the method-level required headers for DefaultPostMethod
func getDefaultPostMethodHeaders() []*sebufhttp.Header {
	return nil
}

// listResourcesPathParams contains path parameter configuration for ListResources
var listResourcesPathParams = []PathParamConfig{}

// listResourcesQueryParams contains query parameter configuration for ListResources
var listResourcesQueryParams = []QueryParamConfig{
	{QueryName: "page", FieldName: "page", Required: false},
	{QueryName: "page_size", FieldName: "page_size", Required: false},
	{QueryName: "filter", FieldName: "filter", Required: false},
	{QueryName: "include_deleted", FieldName: "include_deleted", Required: false},
}

// getResourcePathParams contains path parameter configuration for GetResource
var getResourcePathParams = []PathParamConfig{
	{URLParam: "resource_id", FieldName: "resource_id"},
}

// getResourceQueryParams contains query parameter configuration for GetResource
var getResourceQueryParams = []QueryParamConfig{}

// getNestedResourcePathParams contains path parameter configuration for GetNestedResource
var getNestedResourcePathParams = []PathParamConfig{
	{URLParam: "org_id", FieldName: "org_id"},
	{URLParam: "team_id", FieldName: "team_id"},
	{URLParam: "resource_id", FieldName: "resource_id"},
}

// getNestedResourceQueryParams contains query parameter configuration for GetNestedResource
var getNestedResourceQueryParams = []QueryParamConfig{}

// createResourcePathParams contains path parameter configuration for CreateResource
var createResourcePathParams = []PathParamConfig{}

// createResourceQueryParams contains query parameter configuration for CreateResource
var createResourceQueryParams = []QueryParamConfig{}

// updateResourcePathParams contains path parameter configuration for UpdateResource
var updateResourcePathParams = []PathParamConfig{
	{URLParam: "resource_id", FieldName: "resource_id"},
}

// updateResourceQueryParams contains query parameter configuration for UpdateResource
var updateResourceQueryParams = []QueryParamConfig{}

// patchResourcePathParams contains path parameter configuration for PatchResource
var patchResourcePathParams = []PathParamConfig{
	{URLParam: "resource_id", FieldName: "resource_id"},
}

// patchResourceQueryParams contains query parameter configuration for PatchResource
var patchResourceQueryParams = []QueryParamConfig{}

// deleteResourcePathParams contains path parameter configuration for DeleteResource
var deleteResourcePathParams = []PathParamConfig{
	{URLParam: "resource_id", FieldName: "resource_id"},
}

// deleteResourceQueryParams contains query parameter configuration for DeleteResource
var deleteResourceQueryParams = []QueryParamConfig{}

// defaultPostMethodPathParams contains path parameter configuration for DefaultPostMethod
var defaultPostMethodPathParams = []PathParamConfig{}

// defaultPostMethodQueryParams contains query parameter configuration for DefaultPostMethod
var defaultPostMethodQueryParams = []QueryParamConfig{}

// BackwardCompatServiceServer is the server API for BackwardCompatService service.
type BackwardCompatServiceServer interface {
	LegacyAction(context.Context, *LegacyRequest) (*LegacyResponse, error)
}

// RegisterBackwardCompatServiceServer registers the HTTP handlers for service BackwardCompatService to the given mux.
func RegisterBackwardCompatServiceServer(server BackwardCompatServiceServer, opts ...ServerOption) error {
	config := getConfiguration(opts...)

	serviceHeaders := getBackwardCompatServiceHeaders()

	methodHeaders := getLegacyActionHeaders()
	legacyActionHandler := BindingMiddleware[LegacyRequest](
		genericHandler(server.LegacyAction, config.errorHandler), serviceHeaders, methodHeaders,
		legacyActionPathParams, legacyActionQueryParams,
		"POST", config.errorHandler,
	)

	config.mux.Handle("POST /generated/legacy_action", legacyActionHandler)

	return nil
}

// getBackwardCompatServiceHeaders returns the service-level required headers for BackwardCompatService
func getBackwardCompatServiceHeaders() []*sebufhttp.Header {
	return nil
}

// getLegacyActionHeaders returns the method-level required headers for LegacyAction
func getLegacyActionHeaders() []*sebufhttp.Header {
	return nil
}

// legacyActionPathParams contains path parameter configuration for LegacyAction
var legacyActionPathParams = []PathParamConfig{}

// legacyActionQueryParams contains query parameter configuration for LegacyAction
var legacyActionQueryParams = []QueryParamConfig{}
