// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: int64_deep_nested_encoding.proto

package int64deepnested

import (
	"context"

	sebufhttp "github.com/SebastienMelki/sebuf/http"
)

// DeepNestedServiceServer is the server API for DeepNestedService service.
type DeepNestedServiceServer interface {
	GetOuter(context.Context, *DeepRequest) (*Outer, error)
	GetOuterList(context.Context, *DeepRequest) (*OuterList, error)
	GetNode(context.Context, *DeepRequest) (*NodeHolder, error)
}

// RegisterDeepNestedServiceServer registers the HTTP handlers for service DeepNestedService to the given mux.
func RegisterDeepNestedServiceServer(server DeepNestedServiceServer, opts ...ServerOption) error {
	config := getConfiguration(opts...)

	serviceHeaders := getDeepNestedServiceHeaders()

	methodHeaders := getGetOuterHeaders()
	getOuterHandler := BindingMiddleware[DeepRequest](
		genericHandler(server.GetOuter, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		getOuterPathParams, getOuterQueryParams,
		"POST", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("POST /api/v1/outer", getOuterHandler)

	methodHeaders = getGetOuterListHeaders()
	getOuterListHandler := BindingMiddleware[DeepRequest](
		genericHandler(server.GetOuterList, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		getOuterListPathParams, getOuterListQueryParams,
		"POST", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("POST /api/v1/outer-list", getOuterListHandler)

	methodHeaders = getGetNodeHeaders()
	getNodeHandler := BindingMiddleware[DeepRequest](
		genericHandler(server.GetNode, config.errorHandler, config.marshalOpts), serviceHeaders, methodHeaders,
		getNodePathParams, getNodeQueryParams,
		"POST", config.errorHandler, config.marshalOpts,
	)

	config.mux.Handle("POST /api/v1/node", getNodeHandler)

	return nil
}

// getDeepNestedServiceHeaders returns the service-level required headers for DeepNestedService
func getDeepNestedServiceHeaders() []*sebufhttp.Header {
	return nil
}

// getGetOuterHeaders returns the method-level required headers for GetOuter
func getGetOuterHeaders() []*sebufhttp.Header {
	return nil
}

// getGetOuterListHeaders returns the method-level required headers for GetOuterList
func getGetOuterListHeaders() []*sebufhttp.Header {
	return nil
}

// getGetNodeHeaders returns the method-level required headers for GetNode
func getGetNodeHeaders() []*sebufhttp.Header {
	return nil
}

// getOuterPathParams contains path parameter configuration for GetOuter
var getOuterPathParams = []PathParamConfig{}

// getOuterQueryParams contains query parameter configuration for GetOuter
var getOuterQueryParams = []QueryParamConfig{}

// getOuterListPathParams contains path parameter configuration for GetOuterList
var getOuterListPathParams = []PathParamConfig{}

// getOuterListQueryParams contains query parameter configuration for GetOuterList
var getOuterListQueryParams = []QueryParamConfig{}

// getNodePathParams contains path parameter configuration for GetNode
var getNodePathParams = []PathParamConfig{}

// getNodeQueryParams contains query parameter configuration for GetNode
var getNodeQueryParams = []QueryParamConfig{}
