// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: nullable.proto

package nullable

import (
	"encoding/json"

	"google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSONSebuf implements sebufMarshaler for User.
// This method composes sebuf JSON mapping annotations and nested message delegation.
func (x *User) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Handle nullable field: middle_name
	// proto3 optional + nullable=true: emit null when not set
	if x.MiddleName == nil {
		raw["middleName"] = []byte("null")
	}

	// Handle nullable field: age
	// proto3 optional + nullable=true: emit null when not set
	if x.Age == nil {
		raw["age"] = []byte("null")
	}

	// Handle nullable field: is_verified
	// proto3 optional + nullable=true: emit null when not set
	if x.IsVerified == nil {
		raw["isVerified"] = []byte("null")
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for User.
func (x *User) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for User.
// This method composes inverse sebuf JSON mapping annotations and nested message delegation.
func (x *User) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Handle nullable field: middle_name
	for _, k := range []string{"middleName", "middle_name"} {
		if rawVal, ok := raw[k]; ok && string(rawVal) == "null" {
			delete(raw, k)
		}
	}

	// Handle nullable field: age
	for _, k := range []string{"age"} {
		if rawVal, ok := raw[k]; ok && string(rawVal) == "null" {
			delete(raw, k)
		}
	}

	// Handle nullable field: is_verified
	for _, k := range []string{"isVerified", "is_verified"} {
		if rawVal, ok := raw[k]; ok && string(rawVal) == "null" {
			delete(raw, k)
		}
	}

	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for User.
func (x *User) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for UpdateUserRequest.
// This method composes sebuf JSON mapping annotations and nested message delegation.
func (x *UpdateUserRequest) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Delegate nested JSON mapping for field: user
	if x.User != nil {
		var data []byte
		var err error
		if m, ok := any(x.User).(interface {
			MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
		}); ok {
			data, err = m.MarshalJSONSebuf(opts)
		} else {
			data, err = opts.Marshal(x.User)
		}
		if err != nil {
			return nil, err
		}
		raw["user"] = data
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for UpdateUserRequest.
func (x *UpdateUserRequest) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for UpdateUserRequest.
// This method composes inverse sebuf JSON mapping annotations and nested message delegation.
func (x *UpdateUserRequest) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Delegate nested JSON unmarshal for field: user
	for _, k := range []string{"user"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		if string(rawVal) == "null" {
			continue
		}
		inner := &User{}
		if u, ok := any(inner).(interface {
			UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
		}); ok {
			if err := u.UnmarshalJSONSebuf(rawVal, opts); err != nil {
				return err
			}
		} else if err := json.Unmarshal(rawVal, inner); err != nil {
			return err
		}
		innerJSON, marshalErr := protojson.Marshal(inner)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = innerJSON
	}

	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for UpdateUserRequest.
func (x *UpdateUserRequest) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}
