// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: timestamp_format.proto

package timestampformat

import (
	"encoding/json"
	"time"

	"google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSONSebuf implements sebufMarshaler for TimestampFormatTest.
// This method composes sebuf JSON mapping annotations and nested message delegation.
func (x *TimestampFormatTest) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Convert unix_seconds_ts to TIMESTAMP_FORMAT_UNIX_SECONDS format
	if x.UnixSecondsTs != nil {
		t := x.UnixSecondsTs.AsTime()
		data, _ = json.Marshal(t.Unix())
		if opts.UseProtoNames {
			raw["unix_seconds_ts"] = data
			delete(raw, "unixSecondsTs")
		} else {
			raw["unixSecondsTs"] = data
			delete(raw, "unix_seconds_ts")
		}
	}

	// Convert unix_millis_ts to TIMESTAMP_FORMAT_UNIX_MILLIS format
	if x.UnixMillisTs != nil {
		t := x.UnixMillisTs.AsTime()
		data, _ = json.Marshal(t.UnixMilli())
		if opts.UseProtoNames {
			raw["unix_millis_ts"] = data
			delete(raw, "unixMillisTs")
		} else {
			raw["unixMillisTs"] = data
			delete(raw, "unix_millis_ts")
		}
	}

	// Convert date_ts to TIMESTAMP_FORMAT_DATE format
	if x.DateTs != nil {
		t := x.DateTs.AsTime()
		data, _ = json.Marshal(t.Format("2006-01-02"))
		if opts.UseProtoNames {
			raw["date_ts"] = data
			delete(raw, "dateTs")
		} else {
			raw["dateTs"] = data
			delete(raw, "date_ts")
		}
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for TimestampFormatTest.
func (x *TimestampFormatTest) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for TimestampFormatTest.
// This method composes inverse sebuf JSON mapping annotations and nested message delegation.
func (x *TimestampFormatTest) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Convert unix_seconds_ts from TIMESTAMP_FORMAT_UNIX_SECONDS to RFC 3339 for protojson
	for _, k := range []string{"unixSecondsTs", "unix_seconds_ts"} {
		if v, ok := raw[k]; ok {
			var n int64
			if err := json.Unmarshal(v, &n); err == nil {
				t := time.Unix(n, 0)
				raw[k], _ = json.Marshal(t.Format(time.RFC3339Nano))
			}
		}
	}

	// Convert unix_millis_ts from TIMESTAMP_FORMAT_UNIX_MILLIS to RFC 3339 for protojson
	for _, k := range []string{"unixMillisTs", "unix_millis_ts"} {
		if v, ok := raw[k]; ok {
			var n int64
			if err := json.Unmarshal(v, &n); err == nil {
				t := time.UnixMilli(n)
				raw[k], _ = json.Marshal(t.Format(time.RFC3339Nano))
			}
		}
	}

	// Convert date_ts from TIMESTAMP_FORMAT_DATE to RFC 3339 for protojson
	for _, k := range []string{"dateTs", "date_ts"} {
		if v, ok := raw[k]; ok {
			var s string
			if err := json.Unmarshal(v, &s); err == nil {
				t, parseErr := time.Parse("2006-01-02", s)
				if parseErr == nil {
					raw[k], _ = json.Marshal(t.Format(time.RFC3339Nano))
				}
			}
		}
	}

	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for TimestampFormatTest.
func (x *TimestampFormatTest) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}
