// Code generated by protoc-gen-go-http. DO NOT EDIT.
// source: unwrap_int64_encoding.proto

package unwrapint64encoding

import (
	"encoding/json"
	"fmt"
	"strconv"

	"google.golang.org/protobuf/encoding/protojson"
)

// MarshalJSONSebuf implements sebufMarshaler for Bar.
// This method composes sebuf JSON mapping annotations and nested message delegation.
func (x *Bar) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Convert Volume from string to number
	if x.Volume != 0 {
		data, _ = json.Marshal(x.Volume)
		raw["volume"] = data
	} else {
		// Remove the field if zero (proto3 default behavior)
		delete(raw, "volume")
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for Bar.
func (x *Bar) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for Bar.
// This method composes inverse sebuf JSON mapping annotations and nested message delegation.
func (x *Bar) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Convert volume from number to string for protojson
	for _, k := range []string{"volume"} {
		if rawVal, ok := raw[k]; ok {
			var num int64
			if err := json.Unmarshal(rawVal, &num); err == nil {
				raw[k], _ = json.Marshal(strconv.FormatInt(num, 10))
			}
		}
	}

	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for Bar.
func (x *Bar) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for UnwrapWrapper.
// This method composes sebuf JSON mapping annotations and nested message delegation.
func (x *UnwrapWrapper) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Delegate nested JSON mapping for repeated field: items
	if len(x.Items) > 0 {
		items := make([]json.RawMessage, 0, len(x.Items))
		for _, item := range x.Items {
			var data []byte
			var err error
			if m, ok := any(item).(interface {
				MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
			}); ok {
				data, err = m.MarshalJSONSebuf(opts)
			} else {
				data, err = opts.Marshal(item)
			}
			if err != nil {
				return nil, err
			}
			items = append(items, data)
		}
		data, err := json.Marshal(items)
		if err != nil {
			return nil, err
		}
		raw["items"] = data
	}

	// Apply root-level unwrap last.
	for _, k := range []string{"items"} {
		if rootRaw, ok := raw[k]; ok {
			return rootRaw, nil
		}
	}
	return []byte("[]"), nil
}

// MarshalJSON implements json.Marshaler for UnwrapWrapper.
func (x *UnwrapWrapper) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for UnwrapWrapper.
// This method composes inverse sebuf JSON mapping annotations and nested message delegation.
func (x *UnwrapWrapper) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	var raw map[string]json.RawMessage
	// Invert root-level unwrap before other transforms.
	raw = make(map[string]json.RawMessage, 1)
	raw["items"] = data

	// Delegate nested JSON unmarshal for repeated field: items
	for _, k := range []string{"items"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		var rawItems []json.RawMessage
		if err := json.Unmarshal(rawVal, &rawItems); err != nil {
			return err
		}
		protoItems := make([]json.RawMessage, len(rawItems))
		for i, itemRaw := range rawItems {
			inner := &Bar{}
			if u, ok := any(inner).(interface {
				UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
			}); ok {
				if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
					return err
				}
			} else if err := json.Unmarshal(itemRaw, inner); err != nil {
				return err
			}
			itemJSON, marshalErr := protojson.Marshal(inner)
			if marshalErr != nil {
				return marshalErr
			}
			protoItems[i] = itemJSON
		}
		protoJSON, marshalErr := json.Marshal(protoItems)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = protoJSON
	}

	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for UnwrapWrapper.
func (x *UnwrapWrapper) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for Meta.
// This method composes sebuf JSON mapping annotations and nested message delegation.
func (x *Meta) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Convert Timestamp from string to number
	if x.Timestamp != 0 {
		data, _ = json.Marshal(x.Timestamp)
		raw["timestamp"] = data
	} else {
		// Remove the field if zero (proto3 default behavior)
		delete(raw, "timestamp")
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for Meta.
func (x *Meta) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for Meta.
// This method composes inverse sebuf JSON mapping annotations and nested message delegation.
func (x *Meta) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Convert timestamp from number to string for protojson
	for _, k := range []string{"timestamp"} {
		if rawVal, ok := raw[k]; ok {
			var num int64
			if err := json.Unmarshal(rawVal, &num); err == nil {
				raw[k], _ = json.Marshal(strconv.FormatInt(num, 10))
			}
		}
	}

	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for Meta.
func (x *Meta) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}

// MarshalJSONSebuf implements sebufMarshaler for CombinedResponse.
// This method composes sebuf JSON mapping annotations and nested message delegation.
func (x *CombinedResponse) MarshalJSONSebuf(opts protojson.MarshalOptions) ([]byte, error) {
	if x == nil {
		return []byte("null"), nil
	}
	data, err := opts.Marshal(x)
	if err != nil {
		return nil, err
	}
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return nil, err
	}

	// Delegate nested JSON mapping for field: meta
	if x.Meta != nil {
		var data []byte
		var err error
		if m, ok := any(x.Meta).(interface {
			MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
		}); ok {
			data, err = m.MarshalJSONSebuf(opts)
		} else {
			data, err = opts.Marshal(x.Meta)
		}
		if err != nil {
			return nil, err
		}
		raw["meta"] = data
	}

	// Handle unwrap map field: Data
	for _, k := range []string{"data"} {
		rawField, ok := raw[k]
		if !ok {
			continue
		}
		var mapData map[string]json.RawMessage
		if err := json.Unmarshal(rawField, &mapData); err != nil {
			return nil, err
		}
		for mapKey, wrapperRaw := range mapData {
			if string(wrapperRaw) == "null" {
				continue
			}
			var wrapperObject map[string]json.RawMessage
			if err := json.Unmarshal(wrapperRaw, &wrapperObject); err != nil {
				return nil, err
			}
			arrayData, ok := wrapperObject["items"]
			for goKey, wrapper := range x.Data {
				if fmt.Sprint(goKey) != mapKey || wrapper == nil {
					continue
				}
				items := make([]json.RawMessage, 0, len(wrapper.GetItems()))
				for _, item := range wrapper.GetItems() {
					var data []byte
					var err error
					if m, ok := any(item).(interface {
						MarshalJSONSebuf(protojson.MarshalOptions) ([]byte, error)
					}); ok {
						data, err = m.MarshalJSONSebuf(opts)
					} else {
						data, err = opts.Marshal(item)
					}
					if err != nil {
						return nil, err
					}
					items = append(items, data)
				}
				rewrittenArray, err := json.Marshal(items)
				if err != nil {
					return nil, err
				}
				arrayData = rewrittenArray
				ok = true
				break
			}
			if !ok {
				continue
			}
			mapData[mapKey] = arrayData
		}
		data, err := json.Marshal(mapData)
		if err != nil {
			return nil, err
		}
		raw[k] = data
	}

	return json.Marshal(raw)
}

// MarshalJSON implements json.Marshaler for CombinedResponse.
func (x *CombinedResponse) MarshalJSON() ([]byte, error) {
	return x.MarshalJSONSebuf(protojson.MarshalOptions{})
}

// UnmarshalJSONSebuf implements sebufUnmarshaler for CombinedResponse.
// This method composes inverse sebuf JSON mapping annotations and nested message delegation.
func (x *CombinedResponse) UnmarshalJSONSebuf(data []byte, opts protojson.UnmarshalOptions) error {
	var raw map[string]json.RawMessage
	if err := json.Unmarshal(data, &raw); err != nil {
		return err
	}

	// Re-wrap map values for unwrap field: data
	for _, k := range []string{"data"} {
		rawField, ok := raw[k]
		if !ok {
			continue
		}
		var mapRaw map[string]json.RawMessage
		if err := json.Unmarshal(rawField, &mapRaw); err != nil {
			return err
		}
		for mapKey, arrayRaw := range mapRaw {
			var itemsRaw []json.RawMessage
			if err := json.Unmarshal(arrayRaw, &itemsRaw); err != nil {
				return err
			}
			protoItems := make([]json.RawMessage, len(itemsRaw))
			for i, itemRaw := range itemsRaw {
				inner := &Bar{}
				if u, ok := any(inner).(interface {
					UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
				}); ok {
					if err := u.UnmarshalJSONSebuf(itemRaw, opts); err != nil {
						return err
					}
				} else if err := json.Unmarshal(itemRaw, inner); err != nil {
					return err
				}
				itemJSON, marshalErr := protojson.Marshal(inner)
				if marshalErr != nil {
					return marshalErr
				}
				protoItems[i] = itemJSON
			}
			rewrittenArray, marshalErr := json.Marshal(protoItems)
			if marshalErr != nil {
				return marshalErr
			}
			arrayRaw = rewrittenArray
			wrapperRaw := map[string]json.RawMessage{
				"items": arrayRaw,
			}
			wrapperData, marshalErr := json.Marshal(wrapperRaw)
			if marshalErr != nil {
				return marshalErr
			}
			mapRaw[mapKey] = wrapperData
		}
		rewrapped, marshalErr := json.Marshal(mapRaw)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = rewrapped
	}

	// Delegate nested JSON unmarshal for field: meta
	for _, k := range []string{"meta"} {
		rawVal, ok := raw[k]
		if !ok {
			continue
		}
		if string(rawVal) == "null" {
			continue
		}
		inner := &Meta{}
		if u, ok := any(inner).(interface {
			UnmarshalJSONSebuf([]byte, protojson.UnmarshalOptions) error
		}); ok {
			if err := u.UnmarshalJSONSebuf(rawVal, opts); err != nil {
				return err
			}
		} else if err := json.Unmarshal(rawVal, inner); err != nil {
			return err
		}
		innerJSON, marshalErr := protojson.Marshal(inner)
		if marshalErr != nil {
			return marshalErr
		}
		raw[k] = innerJSON
	}

	modified, err := json.Marshal(raw)
	if err != nil {
		return err
	}
	return opts.Unmarshal(modified, x)
}

// UnmarshalJSON implements json.Unmarshaler for CombinedResponse.
func (x *CombinedResponse) UnmarshalJSON(data []byte) error {
	return x.UnmarshalJSONSebuf(data, protojson.UnmarshalOptions{})
}
